// cards_collection.js — данные для 6-го модуля игры «Предложи партнеру»:
// «Коллекция» — 109 позиций личной коллекции (доп. набор рядом с «Секс-шоп»).
// Без номера-значка «№...» (в отличие от cards_sexshop.js) — список не является
// рейтингом продаж, порядок позиций произвольный. Оценки ♀/♂ при этом есть.
// - forWhom — для кого подходит товар (ей / ему / обоим партнёрам);
// - womenRating/menRating — оценки партнёров от 0 до 10.
// level (здесь всегда 6 — отдельный модуль), image (путь к фото в photos_shop/),
// title (название) и text (краткое описание).
//
// Фото: photos_shop/200.webp..308.webp, по одному на каждую позицию.

const COLLECTION_CARDS = [
  { level: 6, image: 'photos_shop/200.webp', title: 'Маска на глаза', text: 'Классическая маска для сенсорной депривации и ролевых игр.', forWhom: 'обоим партнёрам', womenRating: 7, menRating: 7 },
  { level: 6, image: 'photos_shop/201.webp', title: 'Секс-машина ручная', text: 'Механическое устройство с ручным управлением скоростью и глубиной.', forWhom: 'обоим партнёрам', womenRating: 8, menRating: 7 },
  { level: 6, image: 'photos_shop/202.webp', title: 'Надувная подушка для секса', text: 'Компактная надувная подушка для удобных поз во время близости.', forWhom: 'обоим партнёрам', womenRating: 7, menRating: 7 },
  { level: 6, image: 'photos_shop/203.webp', title: 'Наручники металлические с мехом', text: 'Металлические наручники с мягкой меховой отделкой для лёгкого бондажа.', forWhom: 'обоим партнёрам', womenRating: 7, menRating: 6 },
  { level: 6, image: 'photos_shop/204.webp', title: 'Плакат-игра «Постельный путеводитель»', text: 'Плакат с идеями для разнообразия интимной жизни.', forWhom: 'обоим партнёрам', womenRating: 6, menRating: 6 },
  { level: 6, image: 'photos_shop/205.webp', title: 'Маска на глаза кожаная', text: 'Кожаная маска для сенсорных игр, плотно прилегает к лицу.', forWhom: 'обоим партнёрам', womenRating: 7, menRating: 7 },
  { level: 6, image: 'photos_shop/206.webp', title: 'Маска кожаная', text: 'Кожаная маска для образов и ролевых сценариев.', forWhom: 'обоим партнёрам', womenRating: 6, menRating: 7 },
  { level: 6, image: 'photos_shop/207.webp', title: 'Электростимулятор', text: 'Устройство для электростимуляции эрогенных зон.', forWhom: 'обоим партнёрам', womenRating: 5, menRating: 6 },
  { level: 6, image: 'photos_shop/208.webp', title: 'Маска со стразами', text: 'Декоративная маска со стразами для романтических вечеров.', forWhom: 'ей', womenRating: 7, menRating: 6 },
  { level: 6, image: 'photos_shop/209.webp', title: 'Лопатка для шлепков', text: 'Лёгкая лопатка для игр со шлепками.', forWhom: 'обоим партнёрам', womenRating: 6, menRating: 7 },
  { level: 6, image: 'photos_shop/210.webp', title: 'Мастурбатор автоматический', text: 'Автоматическое устройство с вращением и сжатием.', forWhom: 'ему', womenRating: 2, menRating: 9 },
  { level: 6, image: 'photos_shop/211.webp', title: 'Перо', text: 'Перо для лёгких щекочущих ласк по телу.', forWhom: 'обоим партнёрам', womenRating: 7, menRating: 6 },
  { level: 6, image: 'photos_shop/212.webp', title: 'Вибратор-кролик', text: 'Двойная стимуляция клитора и точки G.', forWhom: 'ей', womenRating: 9, menRating: 6 },
  { level: 6, image: 'photos_shop/213.webp', title: 'Плётка кожаная', text: 'Кожаная плётка для BDSM-игр.', forWhom: 'обоим партнёрам', womenRating: 5, menRating: 6 },
  { level: 6, image: 'photos_shop/214.webp', title: 'Поводок с ремешком', text: 'Ошейник с поводком для ролевых сценариев подчинения.', forWhom: 'обоим партнёрам', womenRating: 5, menRating: 6 },
  { level: 6, image: 'photos_shop/215.webp', title: 'Кляп красный', text: 'Красный кляп-шарик для ролевых игр.', forWhom: 'обоим партнёрам', womenRating: 5, menRating: 6 },
  { level: 6, image: 'photos_shop/216.webp', title: 'Трусы для страпона', text: 'Трусы-крепление для страпона.', forWhom: 'ей', womenRating: 6, menRating: 5 },
  { level: 6, image: 'photos_shop/217.webp', title: 'Карабины для бондажа', text: 'Металлические карабины для фиксации в бондаж-играх.', forWhom: 'обоим партнёрам', womenRating: 5, menRating: 6 },
  { level: 6, image: 'photos_shop/218.webp', title: 'Бондаж: фиксация рук к бёдрам', text: 'Комплект ремней для фиксации рук к бёдрам.', forWhom: 'обоим партнёрам', womenRating: 5, menRating: 6 },
  { level: 6, image: 'photos_shop/219.webp', title: 'Бондаж: фиксация рук к ногам', text: 'Комплект ремней для фиксации рук к ногам.', forWhom: 'обоим партнёрам', womenRating: 5, menRating: 6 },
  { level: 6, image: 'photos_shop/220.webp', title: 'Мастурбатор с подогревом', text: 'Мастурбатор с функцией подогрева для более реалистичных ощущений.', forWhom: 'ему', womenRating: 2, menRating: 9 },
  { level: 6, image: 'photos_shop/221.webp', title: 'Насадка на вибратор (имитация куннилингуса)', text: 'Насадка, имитирующая оральные ласки.', forWhom: 'ей', womenRating: 8, menRating: 5 },
  { level: 6, image: 'photos_shop/222.webp', title: 'Анальная пробка тонкая', text: 'Тонкая анальная пробка для новичков.', forWhom: 'обоим партнёрам', womenRating: 6, menRating: 6 },
  { level: 6, image: 'photos_shop/223.webp', title: 'Фаллос стеклянный', text: 'Стеклянный фаллоимитатор, подходит для температурных игр.', forWhom: 'ей', womenRating: 7, menRating: 5 },
  { level: 6, image: 'photos_shop/224.webp', title: 'Спрей-пролонгатор', text: 'Спрей для продления полового акта.', forWhom: 'ему', womenRating: 5, menRating: 8 },
  { level: 6, image: 'photos_shop/225.webp', title: 'Фаллос анальный тонкий, 14 см', text: 'Тонкий анальный фаллоимитатор длиной 14 см.', forWhom: 'обоим партнёрам', womenRating: 6, menRating: 6 },
  { level: 6, image: 'photos_shop/226.webp', title: 'Насадка на пенис для стимуляции клитора', text: 'Насадка на член для одновременной стимуляции клитора партнёрши.', forWhom: 'обоим партнёрам', womenRating: 8, menRating: 7 },
  { level: 6, image: 'photos_shop/227.webp', title: 'Таблетки возбуждающие', text: 'Таблетки для усиления возбуждения.', forWhom: 'обоим партнёрам', womenRating: 5, menRating: 5 },
  { level: 6, image: 'photos_shop/228.webp', title: 'Насадка на член для клитора, тонкая', text: 'Тонкая насадка для дополнительной стимуляции клитора.', forWhom: 'обоим партнёрам', womenRating: 7, menRating: 6 },
  { level: 6, image: 'photos_shop/229.webp', title: 'Двусторонний вибратор-жезл с подогревом', text: 'Двусторонний вибратор в виде жезла с функцией подогрева.', forWhom: 'ей', womenRating: 8, menRating: 5 },
  { level: 6, image: 'photos_shop/230.webp', title: 'Возбуждающие капли для женщин', text: 'Капли для усиления женского возбуждения.', forWhom: 'ей', womenRating: 6, menRating: 4 },
  { level: 6, image: 'photos_shop/231.webp', title: 'Вибратор-кролик с вращающейся головкой', text: 'Вибратор-кролик с вращающейся головкой для двойной стимуляции.', forWhom: 'ей', womenRating: 9, menRating: 6 },
  { level: 6, image: 'photos_shop/232.webp', title: 'Большой фаллос на присоске, 18 см', text: 'Крупный реалистичный фаллоимитатор на присоске, 18 см.', forWhom: 'ей', womenRating: 6, menRating: 4 },
  { level: 6, image: 'photos_shop/233.webp', title: 'Реалистичный фаллос на присоске, 14 см', text: 'Реалистичный фаллоимитатор на присоске, 14 см.', forWhom: 'ей', womenRating: 7, menRating: 5 },
  { level: 6, image: 'photos_shop/234.webp', title: 'Карточная игра на желания', text: 'Карточная игра с заданиями и желаниями для пар.', forWhom: 'обоим партнёрам', womenRating: 8, menRating: 8 },
  { level: 6, image: 'photos_shop/235.webp', title: 'Электрическая помпа для увеличения члена', text: 'Электрическая вакуумная помпа для увеличения члена.', forWhom: 'ему', womenRating: 3, menRating: 8 },
  { level: 6, image: 'photos_shop/236.webp', title: 'Расширитель вагинальный', text: 'Набор расширителей для растяжки перед крупными игрушками.', forWhom: 'ей', womenRating: 5, menRating: 3 },
  { level: 6, image: 'photos_shop/237.webp', title: 'Свечи с низкой температурой плавления', text: 'Восковые свечи для чувственных игр с горячим воском.', forWhom: 'обоим партнёрам', womenRating: 6, menRating: 6 },
  { level: 6, image: 'photos_shop/238.webp', title: 'Анальная ёлочка', text: 'Анальная цепочка в форме ёлочки с возрастающим диаметром.', forWhom: 'обоим партнёрам', womenRating: 6, menRating: 6 },
  { level: 6, image: 'photos_shop/239.webp', title: 'Массажёр простаты', text: 'Массажёр для стимуляции простаты.', forWhom: 'ему', womenRating: 3, menRating: 8 },
  { level: 6, image: 'photos_shop/240.webp', title: 'Вибропуля', text: 'Компактная вибропуля для точечной стимуляции.', forWhom: 'ей', womenRating: 8, menRating: 5 },
  { level: 6, image: 'photos_shop/241.webp', title: 'Анальные бусы', text: 'Классические анальные бусы.', forWhom: 'обоим партнёрам', womenRating: 6, menRating: 6 },
  { level: 6, image: 'photos_shop/242.webp', title: 'Массажёр простаты для секса', text: 'Массажёр простаты, рассчитанный на использование во время секса.', forWhom: 'ему', womenRating: 3, menRating: 8 },
  { level: 6, image: 'photos_shop/243.webp', title: 'Анальная пробка с вибрацией и пультом', text: 'Анальная пробка с вибрацией и пультом дистанционного управления.', forWhom: 'обоим партнёрам', womenRating: 7, menRating: 7 },
  { level: 6, image: 'photos_shop/244.webp', title: 'Анальный вибратор — массажёр простаты', text: 'Анальный вибратор двойного назначения для массажа простаты.', forWhom: 'ему', womenRating: 3, menRating: 8 },
  { level: 6, image: 'photos_shop/245.webp', title: 'Шарики Кегеля средние', text: 'Вагинальные шарики среднего размера для тренировки мышц.', forWhom: 'ей', womenRating: 6, menRating: 4 },
  { level: 6, image: 'photos_shop/246.webp', title: 'Шарики Кегеля маленькие', text: 'Вагинальные шарики маленького размера для новичков.', forWhom: 'ей', womenRating: 6, menRating: 3 },
  { level: 6, image: 'photos_shop/247.webp', title: 'Мягкие наручники', text: 'Мягкие наручники на меху для комфортной фиксации.', forWhom: 'обоим партнёрам', womenRating: 7, menRating: 7 },
  { level: 6, image: 'photos_shop/248.webp', title: 'Мини-насадка на член для клитора', text: 'Компактная насадка для дополнительной стимуляции клитора.', forWhom: 'обоим партнёрам', womenRating: 7, menRating: 6 },
  { level: 6, image: 'photos_shop/249.webp', title: 'Анальная пробка силиконовая', text: 'Силиконовая анальная пробка, гибкая и комфортная.', forWhom: 'обоим партнёрам', womenRating: 6, menRating: 6 },
  { level: 6, image: 'photos_shop/250.webp', title: 'Набор анальных пробок разных размеров', text: 'Набор из нескольких пробок разного диаметра.', forWhom: 'обоим партнёрам', womenRating: 6, menRating: 6 },
  { level: 6, image: 'photos_shop/251.webp', title: 'Анальная пробка большая', text: 'Анальная пробка большого размера для опытных.', forWhom: 'обоим партнёрам', womenRating: 5, menRating: 6 },
  { level: 6, image: 'photos_shop/252.webp', title: 'Анальная пробка средняя', text: 'Анальная пробка среднего размера.', forWhom: 'обоим партнёрам', womenRating: 6, menRating: 6 },
  { level: 6, image: 'photos_shop/253.webp', title: 'Анальная пробка маленькая с кристаллом', text: 'Маленькая анальная пробка с декоративным кристаллом.', forWhom: 'обоим партнёрам', womenRating: 7, menRating: 6 },
  { level: 6, image: 'photos_shop/254.webp', title: 'Анальная цепочка', text: 'Анальная цепочка из нескольких шариков возрастающего размера.', forWhom: 'обоим партнёрам', womenRating: 6, menRating: 6 },
  { level: 6, image: 'photos_shop/255.webp', title: 'Вибратор с управлением через телефон', text: 'Смарт-вибратор с управлением из мобильного приложения.', forWhom: 'ей', womenRating: 8, menRating: 6 },
  { level: 6, image: 'photos_shop/256.webp', title: 'Эрекционные кольца', text: 'Набор эрекционных колец разного диаметра.', forWhom: 'ему', womenRating: 5, menRating: 8 },
  { level: 6, image: 'photos_shop/257.webp', title: 'Шарик в презерватив для увеличения объёма', text: 'Шарик, надеваемый в презерватив, для увеличения объёма.', forWhom: 'ему', womenRating: 5, menRating: 7 },
  { level: 6, image: 'photos_shop/258.webp', title: 'Клиторальный волновой вибратор', text: 'Вибратор с волновой технологией для клиторальной стимуляции.', forWhom: 'ей', womenRating: 9, menRating: 5 },
  { level: 6, image: 'photos_shop/259.webp', title: 'Пирсинг на член', text: 'Декоративный съёмный пирсинг на член.', forWhom: 'обоим партнёрам', womenRating: 5, menRating: 6 },
  { level: 6, image: 'photos_shop/260.webp', title: 'Насадка на член с шипами', text: 'Насадка с рельефными шипами для усиления ощущений партнёрши.', forWhom: 'обоим партнёрам', womenRating: 7, menRating: 6 },
  { level: 6, image: 'photos_shop/261.webp', title: 'Напальчник вибро', text: 'Вибрирующий напальчник для точечной стимуляции.', forWhom: 'ей', womenRating: 7, menRating: 5 },
  { level: 6, image: 'photos_shop/262.webp', title: 'Мастурбатор-яйцо продолговатое', text: 'Продолговатый мастурбатор-яйцо, компактный формат.', forWhom: 'ему', womenRating: 2, menRating: 8 },
  { level: 6, image: 'photos_shop/263.webp', title: 'Мастурбатор-яйцо', text: 'Компактный мастурбатор в форме яйца.', forWhom: 'ему', womenRating: 2, menRating: 8 },
  { level: 6, image: 'photos_shop/264.webp', title: 'Верёвка для связывания', text: 'Верёвка для шибари и лёгких бондаж-игр.', forWhom: 'обоим партнёрам', womenRating: 5, menRating: 6 },
  { level: 6, image: 'photos_shop/265.webp', title: 'Кляп чёрный', text: 'Чёрный кляп-шарик для ролевых сценариев.', forWhom: 'обоим партнёрам', womenRating: 5, menRating: 6 },
  { level: 6, image: 'photos_shop/266.webp', title: 'Бондаж для поддержки ноги через шею', text: 'Ремень-бондаж для фиксации ноги через шею в позах.', forWhom: 'обоим партнёрам', womenRating: 5, menRating: 6 },
  { level: 6, image: 'photos_shop/267.webp', title: 'Накладные ресницы', text: 'Накладные ресницы для романтического образа.', forWhom: 'ей', womenRating: 6, menRating: 5 },
  { level: 6, image: 'photos_shop/268.webp', title: 'Кошачьи ушки на заколках', text: 'Кошачьи ушки на заколках для ролевого образа.', forWhom: 'ей', womenRating: 6, menRating: 6 },
  { level: 6, image: 'photos_shop/269.webp', title: 'Анальная пробка с хвостом', text: 'Анальная пробка с декоративным хвостом для ролевых игр.', forWhom: 'обоим партнёрам', womenRating: 6, menRating: 6 },
  { level: 6, image: 'photos_shop/270.webp', title: 'Рожки на заколках', text: 'Декоративные рожки на заколках для образа.', forWhom: 'ей', womenRating: 5, menRating: 5 },
  { level: 6, image: 'photos_shop/271.webp', title: 'Зажимы для сосков', text: 'Регулируемые зажимы для сосков.', forWhom: 'обоим партнёрам', womenRating: 5, menRating: 6 },
  { level: 6, image: 'photos_shop/272.webp', title: 'Ленточка на шею', text: 'Атласная ленточка-чокер на шею как аксессуар образа.', forWhom: 'ей', womenRating: 6, menRating: 6 },
  { level: 6, image: 'photos_shop/273.webp', title: 'Парик женский чёрный', text: 'Чёрный парик для смены образа.', forWhom: 'ей', womenRating: 6, menRating: 6 },
  { level: 6, image: 'photos_shop/274.webp', title: 'Клизма-груша', text: 'Груша для гигиенической подготовки перед анальным сексом.', forWhom: 'обоим партнёрам', womenRating: 6, menRating: 6 },
  { level: 6, image: 'photos_shop/275.webp', title: 'Клизма', text: 'Клизма для гигиены перед анальными играми.', forWhom: 'обоим партнёрам', womenRating: 6, menRating: 6 },
  { level: 6, image: 'photos_shop/276.webp', title: 'Полоски ткани для бондажа', text: 'Тканевые полоски для мягкой фиксации в бондаж-играх.', forWhom: 'обоим партнёрам', womenRating: 5, menRating: 6 },
  { level: 6, image: 'photos_shop/277.webp', title: 'Ручная помпа', text: 'Ручная вакуумная помпа для увеличения члена.', forWhom: 'ему', womenRating: 3, menRating: 7 },
  { level: 6, image: 'photos_shop/278.webp', title: 'Ролевые очки', text: 'Очки как часть образа для ролевых сценариев.', forWhom: 'ей', womenRating: 5, menRating: 6 },
  { level: 6, image: 'photos_shop/279.webp', title: 'Кубик с позами', text: 'Игровой кубик с позами для разнообразия.', forWhom: 'обоим партнёрам', womenRating: 7, menRating: 7 },
  { level: 6, image: 'photos_shop/280.webp', title: 'Беруши', text: 'Беруши для сенсорной депривации во время игр.', forWhom: 'обоим партнёрам', womenRating: 5, menRating: 5 },
  { level: 6, image: 'photos_shop/281.webp', title: 'Женский презерватив', text: 'Альтернатива мужскому презервативу, надевается партнёршей.', forWhom: 'ей', womenRating: 4, menRating: 4 },
  { level: 6, image: 'photos_shop/282.webp', title: 'Виброяйцо на пульте', text: 'Виброяйцо с пультом дистанционного управления.', forWhom: 'ей', womenRating: 8, menRating: 6 },
  { level: 6, image: 'photos_shop/283.webp', title: 'Мини-вибратор языком', text: 'Компактный вибратор с насадкой в форме языка.', forWhom: 'ей', womenRating: 8, menRating: 5 },
  { level: 6, image: 'photos_shop/284.webp', title: 'Мини-вибратор', text: 'Компактный мини-вибратор для точечной стимуляции.', forWhom: 'ей', womenRating: 7, menRating: 5 },
  { level: 6, image: 'photos_shop/285.webp', title: 'Шприц для смазки ануса', text: 'Шприц-дозатор для нанесения смазки перед анальным сексом.', forWhom: 'обоим партнёрам', womenRating: 6, menRating: 6 },
  { level: 6, image: 'photos_shop/286.webp', title: 'Презерватив с шипами', text: 'Презерватив с рельефными шипами для дополнительной стимуляции.', forWhom: 'обоим партнёрам', womenRating: 7, menRating: 7 },
  { level: 6, image: 'photos_shop/287.webp', title: 'Средство для ухода за секс-игрушками', text: 'Очищающее средство для ухода за игрушками.', forWhom: 'обоим партнёрам', womenRating: 6, menRating: 6 },
  { level: 6, image: 'photos_shop/288.webp', title: 'Насадка на член с вибрацией', text: 'Насадка с вибромотором для усиления ощущений.', forWhom: 'обоим партнёрам', womenRating: 7, menRating: 7 },
  { level: 6, image: 'photos_shop/289.webp', title: 'Сексуальная ночнушка', text: 'Короткая сексуальная ночная сорочка.', forWhom: 'ей', womenRating: 7, menRating: 8 },
  { level: 6, image: 'photos_shop/290.webp', title: 'Ночнушка-сетка', text: 'Прозрачная ночнушка из сетки.', forWhom: 'ей', womenRating: 6, menRating: 8 },
  { level: 6, image: 'photos_shop/291.webp', title: 'Белая ночнушка с подвязками', text: 'Белая ночнушка в комплекте с подвязками.', forWhom: 'ей', womenRating: 7, menRating: 8 },
  { level: 6, image: 'photos_shop/292.webp', title: 'Наряд уборщицы', text: 'Ролевой костюм горничной/уборщицы.', forWhom: 'ей', womenRating: 6, menRating: 8 },
  { level: 6, image: 'photos_shop/293.webp', title: 'Красивый комплект белья', text: 'Красивый комплект нижнего белья.', forWhom: 'ей', womenRating: 7, menRating: 8 },
  { level: 6, image: 'photos_shop/294.webp', title: 'Сексуальный комплект белья', text: 'Откровенный комплект нижнего белья.', forWhom: 'ей', womenRating: 7, menRating: 8 },
  { level: 6, image: 'photos_shop/295.webp', title: 'Чулки в сетку с белыми подвязками', text: 'Сетчатые чулки на белых подвязках.', forWhom: 'ей', womenRating: 6, menRating: 8 },
  { level: 6, image: 'photos_shop/296.webp', title: 'Чулки в сетку', text: 'Классические чулки в сетку.', forWhom: 'ей', womenRating: 6, menRating: 8 },
  { level: 6, image: 'photos_shop/297.webp', title: 'Платье-сетка', text: 'Прозрачное сетчатое платье.', forWhom: 'ей', womenRating: 6, menRating: 8 },
  { level: 6, image: 'photos_shop/298.webp', title: 'Минимальный купальник белый', text: 'Минималистичный белый купальник.', forWhom: 'ей', womenRating: 6, menRating: 7 },
  { level: 6, image: 'photos_shop/299.webp', title: 'Стринги розовые', text: 'Розовые стринги.', forWhom: 'ей', womenRating: 6, menRating: 7 },
  { level: 6, image: 'photos_shop/300.webp', title: 'Повязка на глаза атласная', text: 'Атласная повязка на глаза для сенсорных игр.', forWhom: 'обоим партнёрам', womenRating: 7, menRating: 7 },
  { level: 6, image: 'photos_shop/301.webp', title: 'Чулки с бантиками', text: 'Чулки с декоративными бантиками.', forWhom: 'ей', womenRating: 6, menRating: 7 },
  { level: 6, image: 'photos_shop/302.webp', title: 'Мини-бикини красные', text: 'Красное мини-бикини.', forWhom: 'ей', womenRating: 6, menRating: 8 },
  { level: 6, image: 'photos_shop/303.webp', title: 'Подвязки белые', text: 'Белые подвязки для чулок.', forWhom: 'ей', womenRating: 6, menRating: 7 },
  { level: 6, image: 'photos_shop/304.webp', title: 'Минимальный купальник чёрный', text: 'Минималистичный чёрный купальник.', forWhom: 'ей', womenRating: 6, menRating: 8 },
  { level: 6, image: 'photos_shop/305.webp', title: 'Полупрозрачный комплект', text: 'Полупрозрачный комплект белья.', forWhom: 'ей', womenRating: 6, menRating: 8 },
  { level: 6, image: 'photos_shop/306.webp', title: 'Чулки в крупную сетку', text: 'Чулки в крупную сетку.', forWhom: 'ей', womenRating: 6, menRating: 8 },
  { level: 6, image: 'photos_shop/307.webp', title: 'Подвязки чёрные', text: 'Чёрные подвязки для чулок.', forWhom: 'ей', womenRating: 6, menRating: 7 },
  { level: 6, image: 'photos_shop/308.webp', title: 'Сумочка для игрушек', text: 'Компактная сумочка для хранения игрушек.', forWhom: 'обоим партнёрам', womenRating: 6, menRating: 6 },
];
