// cards_sexshop.js — данные для 5-го модуля игры «Предложи партнеру»:
// топ-200 товаров для секс-шопа (рейтинг по продажам в России). Формат
// такой же, как в cards_poses.js, плюс:
// - rank — номер в рейтинге продаж (1 = самый продаваемый), показывается
//   крупным значком над названием;
// - forWhom — для кого подходит товар (ей / ему / обоим партнёрам),
//   показывается отдельной строкой под описанием;
// - womenRating/menRating — оценки партнёров от 0 до 10, показываются
//   отдельной строкой значков ниже.
// level (здесь всегда 5 — отдельный модуль), image (путь к фото в
// photos_shop/, фото добавляются отдельно), title (название товара) и
// text (только описание товара, без прочих полей).
//
// Фото для этого модуля пока не загружены — до появления файлов в
// photos_shop/ карточки будут показывать запасную иконку вместо картинки.

const SEXSHOP_CARDS = [
  { level: 5, rank: 1, image: 'photos_shop/001.jpg', title: 'Лубрикант на водной основе', text: 'Базовая смазка для любых видов секса, самая ходовая позиция.', forWhom: 'обоим партнёрам', womenRating: 9, menRating: 9 },
  { level: 5, rank: 2, image: 'photos_shop/002.jpg', title: 'Эротические игры для пар (настольная)', text: 'Игры с заданиями и вопросами, популярный подарочный формат.', forWhom: 'обоим партнёрам', womenRating: 8, menRating: 8 },
  { level: 5, rank: 3, image: 'photos_shop/003.jpg', title: 'Вибратор-пуля', text: 'Компактная игрушка для клиторальной стимуляции.', forWhom: 'ей', womenRating: 9, menRating: 6 },
  { level: 5, rank: 4, image: 'photos_shop/004.jpg', title: 'Клиторальный вакуумный стимулятор', text: 'Стимуляция воздушными импульсами, один из лидеров женского спроса.', forWhom: 'ей', womenRating: 9, menRating: 6 },
  { level: 5, rank: 5, image: 'photos_shop/005.jpg', title: 'Мастурбатор (рукав/туннель)', text: 'Классический мужской мастурбатор, базовый вариант.', forWhom: 'ему', womenRating: 2, menRating: 9 },
  { level: 5, rank: 6, image: 'photos_shop/006.jpg', title: 'Вибратор для пар (кольцо на пенис)', text: 'Стимулирует клитор во время проникновения.', forWhom: 'обоим партнёрам', womenRating: 8, menRating: 8 },
  { level: 5, rank: 7, image: 'photos_shop/007.jpg', title: 'Силиконовый лубрикант', text: 'Более долговечная смазка, подходит для душа и ванны.', forWhom: 'обоим партнёрам', womenRating: 8, menRating: 8 },
  { level: 5, rank: 8, image: 'photos_shop/008.jpg', title: 'Вибратор-кролик (двойная стимуляция)', text: 'Одновременная стимуляция клитора и влагалища.', forWhom: 'ей', womenRating: 9, menRating: 6 },
  { level: 5, rank: 9, image: 'photos_shop/009.jpg', title: 'Анальная пробка (базовая)', text: 'Небольшая пробка для начального уровня.', forWhom: 'обоим партнёрам', womenRating: 6, menRating: 7 },
  { level: 5, rank: 10, image: 'photos_shop/010.jpg', title: 'Презервативы классические', text: 'Базовая защита, массовый спрос.', forWhom: 'обоим партнёрам', womenRating: 8, menRating: 8 },
  { level: 5, rank: 11, image: 'photos_shop/011.jpg', title: 'Эротическое бельё (комплект)', text: 'Бюстгальтер + трусики, популярный подарок.', forWhom: 'ей', womenRating: 7, menRating: 8 },
  { level: 5, rank: 12, image: 'photos_shop/012.jpg', title: 'Вибропалочка (wand)', text: 'Мощная внешняя стимуляция, классика для клитора.', forWhom: 'ей', womenRating: 9, menRating: 6 },
  { level: 5, rank: 13, image: 'photos_shop/013.jpg', title: 'Эротические костюмы (ролевые)', text: 'Медсестра, полицейская, горничная — популярные сюжеты.', forWhom: 'ей', womenRating: 7, menRating: 8 },
  { level: 5, rank: 14, image: 'photos_shop/014.jpg', title: 'Массажное масло', text: 'Для эротического массажа как часть прелюдии.', forWhom: 'обоим партнёрам', womenRating: 8, menRating: 7 },
  { level: 5, rank: 15, image: 'photos_shop/015.jpg', title: 'Автоматический мастурбатор', text: 'Устройство с вращением и сжатием.', forWhom: 'ему', womenRating: 3, menRating: 9 },
  { level: 5, rank: 16, image: 'photos_shop/016.jpg', title: 'Вибратор с изгибом (G‑точка)', text: 'Специальная форма для стимуляции G‑точки.', forWhom: 'ей', womenRating: 8, menRating: 5 },
  { level: 5, rank: 17, image: 'photos_shop/017.jpg', title: 'Эротические аксессуары (набор для бондажа)', text: 'Верёвки, повязки, мягкие фиксаторы.', forWhom: 'обоим партнёрам', womenRating: 6, menRating: 7 },
  { level: 5, rank: 18, image: 'photos_shop/018.jpg', title: 'Презервативы с вкусами/ароматами', text: 'Для орального секса, популярный вариант.', forWhom: 'обоим партнёрам', womenRating: 7, menRating: 7 },
  { level: 5, rank: 19, image: 'photos_shop/019.jpg', title: 'Вагинальные шарики', text: 'Тренировка интимных мышц и дополнительная стимуляция.', forWhom: 'ей', womenRating: 6, menRating: 4 },
  { level: 5, rank: 20, image: 'photos_shop/020.jpg', title: 'Простатный массажёр', text: 'Стимуляция простаты, растущий сегмент.', forWhom: 'ему', womenRating: 3, menRating: 8 },
  { level: 5, rank: 21, image: 'photos_shop/021.jpg', title: 'Анальная смазка (густая)', text: 'Специальный лубрикант для анального секса.', forWhom: 'обоим партнёрам', womenRating: 7, menRating: 7 },
  { level: 5, rank: 22, image: 'photos_shop/022.jpg', title: 'Вибратор-яйцо', text: 'Компактная форма, подходит для новичков.', forWhom: 'ей', womenRating: 7, menRating: 5 },
  { level: 5, rank: 23, image: 'photos_shop/023.jpg', title: 'Набор презервативов (микс)', text: 'Разные виды в одной упаковке.', forWhom: 'обоим партнёрам', womenRating: 7, menRating: 8 },
  { level: 5, rank: 24, image: 'photos_shop/024.jpg', title: 'Чулки эротические', text: 'Классика эротического белья.', forWhom: 'ей', womenRating: 7, menRating: 8 },
  { level: 5, rank: 25, image: 'photos_shop/025.jpg', title: 'Вибратор с пультом (для пар)', text: 'Управление партнёром, игра на расстоянии.', forWhom: 'обоим партнёрам', womenRating: 8, menRating: 7 },
  { level: 5, rank: 26, image: 'photos_shop/026.jpg', title: 'Анальный набор (пробки разного размера)', text: 'Постепенное увеличение диаметра.', forWhom: 'обоим партнёрам', womenRating: 7, menRating: 7 },
  { level: 5, rank: 27, image: 'photos_shop/027.jpg', title: 'Мастурбатор с вибрацией', text: 'Добавляет вибрацию к обычному рукаву.', forWhom: 'ему', womenRating: 3, menRating: 8 },
  { level: 5, rank: 28, image: 'photos_shop/028.jpg', title: 'Эротические кубики', text: 'Генерация случайных заданий для пар.', forWhom: 'обоим партнёрам', womenRating: 7, menRating: 6 },
  { level: 5, rank: 29, image: 'photos_shop/029.jpg', title: 'Вибратор-браслет', text: 'Носимая игрушка с пультом.', forWhom: 'ей', womenRating: 7, menRating: 4 },
  { level: 5, rank: 30, image: 'photos_shop/030.jpg', title: 'Свечи эротические (массажные)', text: 'Создают атмосферу и используются для массажа.', forWhom: 'обоим партнёрам', womenRating: 7, menRating: 6 },
  { level: 5, rank: 31, image: 'photos_shop/031.jpg', title: 'Вибратор-помада', text: 'Компактный формат, похожий на помаду.', forWhom: 'ей', womenRating: 7, menRating: 4 },
  { level: 5, rank: 32, image: 'photos_shop/032.jpg', title: 'Презервативы с пролонгатором', text: 'Содержат лёгкий анестетик для продления.', forWhom: 'обоим партнёрам', womenRating: 7, menRating: 8 },
  { level: 5, rank: 33, image: 'photos_shop/033.jpg', title: 'Эротическая повязка на глаза', text: 'Базовый элемент для сенсорных игр.', forWhom: 'обоим партнёрам', womenRating: 7, menRating: 7 },
  { level: 5, rank: 34, image: 'photos_shop/034.jpg', title: 'Мини-вибратор для клитора', text: 'Точечная стимуляция, удобно носить с собой.', forWhom: 'ей', womenRating: 8, menRating: 5 },
  { level: 5, rank: 35, image: 'photos_shop/035.jpg', title: 'Гель для интимной гигиены', text: 'Ежедневная гигиена, чувствительная зона.', forWhom: 'ей', womenRating: 7, menRating: 4 },
  { level: 5, rank: 36, image: 'photos_shop/036.jpg', title: 'Вибратор-двойник (для пар)', text: 'Одновременно стимулирует обоих партнёров.', forWhom: 'обоим партнёрам', womenRating: 8, menRating: 7 },
  { level: 5, rank: 37, image: 'photos_shop/037.jpg', title: 'Анальная груша/спринцовка', text: 'Для подготовки и гигиены перед анальным сексом.', forWhom: 'обоим партнёрам', womenRating: 6, menRating: 6 },
  { level: 5, rank: 38, image: 'photos_shop/038.jpg', title: 'Мастурбатор с подогревом', text: 'Тепло усиливает реалистичность ощущений.', forWhom: 'ему', womenRating: 3, menRating: 8 },
  { level: 5, rank: 39, image: 'photos_shop/039.jpg', title: 'Вибратор с аппликатором для пар', text: 'Одновременная стимуляция клитора и пениса.', forWhom: 'обоим партнёрам', womenRating: 8, menRating: 7 },
  { level: 5, rank: 40, image: 'photos_shop/040.jpg', title: 'Эротический комплект «горничная»', text: 'Платье, фартук и аксессуары.', forWhom: 'ей', womenRating: 7, menRating: 7 },
  { level: 5, rank: 41, image: 'photos_shop/041.jpg', title: 'Вибратор-кольцо на палец', text: 'Точечная стимуляция во время ласк.', forWhom: 'ей', womenRating: 7, menRating: 6 },
  { level: 5, rank: 42, image: 'photos_shop/042.jpg', title: 'Презервативы увеличенного размера', text: 'Для большего комфорта.', forWhom: 'ему', womenRating: 5, menRating: 8 },
  { level: 5, rank: 43, image: 'photos_shop/043.jpg', title: 'Вибратор с изгибом и вибрацией', text: 'Комбинация формы и мощности.', forWhom: 'ей', womenRating: 8, menRating: 5 },
  { level: 5, rank: 44, image: 'photos_shop/044.jpg', title: 'Эротический набор для массажа', text: 'Масло, перо, иногда кубики.', forWhom: 'обоим партнёрам', womenRating: 7, menRating: 7 },
  { level: 5, rank: 45, image: 'photos_shop/045.jpg', title: 'Анальная пробка с камнем/декором', text: 'Эстетика и стимуляция.', forWhom: 'обоим партнёрам', womenRating: 6, menRating: 6 },
  { level: 5, rank: 46, image: 'photos_shop/046.jpg', title: 'Вибратор-кролик премиум', text: 'Более мощные моторы и материалы.', forWhom: 'ей', womenRating: 8, menRating: 5 },
  { level: 5, rank: 47, image: 'photos_shop/047.jpg', title: 'Мастурбатор-туннель (компактный)', text: 'Упрощённая версия для новичков.', forWhom: 'ему', womenRating: 3, menRating: 8 },
  { level: 5, rank: 48, image: 'photos_shop/048.jpg', title: 'Эротическое боди', text: 'Цельный комплект, популярный в подарках.', forWhom: 'ей', womenRating: 7, menRating: 7 },
  { level: 5, rank: 49, image: 'photos_shop/049.jpg', title: 'Вибратор с Bluetooth (управление из приложения)', text: 'Smart-игрушка, управление со смартфона.', forWhom: 'ей', womenRating: 8, menRating: 6 },
  { level: 5, rank: 50, image: 'photos_shop/050.jpg', title: 'Презервативы тонкие (ultra thin)', text: 'Максимальная чувствительность.', forWhom: 'обоим партнёрам', womenRating: 8, menRating: 8 },
  { level: 5, rank: 51, image: 'photos_shop/051.jpg', title: 'Вибропалочка с насадками', text: 'Разные текстуры в одном устройстве.', forWhom: 'ей', womenRating: 8, menRating: 5 },
  { level: 5, rank: 52, image: 'photos_shop/052.jpg', title: 'Эротический корсет', text: 'Формирует силуэт, ролевой элемент.', forWhom: 'ей', womenRating: 6, menRating: 7 },
  { level: 5, rank: 53, image: 'photos_shop/053.jpg', title: 'Анальный вибратор-пуля', text: 'Маленькая модель для анальной зоны.', forWhom: 'обоим партнёрам', womenRating: 7, menRating: 7 },
  { level: 5, rank: 54, image: 'photos_shop/054.jpg', title: 'Мастурбатор с текстурой (рёбра/волны)', text: 'Внутренний рельеф для усиления стимуляции.', forWhom: 'ему', womenRating: 3, menRating: 8 },
  { level: 5, rank: 55, image: 'photos_shop/055.jpg', title: 'Вибратор для G‑точки с пультом', text: 'Управление партнёром, игра в постели.', forWhom: 'ей', womenRating: 8, menRating: 5 },
  { level: 5, rank: 56, image: 'photos_shop/056.jpg', title: 'Эротические перчатки', text: 'Часть образа и тактильного сценария.', forWhom: 'ей', womenRating: 6, menRating: 7 },
  { level: 5, rank: 57, image: 'photos_shop/057.jpg', title: 'Лубрикант с ароматом/вкусом', text: 'Для оральных практик и разнообразия.', forWhom: 'обоим партнёрам', womenRating: 7, menRating: 7 },
  { level: 5, rank: 58, image: 'photos_shop/058.jpg', title: 'Вибратор с программируемыми паттернами', text: 'Сложные сценарии вибрации.', forWhom: 'ей', womenRating: 7, menRating: 5 },
  { level: 5, rank: 59, image: 'photos_shop/059.jpg', title: 'Автоматический мастурбатор с вращением', text: 'Вращение в сочетании с движением.', forWhom: 'ему', womenRating: 3, menRating: 8 },
  { level: 5, rank: 60, image: 'photos_shop/060.jpg', title: 'Эротический халатик/пеньюар', text: 'Лёгкая домашняя эротика.', forWhom: 'ей', womenRating: 7, menRating: 7 },
  { level: 5, rank: 61, image: 'photos_shop/061.jpg', title: 'Вибратор-браслет с пультом', text: 'Носимая игрушка, управление партнёром.', forWhom: 'ей', womenRating: 7, menRating: 6 },
  { level: 5, rank: 62, image: 'photos_shop/062.jpg', title: 'Простатный массажёр с вибрацией', text: 'Стимуляция простаты + вибрация.', forWhom: 'ему', womenRating: 4, menRating: 8 },
  { level: 5, rank: 63, image: 'photos_shop/063.jpg', title: 'Эротические чулки с узором', text: 'Эротический акцент в образе.', forWhom: 'ей', womenRating: 7, menRating: 7 },
  { level: 5, rank: 64, image: 'photos_shop/064.jpg', title: 'Вибратор с подогревом', text: 'Тепло усиливает ощущения.', forWhom: 'ей', womenRating: 7, menRating: 5 },
  { level: 5, rank: 65, image: 'photos_shop/065.jpg', title: 'Мастурбатор с сжатием (автомат)', text: 'Имитация сжатия, более продвинутая модель.', forWhom: 'ему', womenRating: 3, menRating: 8 },
  { level: 5, rank: 66, image: 'photos_shop/066.jpg', title: 'Эротический набор «стюардесса»', text: 'Ролевой комплект.', forWhom: 'ей', womenRating: 6, menRating: 7 },
  { level: 5, rank: 67, image: 'photos_shop/067.jpg', title: 'Вибратор-двойник премиум', text: 'Более мощные моторы и материалы.', forWhom: 'обоим партнёрам', womenRating: 8, menRating: 7 },
  { level: 5, rank: 68, image: 'photos_shop/068.jpg', title: 'Анальная пробка металлическая', text: 'Тяжёлая, для продвинутых.', forWhom: 'обоим партнёрам', womenRating: 6, menRating: 7 },
  { level: 5, rank: 69, image: 'photos_shop/069.jpg', title: 'Вибратор с дальним управлением (long distance)', text: 'Игра на расстоянии через приложение.', forWhom: 'ей', womenRating: 8, menRating: 6 },
  { level: 5, rank: 70, image: 'photos_shop/070.jpg', title: 'Презервативы с рёбрами/точками', text: 'Дополнительная стимуляция для партнёрши.', forWhom: 'обоим партнёрам', womenRating: 7, menRating: 7 },
  { level: 5, rank: 71, image: 'photos_shop/071.jpg', title: 'Вибратор-помада с пультом', text: 'Компактность + управление партнёром.', forWhom: 'ей', womenRating: 7, menRating: 6 },
  { level: 5, rank: 72, image: 'photos_shop/072.jpg', title: 'Эротический комплект «полицейская»', text: 'Популярный ролевой сюжет.', forWhom: 'ей', womenRating: 6, menRating: 7 },
  { level: 5, rank: 73, image: 'photos_shop/073.jpg', title: 'Анальный стимулятор с изгибом (для простаты)', text: 'Часто выбирают для простатной стимуляции.', forWhom: 'ему', womenRating: 4, menRating: 8 },
  { level: 5, rank: 74, image: 'photos_shop/074.jpg', title: 'Вибратор-яйцо с Bluetooth', text: 'Удалённое управление на расстоянии.', forWhom: 'ей', womenRating: 8, menRating: 6 },
  { level: 5, rank: 75, image: 'photos_shop/075.jpg', title: 'Мастурбатор с вибрацией и подогревом', text: 'Комбинация тепла и вибрации.', forWhom: 'ему', womenRating: 3, menRating: 8 },
  { level: 5, rank: 76, image: 'photos_shop/076.jpg', title: 'Эротический пояс для подвязок', text: 'Классический элемент образа.', forWhom: 'ей', womenRating: 6, menRating: 7 },
  { level: 5, rank: 77, image: 'photos_shop/077.jpg', title: 'Вибратор с голосовым управлением', text: 'Нишевая smart-функция.', forWhom: 'ей', womenRating: 6, menRating: 5 },
  { level: 5, rank: 78, image: 'photos_shop/078.jpg', title: 'Анальная смазка с анестетиком', text: 'Частично снижает чувствительность.', forWhom: 'обоим партнёрам', womenRating: 6, menRating: 7 },
  { level: 5, rank: 79, image: 'photos_shop/079.jpg', title: 'Вибратор-кролик с подогревом', text: 'Двойная стимуляция + тепло.', forWhom: 'ей', womenRating: 8, menRating: 5 },
  { level: 5, rank: 80, image: 'photos_shop/080.jpg', title: 'Эротический комплект «медсестра»', text: 'Классика ролевых сценариев.', forWhom: 'ей', womenRating: 7, menRating: 7 },
  { level: 5, rank: 81, image: 'photos_shop/081.jpg', title: 'Вибратор с подсветкой', text: 'Добавляет визуальный эффект.', forWhom: 'ей', womenRating: 6, menRating: 5 },
  { level: 5, rank: 82, image: 'photos_shop/082.jpg', title: 'Автоматический мастурбатор премиум', text: 'Более сложные программы и материалы.', forWhom: 'ему', womenRating: 3, menRating: 8 },
  { level: 5, rank: 83, image: 'photos_shop/083.jpg', title: 'Эротические гольфы/чулки до бедра', text: 'Элемент костюма.', forWhom: 'ей', womenRating: 6, menRating: 7 },
  { level: 5, rank: 84, image: 'photos_shop/084.jpg', title: 'Вибратор с аппликатором для пар (премиум)', text: 'Одновременная стимуляция, улучшенная версия.', forWhom: 'обоим партнёрам', womenRating: 8, menRating: 7 },
  { level: 5, rank: 85, image: 'photos_shop/085.jpg', title: 'Анальный набор (пробки + смазка + груша)', text: 'Комплект для комфортного старта.', forWhom: 'обоим партнёрам', womenRating: 7, menRating: 7 },
  { level: 5, rank: 86, image: 'photos_shop/086.jpg', title: 'Вибратор-браслет с приложением', text: 'Smart-сценарии и тонкая настройка.', forWhom: 'ей', womenRating: 7, menRating: 6 },
  { level: 5, rank: 87, image: 'photos_shop/087.jpg', title: 'Эротический комплект «студентка»', text: 'Один из массовых ролевых образов.', forWhom: 'ей', womenRating: 6, menRating: 7 },
  { level: 5, rank: 88, image: 'photos_shop/088.jpg', title: 'Вибратор с изгибом и вибрацией (премиум)', text: 'Более мощные моторы и материалы.', forWhom: 'ей', womenRating: 8, menRating: 5 },
  { level: 5, rank: 89, image: 'photos_shop/089.jpg', title: 'Мастурбатор с текстурой и вибрацией', text: 'Сочетание рельефа и вибрации.', forWhom: 'ему', womenRating: 3, menRating: 8 },
  { level: 5, rank: 90, image: 'photos_shop/090.jpg', title: 'Эротический комплект «кошка/лисичка»', text: 'Ушки, хвост и костюм в одном наборе.', forWhom: 'ей', womenRating: 7, menRating: 7 },
  { level: 5, rank: 91, image: 'photos_shop/091.jpg', title: 'Вибратор-двойник с подогревом', text: 'Тепло + двойная стимуляция.', forWhom: 'обоим партнёрам', womenRating: 8, menRating: 7 },
  { level: 5, rank: 92, image: 'photos_shop/092.jpg', title: 'Анальная пробка с вибрацией', text: 'Добавляет вибрацию к анальной стимуляции.', forWhom: 'обоим партнёрам', womenRating: 7, menRating: 7 },
  { level: 5, rank: 93, image: 'photos_shop/093.jpg', title: 'Вибратор-помада с подогревом', text: 'Компактность + тепло.', forWhom: 'ей', womenRating: 7, menRating: 5 },
  { level: 5, rank: 94, image: 'photos_shop/094.jpg', title: 'Эротический набор для бондажа (премиум)', text: 'Более дорогие материалы и фурнитура.', forWhom: 'обоим партнёрам', womenRating: 6, menRating: 7 },
  { level: 5, rank: 95, image: 'photos_shop/095.jpg', title: 'Вибратор с программируемыми паттернами (премиум)', text: 'Сложные сценарии и настройки.', forWhom: 'ей', womenRating: 7, menRating: 6 },
  { level: 5, rank: 96, image: 'photos_shop/096.jpg', title: 'Мастурбатор с подогревом и вибрацией (премиум)', text: 'Тепло + вибрация + продвинутые режимы.', forWhom: 'ему', womenRating: 3, menRating: 8 },
  { level: 5, rank: 97, image: 'photos_shop/097.jpg', title: 'Эротический комплект «горничная» (премиум)', text: 'Улучшенные материалы и детали.', forWhom: 'ей', womenRating: 7, menRating: 7 },
  { level: 5, rank: 98, image: 'photos_shop/098.jpg', title: 'Вибратор-яйцо с подогревом', text: 'Тепло + компактность.', forWhom: 'ей', womenRating: 7, menRating: 6 },
  { level: 5, rank: 99, image: 'photos_shop/099.jpg', title: 'Анальный стимулятор с вибрацией и подогревом', text: 'Вибрация + тепло для простатной стимуляции.', forWhom: 'ему', womenRating: 4, menRating: 8 },
  { level: 5, rank: 100, image: 'photos_shop/100.jpg', title: 'Эротический комплект «стюардесса» (премиум)', text: 'Ролевой комплект улучшенного качества.', forWhom: 'ей', womenRating: 6, menRating: 7 },
  { level: 5, rank: 101, image: 'photos_shop/101.jpg', title: 'Секс-кукла (TPE, средняя)', text: 'Высокий чек, но взрывной рост категории.', forWhom: 'ему', womenRating: 1, menRating: 6 },
  { level: 5, rank: 102, image: 'photos_shop/102.jpg', title: 'Секс-машина (продвинутая)', text: 'Одна из самых дорогих позиций, штучные продажи.', forWhom: 'ей', womenRating: 6, menRating: 4 },
  { level: 5, rank: 103, image: 'photos_shop/103.jpg', title: 'Набор насадок на вибратор', text: 'Расширяет функционал базового устройства.', forWhom: 'ей', womenRating: 6, menRating: 3 },
  { level: 5, rank: 104, image: 'photos_shop/104.jpg', title: 'Эротический веер', text: 'Лёгкий BDSM- или ролевой аксессуар.', forWhom: 'обоим партнёрам', womenRating: 6, menRating: 5 },
  { level: 5, rank: 105, image: 'photos_shop/105.jpg', title: 'Зажимы для сосков (металл)', text: 'Более выраженный эффект давления.', forWhom: 'обоим партнёрам', womenRating: 4, menRating: 5 },
  { level: 5, rank: 106, image: 'photos_shop/106.jpg', title: 'Набор для ролевых (костюм + аксессуары)', text: 'Популярный подарочный формат.', forWhom: 'ей', womenRating: 6, menRating: 6 },
  { level: 5, rank: 107, image: 'photos_shop/107.jpg', title: 'Эротическая маска', text: 'Дополняет образ в ролевых сценариях.', forWhom: 'обоим партнёрам', womenRating: 6, menRating: 5 },
  { level: 5, rank: 108, image: 'photos_shop/108.jpg', title: 'Чокер эротический', text: 'Аксессуар для образа и BDSM-эстетики.', forWhom: 'ей', womenRating: 5, menRating: 5 },
  { level: 5, rank: 109, image: 'photos_shop/109.jpg', title: 'Каблуки или туфли для ролевых', text: 'Элемент костюма, усиливает образ.', forWhom: 'ей', womenRating: 4, menRating: 5 },
  { level: 5, rank: 110, image: 'photos_shop/110.jpg', title: 'Эротические чулки (сетка)', text: 'Классика эротического белья.', forWhom: 'ей', womenRating: 5, menRating: 6 },
  { level: 5, rank: 111, image: 'photos_shop/111.jpg', title: 'Подтяжки для чулок', text: 'Дополнение к комплекту белья.', forWhom: 'ей', womenRating: 4, menRating: 5 },
  { level: 5, rank: 112, image: 'photos_shop/112.jpg', title: 'Боди эротическое', text: 'Цельный комплект, популярный в подарках.', forWhom: 'ей', womenRating: 5, menRating: 6 },
  { level: 5, rank: 113, image: 'photos_shop/113.jpg', title: 'Корсет эротический', text: 'Формирует силуэт и поддерживает ролевой образ.', forWhom: 'ей', womenRating: 5, menRating: 6 },
  { level: 5, rank: 114, image: 'photos_shop/114.jpg', title: 'Халатик или пеньюар прозрачный', text: 'Лёгкая домашняя эротика.', forWhom: 'ей', womenRating: 5, menRating: 6 },
  { level: 5, rank: 115, image: 'photos_shop/115.jpg', title: 'Трусики с вырезами', text: 'Открытый дизайн для доступа.', forWhom: 'ей', womenRating: 5, menRating: 6 },
  { level: 5, rank: 116, image: 'photos_shop/116.jpg', title: 'Бюстгальтер push-up эротический', text: 'Усиливает декольте, часть комплекта.', forWhom: 'ей', womenRating: 5, menRating: 6 },
  { level: 5, rank: 117, image: 'photos_shop/117.jpg', title: 'Пояс для подвязок', text: 'Классический элемент образа.', forWhom: 'ей', womenRating: 5, menRating: 5 },
  { level: 5, rank: 118, image: 'photos_shop/118.jpg', title: 'Массажёр для шеи и плеч', text: 'Подходит для расслабляющей прелюдии.', forWhom: 'обоим партнёрам', womenRating: 6, menRating: 5 },
  { level: 5, rank: 119, image: 'photos_shop/119.jpg', title: 'Игрушка-антистресс 18+', text: 'Шуточный или подарочный формат.', forWhom: 'обоим партнёрам', womenRating: 4, menRating: 4 },
  { level: 5, rank: 120, image: 'photos_shop/120.jpg', title: 'Набор эротических кубиков', text: 'Генератор случайных заданий.', forWhom: 'обоим партнёрам', womenRating: 6, menRating: 5 },
  { level: 5, rank: 121, image: 'photos_shop/121.jpg', title: 'Карты желаний (интимные)', text: 'Мягкая игра про желания и фантазии.', forWhom: 'обоим партнёрам', womenRating: 6, menRating: 5 },
  { level: 5, rank: 122, image: 'photos_shop/122.jpg', title: 'Игра «Правда или действие» 18+', text: 'Адаптация популярной игры.', forWhom: 'обоим партнёрам', womenRating: 6, menRating: 6 },
  { level: 5, rank: 123, image: 'photos_shop/123.jpg', title: 'Рулетка эротическая', text: 'Случайный выбор действия или зоны.', forWhom: 'обоим партнёрам', womenRating: 5, menRating: 5 },
  { level: 5, rank: 124, image: 'photos_shop/124.jpg', title: 'Дартс эротический', text: 'Игра с призами и заданиями.', forWhom: 'обоим партнёрам', womenRating: 5, menRating: 5 },
  { level: 5, rank: 125, image: 'photos_shop/125.jpg', title: 'Настольная игра для пар (продвинутая)', text: 'Более откровенные механики и сценарии.', forWhom: 'обоим партнёрам', womenRating: 7, menRating: 6 },
  { level: 5, rank: 126, image: 'photos_shop/126.jpg', title: 'Игра-квиз про отношения 18+', text: 'Проверка совместимости и фантазий.', forWhom: 'обоим партнёрам', womenRating: 6, menRating: 5 },
  { level: 5, rank: 127, image: 'photos_shop/127.jpg', title: 'Лубрикант с разогревающим эффектом', text: 'Нишевый сегмент интим-косметики.', forWhom: 'обоим партнёрам', womenRating: 6, menRating: 6 },
  { level: 5, rank: 128, image: 'photos_shop/128.jpg', title: 'Интимный дезодорант', text: 'Гигиена и свежесть перед близостью.', forWhom: 'обоим партнёрам', womenRating: 5, menRating: 5 },
  { level: 5, rank: 129, image: 'photos_shop/129.jpg', title: 'Спрей для свежести дыхания', text: 'Используют перед оральными практиками.', forWhom: 'обоим партнёрам', womenRating: 5, menRating: 5 },
  { level: 5, rank: 130, image: 'photos_shop/130.jpg', title: 'Салфетки с ароматом для интима', text: 'Быстрая гигиена на ходу.', forWhom: 'обоим партнёрам', womenRating: 6, menRating: 6 },
  { level: 5, rank: 131, image: 'photos_shop/131.jpg', title: 'Гель для интимной гигиены (мужской)', text: 'Часть мужского sexual wellness.', forWhom: 'ему', womenRating: 3, menRating: 6 },
  { level: 5, rank: 132, image: 'photos_shop/132.jpg', title: 'Гель для интимной гигиены (женский)', text: 'Ежедневная гигиена для чувствительной зоны.', forWhom: 'ей', womenRating: 6, menRating: 3 },
  { level: 5, rank: 133, image: 'photos_shop/133.jpg', title: 'Пенка для интимной гигиены', text: 'Мягкая альтернатива гелю.', forWhom: 'ей', womenRating: 6, menRating: 3 },
  { level: 5, rank: 134, image: 'photos_shop/134.jpg', title: 'Презервативы с пролонгатором', text: 'Содержат лёгкий анестетик.', forWhom: 'обоим партнёрам', womenRating: 6, menRating: 7 },
  { level: 5, rank: 135, image: 'photos_shop/135.jpg', title: 'Презервативы увеличенного размера', text: 'Для большего комфорта.', forWhom: 'ему', womenRating: 4, menRating: 7 },
  { level: 5, rank: 136, image: 'photos_shop/136.jpg', title: 'Презервативы тонкие со смазкой', text: 'Баланс чувствительности и скольжения.', forWhom: 'обоим партнёрам', womenRating: 7, menRating: 7 },
  { level: 5, rank: 137, image: 'photos_shop/137.jpg', title: 'Женский презерватив', text: 'Альтернатива мужскому, нишевый спрос.', forWhom: 'ей', womenRating: 4, menRating: 4 },
  { level: 5, rank: 138, image: 'photos_shop/138.jpg', title: 'Диафрагма или колпачок', text: 'Многоразовая контрацепция, редкий спрос.', forWhom: 'ей', womenRating: 3, menRating: 2 },
  { level: 5, rank: 139, image: 'photos_shop/139.jpg', title: 'Тест на овуляцию', text: 'Смежная категория, иногда в одном чеке.', forWhom: 'ей', womenRating: 3, menRating: 1 },
  { level: 5, rank: 140, image: 'photos_shop/140.jpg', title: 'Тест на беременность', text: 'Часто размещается рядом с интим-товарами.', forWhom: 'ей', womenRating: 3, menRating: 1 },
  { level: 5, rank: 141, image: 'photos_shop/141.jpg', title: 'Секс-качели', text: 'Для продвинутых позиций, высокий чек.', forWhom: 'обоим партнёрам', womenRating: 5, menRating: 5 },
  { level: 5, rank: 142, image: 'photos_shop/142.jpg', title: 'Секс-кресло или надувная подушка', text: 'Облегчает сложные позы.', forWhom: 'обоим партнёрам', womenRating: 6, menRating: 6 },
  { level: 5, rank: 143, image: 'photos_shop/143.jpg', title: 'Набор для бондажа', text: 'Комплект для фиксаций.', forWhom: 'обоим партнёрам', womenRating: 5, menRating: 6 },
  { level: 5, rank: 144, image: 'photos_shop/144.jpg', title: 'BDSM-набор премиум', text: 'Более дорогие материалы и фурнитура.', forWhom: 'обоим партнёрам', womenRating: 5, menRating: 6 },
  { level: 5, rank: 145, image: 'photos_shop/145.jpg', title: 'Зажимы для сосков с цепочкой', text: 'Визуальный и физический эффект.', forWhom: 'обоим партнёрам', womenRating: 4, menRating: 5 },
  { level: 5, rank: 146, image: 'photos_shop/146.jpg', title: 'Стеклянный анальный стимулятор', text: 'Непористый, подходит для температурной игры.', forWhom: 'обоим партнёрам', womenRating: 5, menRating: 6 },
  { level: 5, rank: 147, image: 'photos_shop/147.jpg', title: 'Металлическая анальная пробка', text: 'Тяжёлая модель для продвинутых.', forWhom: 'обоим партнёрам', womenRating: 5, menRating: 6 },
  { level: 5, rank: 148, image: 'photos_shop/148.jpg', title: 'Виброяйцо с Bluetooth', text: 'Удалённое управление на расстоянии.', forWhom: 'ей', womenRating: 7, menRating: 5 },
  { level: 5, rank: 149, image: 'photos_shop/149.jpg', title: 'Вибратор-браслет', text: 'Носимый формат и дискретность.', forWhom: 'ей', womenRating: 6, menRating: 3 },
  { level: 5, rank: 150, image: 'photos_shop/150.jpg', title: 'Вибратор-ожерелье', text: 'Аксессуар и игрушка в одном.', forWhom: 'ей', womenRating: 6, menRating: 3 },
  { level: 5, rank: 151, image: 'photos_shop/151.jpg', title: 'Виброкольцо на палец', text: 'Точечная стимуляция.', forWhom: 'ей', womenRating: 6, menRating: 4 },
  { level: 5, rank: 152, image: 'photos_shop/152.jpg', title: 'Мини-массажёр для точек', text: 'Для клитора и других чувствительных зон.', forWhom: 'ей', womenRating: 7, menRating: 3 },
  { level: 5, rank: 153, image: 'photos_shop/153.jpg', title: 'Вибратор с аппликатором для пар', text: 'Одновременная стимуляция.', forWhom: 'обоим партнёрам', womenRating: 7, menRating: 6 },
  { level: 5, rank: 154, image: 'photos_shop/154.jpg', title: 'Двусторонний вибратор с гибкой шейкой', text: 'Можно регулировать угол.', forWhom: 'обоим партнёрам', womenRating: 7, menRating: 4 },
  { level: 5, rank: 155, image: 'photos_shop/155.jpg', title: 'Вибратор со сменными головками', text: 'Разные текстуры в одном устройстве.', forWhom: 'ей', womenRating: 7, menRating: 3 },
  { level: 5, rank: 156, image: 'photos_shop/156.jpg', title: 'Вибропалочка с подогревом', text: 'Мощная стимуляция с теплом.', forWhom: 'ей', womenRating: 7, menRating: 3 },
  { level: 5, rank: 157, image: 'photos_shop/157.jpg', title: 'Вибратор с дальним пультом', text: 'Подходит для игры на расстоянии.', forWhom: 'ей', womenRating: 7, menRating: 5 },
  { level: 5, rank: 158, image: 'photos_shop/158.jpg', title: 'Вибратор с программируемыми паттернами', text: 'Сложные сценарии вибрации.', forWhom: 'ей', womenRating: 7, menRating: 3 },
  { level: 5, rank: 159, image: 'photos_shop/159.jpg', title: 'Вибратор с голосовым управлением', text: 'Нишевая smart-функция.', forWhom: 'ей', womenRating: 6, menRating: 4 },
  { level: 5, rank: 160, image: 'photos_shop/160.jpg', title: 'Вибратор с подсветкой', text: 'Добавляет визуальный эффект.', forWhom: 'ей', womenRating: 6, menRating: 3 },
  { level: 5, rank: 161, image: 'photos_shop/161.jpg', title: 'Мастурбатор с текстурой «рёбра»', text: 'Классическая внутренняя структура.', forWhom: 'ему', womenRating: 2, menRating: 9 },
  { level: 5, rank: 162, image: 'photos_shop/162.jpg', title: 'Мастурбатор с текстурой «волны»', text: 'Другой тип внутреннего рельефа.', forWhom: 'ему', womenRating: 2, menRating: 9 },
  { level: 5, rank: 163, image: 'photos_shop/163.jpg', title: 'Мастурбатор с вибрацией', text: 'Добавляет вибрацию к рукаву.', forWhom: 'ему', womenRating: 2, menRating: 9 },
  { level: 5, rank: 164, image: 'photos_shop/164.jpg', title: 'Мастурбатор с подогревом', text: 'Тепло усиливает реализм.', forWhom: 'ему', womenRating: 2, menRating: 8 },
  { level: 5, rank: 165, image: 'photos_shop/165.jpg', title: 'Мастурбатор-туннель', text: 'Компактнее и проще в уходе.', forWhom: 'ему', womenRating: 2, menRating: 8 },
  { level: 5, rank: 166, image: 'photos_shop/166.jpg', title: 'Автоматический мастурбатор с вращением', text: 'Вращение сочетается с движением.', forWhom: 'ему', womenRating: 2, menRating: 9 },
  { level: 5, rank: 167, image: 'photos_shop/167.jpg', title: 'Автоматический мастурбатор с сжатием', text: 'Имитирует сжатие.', forWhom: 'ему', womenRating: 2, menRating: 9 },
  { level: 5, rank: 168, image: 'photos_shop/168.jpg', title: 'Простатный массажер с пультом', text: 'Управление без рук.', forWhom: 'ему', womenRating: 3, menRating: 8 },
  { level: 5, rank: 169, image: 'photos_shop/169.jpg', title: 'Простатный массажер с приложением', text: 'Smart-сценарии и тонкая настройка.', forWhom: 'ему', womenRating: 3, menRating: 8 },
  { level: 5, rank: 170, image: 'photos_shop/170.jpg', title: 'Анальная пробка с камнем', text: 'Эстетика и стимуляция.', forWhom: 'обоим партнёрам', womenRating: 4, menRating: 5 },
  { level: 5, rank: 171, image: 'photos_shop/171.jpg', title: 'Набор анальных пробок (3–5 шт.)', text: 'Постепенная прогрессия размеров.', forWhom: 'обоим партнёрам', womenRating: 6, menRating: 7 },
  { level: 5, rank: 172, image: 'photos_shop/172.jpg', title: 'Анальный вибратор-пуля', text: 'Маленькая модель для анальной зоны.', forWhom: 'обоим партнёрам', womenRating: 5, menRating: 6 },
  { level: 5, rank: 173, image: 'photos_shop/173.jpg', title: 'Анальный стимулятор с изгибом', text: 'Часто выбирают для простатной стимуляции.', forWhom: 'ему', womenRating: 3, menRating: 7 },
  { level: 5, rank: 174, image: 'photos_shop/174.jpg', title: 'Анальная груша или спринцовка', text: 'Для подготовки и гигиены.', forWhom: 'обоим партнёрам', womenRating: 4, menRating: 5 },
  { level: 5, rank: 175, image: 'photos_shop/175.jpg', title: 'Набор для анальной гигиены', text: 'Обычно включает спрей, грушу и салфетки.', forWhom: 'обоим партнёрам', womenRating: 5, menRating: 6 },
  { level: 5, rank: 176, image: 'photos_shop/176.jpg', title: 'Лубрикант для анального секса', text: 'Более густая и вязкая формула.', forWhom: 'обоим партнёрам', womenRating: 6, menRating: 7 },
  { level: 5, rank: 177, image: 'photos_shop/177.jpg', title: 'Лубрикант с анестетиком', text: 'Частично снижает чувствительность.', forWhom: 'обоим партнёрам', womenRating: 5, menRating: 6 },
  { level: 5, rank: 178, image: 'photos_shop/178.jpg', title: 'Лубрикант с феромонами', text: 'Скорее ароматический и маркетинговый эффект.', forWhom: 'обоим партнёрам', womenRating: 4, menRating: 5 },
  { level: 5, rank: 179, image: 'photos_shop/179.jpg', title: 'Гель-смазка длительного действия', text: 'Меньше повторных нанесений.', forWhom: 'обоим партнёрам', womenRating: 6, menRating: 6 },
  { level: 5, rank: 180, image: 'photos_shop/180.jpg', title: 'Спрей-пролонгатор для мужчин', text: 'Временно снижает чувствительность.', forWhom: 'ему', womenRating: 3, menRating: 7 },
  { level: 5, rank: 181, image: 'photos_shop/181.jpg', title: 'Гель-увеличитель (временный эффект)', text: 'Краткосрочный эффект.', forWhom: 'ему', womenRating: 2, menRating: 5 },
  { level: 5, rank: 182, image: 'photos_shop/182.jpg', title: 'Возбуждающий крем для клитора', text: 'Локально усиливает чувствительность.', forWhom: 'ей', womenRating: 6, menRating: 4 },
  { level: 5, rank: 183, image: 'photos_shop/183.jpg', title: 'Возбуждающий гель для груди', text: 'Нишевая внешняя стимуляция.', forWhom: 'ей', womenRating: 5, menRating: 5 },
  { level: 5, rank: 184, image: 'photos_shop/184.jpg', title: 'Возбуждающий спрей для неё', text: 'Аромат и лёгкий разогревающий эффект.', forWhom: 'ей', womenRating: 4, menRating: 4 },
  { level: 5, rank: 185, image: 'photos_shop/185.jpg', title: 'Свеча эротическая (арома)', text: 'Создаёт атмосферу и подходит для массажа.', forWhom: 'обоим партнёрам', womenRating: 6, menRating: 5 },
  { level: 5, rank: 186, image: 'photos_shop/186.jpg', title: 'Набор для эротического массажа', text: 'Масло, перо и другие элементы прелюдии.', forWhom: 'обоим партнёрам', womenRating: 6, menRating: 6 },
  { level: 5, rank: 187, image: 'photos_shop/187.jpg', title: 'Перчатки эротические', text: 'Часть образа и тактильного сценария.', forWhom: 'ей', womenRating: 5, menRating: 6 },
  { level: 5, rank: 188, image: 'photos_shop/188.jpg', title: 'Гольфы или чулки до бедра', text: 'Элемент костюма.', forWhom: 'ей', womenRating: 5, menRating: 6 },
  { level: 5, rank: 189, image: 'photos_shop/189.jpg', title: 'Колготки с узором или сеткой', text: 'Эротический акцент в образе.', forWhom: 'ей', womenRating: 5, menRating: 6 },
  { level: 5, rank: 190, image: 'photos_shop/190.jpg', title: 'Бандажное эротическое бельё', text: 'BDSM-эстетика в белье.', forWhom: 'ей', womenRating: 5, menRating: 6 },
  { level: 5, rank: 191, image: 'photos_shop/191.jpg', title: 'Комплект «бюст + трусики + подвязки»', text: 'Полный собранный набор.', forWhom: 'ей', womenRating: 6, menRating: 6 },
  { level: 5, rank: 192, image: 'photos_shop/192.jpg', title: 'Пижама эротическая', text: 'Домашний формат с прозрачными элементами.', forWhom: 'ей', womenRating: 5, menRating: 6 },
  { level: 5, rank: 193, image: 'photos_shop/193.jpg', title: 'Халат-кимоно эротический', text: 'Ролевой и домашний образ.', forWhom: 'ей', womenRating: 5, menRating: 6 },
  { level: 5, rank: 194, image: 'photos_shop/194.jpg', title: 'Фартук эротический', text: 'Шуточный или ролевой формат.', forWhom: 'ей', womenRating: 4, menRating: 5 },
  { level: 5, rank: 195, image: 'photos_shop/195.jpg', title: 'Форма медсестры или учительницы', text: 'Классика ролевых сценариев.', forWhom: 'ей', womenRating: 5, menRating: 6 },
  { level: 5, rank: 196, image: 'photos_shop/196.jpg', title: 'Форма полицейской или охраны', text: 'Популярный ролевой сюжет.', forWhom: 'ей', womenRating: 4, menRating: 5 },
  { level: 5, rank: 197, image: 'photos_shop/197.jpg', title: 'Набор «горничная»', text: 'Платье, фартук и аксессуары.', forWhom: 'ей', womenRating: 5, menRating: 6 },
  { level: 5, rank: 198, image: 'photos_shop/198.jpg', title: 'Набор «стюардесса»', text: 'Ролевой комплект.', forWhom: 'ей', womenRating: 4, menRating: 5 },
  { level: 5, rank: 199, image: 'photos_shop/199.jpg', title: 'Набор «студентка»', text: 'Один из массовых ролевых образов.', forWhom: 'ей', womenRating: 4, menRating: 5 },
  { level: 5, rank: 200, image: 'photos_shop/200.jpg', title: 'Набор «кошка или лисичка»', text: 'Ушки, хвост и костюм в одном наборе.', forWhom: 'ей', womenRating: 5, menRating: 6 },
];
