// cards/capitals.js — данные для игры «Столицы» (games/capitals.js).
// CAPITALS_LEVELS — 3 уровня сложности (id, name, desc, icon).
// CAPITALS_CARDS — { level, country, flag: путь к SVG-флагу, a: [столица, ...3 неверных] },
// все 43 флага из flags-svg/ распределены по уровням: 15 (лёгкий) / 14 (средний) / 14 (трудный).
// Структура карточки как у Флагов: a[0] — правильный ответ (столица),
// a[1..3] — дистрактеры (города той же страны или соседних стран).

const CAPITALS_LEVELS = [
  { id: 1, icon: '🟢', name: 'Лёгкий', desc: '15 стран с известными столицами' },
  { id: 2, icon: '🟡', name: 'Средний', desc: 'Ещё 14 стран — узнайте столицу' },
  { id: 3, icon: '🔴', name: 'Трудный', desc: 'Последние 14 стран — сложные столицы' },
];

const CAPITALS_CARDS = [
  // ---------- Уровень 1 ----------
  { level: 1, country: 'Россия', flag: 'flags-svg/flag-ru.svg', a: ['Москва', 'Санкт-Петербург', 'Казань', 'Екатеринбург'] },
  { level: 1, country: 'Франция', flag: 'flags-svg/flag-fr.svg', a: ['Париж', 'Марсель', 'Лион', 'Тулуза'] },
  { level: 1, country: 'Германия', flag: 'flags-svg/flag-de.svg', a: ['Берлин', 'Мюнхен', 'Гамбург', 'Кёльн'] },
  { level: 1, country: 'Италия', flag: 'flags-svg/flag-it.svg', a: ['Рим', 'Милан', 'Неаполь', 'Турин'] },
  { level: 1, country: 'Испания', flag: 'flags-svg/flag-es.svg', a: ['Мадрид', 'Барселона', 'Валенсия', 'Севилья'] },
  { level: 1, country: 'США', flag: 'flags-svg/flag-us.svg', a: ['Вашингтон', 'Нью-Йорк', 'Лос-Анджелес', 'Чикаго'] },
  { level: 1, country: 'Япония', flag: 'flags-svg/flag-jp.svg', a: ['Токио', 'Осака', 'Нагоя', 'Саппоро'] },
  { level: 1, country: 'Китай', flag: 'flags-svg/flag-cn.svg', a: ['Пекин', 'Шанхай', 'Гуанчжоу', 'Чэнду'] },
  { level: 1, country: 'Корея', flag: 'flags-svg/flag-kr.svg', a: ['Сеул', 'Пусан', 'Инчхон', 'Тэгу'] },
  { level: 1, country: 'Великобритания', flag: 'flags-svg/flag-gb.svg', a: ['Лондон', 'Бирмингем', 'Ливерпуль', 'Лидс'] },
  { level: 1, country: 'Канада', flag: 'flags-svg/flag-ca.svg', a: ['Оттава', 'Торонто', 'Ванкувер', 'Калгари'] },
  { level: 1, country: 'Австралия', flag: 'flags-svg/flag-au.svg', a: ['Канберра', 'Сидней', 'Мельбурн', 'Брисбен'] },
  { level: 1, country: 'Бразилия', flag: 'flags-svg/flag-br.svg', a: ['Бразилиа', 'Рио-де-Жанейро', 'Сан-Паулу', 'Сальвадор'] },
  { level: 1, country: 'Мексика', flag: 'flags-svg/flag-mx.svg', a: ['Мехико', 'Гвадалахара', 'Монтеррей', 'Пуэбла'] },
  { level: 1, country: 'Индия', flag: 'flags-svg/flag-in.svg', a: ['Нью-Дели', 'Мумбаи', 'Бангалор', 'Хайдарабад'] },
  // ---------- Добавленные страны (уровень 1) ----------
  { level: 1, country: 'Дания', flag: 'flags-svg/flag-dk.svg', a: ['Копенгаген', 'Орхус', 'Оденсе', 'Ольборг'] },
  { level: 1, country: 'Украина', flag: 'flags-svg/flag-ua.svg', a: ['Киев', 'Одесса', 'Львов', 'Днепр'] },
  { level: 1, country: 'Греция', flag: 'flags-svg/flag-gr.svg', a: ['Афины', 'Салоники', 'Патры', 'Ираклион'] },
  { level: 1, country: 'Австрия', flag: 'flags-svg/flag-at.svg', a: ['Вена', 'Грац', 'Зальцбург', 'Линц'] },
  { level: 1, country: 'Швейцария', flag: 'flags-svg/flag-ch.svg', a: ['Берн', 'Цюрих', 'Женева', 'Базель'] },
  { level: 1, country: 'Румыния', flag: 'flags-svg/flag-ro.svg', a: ['Бухарест', 'Клуж', 'Яссы', 'Тимшоара'] },
  { level: 1, country: 'Венгрия', flag: 'flags-svg/flag-hu.svg', a: ['Будапешт', 'Дебрецен', 'Сегед', 'Мишкольц'] },
  { level: 1, country: 'Чехия', flag: 'flags-svg/flag-cz.svg', a: ['Прага', 'Брно', 'Острава', 'Пльзень'] },
  { level: 1, country: 'Таиланд', flag: 'flags-svg/flag-th.svg', a: ['Бангкок', 'Паттайя', 'Чиангмай', 'Самуи'] },
  { level: 1, country: 'Вьетнам', flag: 'flags-svg/flag-vn.svg', a: ['Ханой', 'Хошимин', 'Дананг', 'Хайфон'] },
  { level: 1, country: 'Индонезия', flag: 'flags-svg/flag-id.svg', a: ['Джакарта', 'Сурабая', 'Бандунг', 'Медеан'] },
  { level: 1, country: 'Турция', flag: 'flags-svg/flag-tr.svg', a: ['Анкара', 'Стамбул', 'Измир', 'Анталья'] },
  // ---------- Уровень 2 ----------
  { level: 2, country: 'Польша', flag: 'flags-svg/flag-pl.svg', a: ['Варшава', 'Краков', 'Вроцлав', 'Гданьск'] },
  { level: 2, country: 'Нидерланды', flag: 'flags-svg/flag-nl.svg', a: ['Амстердам', 'Роттердам', 'Гаага', 'Утрехт'] },
  { level: 2, country: 'Бельгия', flag: 'flags-svg/flag-be.svg', a: ['Брюссель', 'Антверпен', 'Гент', 'Льеж'] },
  { level: 2, country: 'Швеция', flag: 'flags-svg/flag-se.svg', a: ['Стокгольм', 'Гётеборг', 'Мальмё', 'Уппсала'] },
  { level: 2, country: 'Норвегия', flag: 'flags-svg/flag-no.svg', a: ['Осло', 'Берген', 'Тромсё', 'Ставангер'] },
  { level: 2, country: 'Финляндия', flag: 'flags-svg/flag-fi.svg', a: ['Хельсинки', 'Эспоо', 'Тампере', 'Турку'] },
  { level: 2, country: 'Ирландия', flag: 'flags-svg/flag-ie.svg', a: ['Дублин', 'Корк', 'Голуэй', 'Лимерик'] },
  { level: 2, country: 'Португалия', flag: 'flags-svg/flag-pt.svg', a: ['Лиссабон', 'Порту', 'Брага', 'Фару'] },
  { level: 2, country: 'Азербайджан', flag: 'flags-svg/flag-az.svg', a: ['Баку', 'Гянджа', 'Сумгаит', 'Шеки'] },
  { level: 2, country: 'Перу', flag: 'flags-svg/flag-pe.svg', a: ['Лима', 'Куско', 'Арекипа', 'Трухильо'] },
  { level: 2, country: 'Казахстан', flag: 'flags-svg/flag-kz.svg', a: ['Астана', 'Алматы', 'Шымкент', 'Караганда'] },
  { level: 2, country: 'Армения', flag: 'flags-svg/flag-am.svg', a: ['Ереван', 'Гюмри', 'Ванадзор', 'Севан'] },
  { level: 2, country: 'Грузия', flag: 'flags-svg/flag-ge.svg', a: ['Тбилиси', 'Батуми', 'Кутаиси', 'Рустави'] },
  { level: 2, country: 'Узбекистан', flag: 'flags-svg/flag-uz.svg', a: ['Ташкент', 'Самарканд', 'Бухара', 'Хива'] },
  // ---------- Добавленные страны (уровень 2) ----------
  { level: 2, country: 'Болгария', flag: 'flags-svg/flag-bg.svg', a: ['София', 'Пловдив', 'Варна', 'Бургас'] },
  { level: 2, country: 'Мальта', flag: 'flags-svg/flag-mt.svg', a: ['Валлетта', 'Слима', 'Мсина', 'Гоцо'] },
  { level: 2, country: 'Чили', flag: 'flags-svg/flag-cl.svg', a: ['Сантьяго', 'Вальпараисо', 'Консепсьон', 'Пунта-Аренас'] },
  { level: 2, country: 'Аргентина', flag: 'flags-svg/flag-ar.svg', a: ['Буэнос-Айрес', 'Кордова', 'Розарио', 'Мендоса'] },
  { level: 2, country: 'Филиппины', flag: 'flags-svg/flag-ph.svg', a: ['Манила', 'Кесон-Сити', 'Себу', 'Илоило'] },
  { level: 2, country: 'Египет', flag: 'flags-svg/flag-eg.svg', a: ['Каир', 'Александрия', 'Гиза', 'Асуан'] },
  { level: 2, country: 'Израиль', flag: 'flags-svg/flag-il.svg', a: ['Иерусалим', 'Тель-Авив', 'Хайфа', 'Беэр-Шеба'] },
  { level: 2, country: 'Эстония', flag: 'flags-svg/flag-ee.svg', a: ['Таллин', 'Тарту', 'Пярну', 'Нарва'] },
  { level: 2, country: 'Латвия', flag: 'flags-svg/flag-lv.svg', a: ['Рига', 'Вильнюс', 'Даугавпилс', 'Лиепая'] },
  { level: 2, country: 'Литва', flag: 'flags-svg/flag-lt.svg', a: ['Вильнюс', 'Каунас', 'Клайпеда', 'Шяуляй'] },
  { level: 2, country: 'Исландия', flag: 'flags-svg/flag-is.svg', a: ['Рейкьявик', 'Акюрейри', 'Асавери', 'Исафьёрдур'] },
  { level: 2, country: 'Люксембург', flag: 'flags-svg/flag-lu.svg', a: ['Люксембург', 'Эш-сур-Альзетт', 'Диффенгахен', 'Вианден'] },
  { level: 2, country: 'Словакия', flag: 'flags-svg/flag-sk.svg', a: ['Братислава', 'Кошице', 'Прешов', 'Жилина'] },
  { level: 2, country: 'Словения', flag: 'flags-svg/flag-si.svg', a: ['Любляна', 'Марибор', 'Целе', 'Копер'] },
  { level: 2, country: 'Хорватия', flag: 'flags-svg/flag-hr.svg', a: ['Загреб', 'Сплит', 'Риека', 'Осиек'] },
  { level: 2, country: 'Молдова', flag: 'flags-svg/flag-md.svg', a: ['Кишинев', 'Бельцы', 'Балты', 'Тирасполь'] },
  { level: 2, country: 'Марокко', flag: 'flags-svg/flag-ma.svg', a: ['Рабат', 'Касабланка', 'Фес', 'Марракеш'] },
  { level: 2, country: 'Алжир', flag: 'flags-svg/flag-dz.svg', a: ['Алжир', 'Оран', 'Константина', 'Аннаба'] },
  { level: 2, country: 'Тунис', flag: 'flags-svg/flag-tn.svg', a: ['Тунис', 'Суфса', 'Кайруан', 'Бизерта'] },
  { level: 2, country: 'Иордания', flag: 'flags-svg/flag-jo.svg', a: ['Амман', 'Ирбид', 'Зарка', 'Акаба'] },
  // ---------- Уровень 3 ----------
  { level: 3, country: 'Киргизия', flag: 'flags-svg/flag-kg.svg', a: ['Бишкек', 'Ош', 'Джалал-Абад', 'Каракол'] },
  { level: 3, country: 'Таджикистан', flag: 'flags-svg/flag-tj.svg', a: ['Душанбе', 'Худжанд', 'Куляб', 'Бохтар'] },
  { level: 3, country: 'Лихтенштейн', flag: 'flags-svg/flag-li.svg', a: ['Вадуц', 'Шаан', 'Бальцерс', 'Эшен'] },
  { level: 3, country: 'Сан-Марино', flag: 'flags-svg/flag-sm.svg', a: ['Сан-Марино', 'Серравалле', 'Борго-Маджоре', 'Фаэтано'] },
  { level: 3, country: 'Монако', flag: 'flags-svg/flag-mc.svg', a: ['Монако', 'Монте-Карло', 'Ла-Кондамин', 'Фонвьей'] },
  { level: 3, country: 'Сан-Томе', flag: 'flags-svg/flag-st.svg', a: ['Сан-Томе', 'Триндади', 'Невис', 'Гуадалупе'] },
  { level: 3, country: 'Кувейт', flag: 'flags-svg/flag-kw.svg', a: ['Кувейт', 'Эль-Ахмади', 'Эль-Джахра', 'Хавалли'] },
  { level: 3, country: 'Сирия', flag: 'flags-svg/flag-sy.svg', a: ['Дамаск', 'Алеппо', 'Хомс', 'Латакия'] },
  { level: 3, country: 'Мьянма', flag: 'flags-svg/flag-mm.svg', a: ['Нейпьидо', 'Янгон', 'Мандалай', 'Баган'] },
  { level: 3, country: 'ЦАР', flag: 'flags-svg/flag-cf.svg', a: ['Банги', 'Бимбо', 'Берберати', 'Бангассу'] },
  { level: 3, country: 'Нигер', flag: 'flags-svg/flag-ne.svg', a: ['Ниамей', 'Зиндер', 'Маради', 'Агадес'] },
  { level: 3, country: 'Чад', flag: 'flags-svg/flag-td.svg', a: ['Нджамена', 'Мунду', 'Абеше', 'Сарх'] },
  { level: 3, country: 'Сьерра-Леоне', flag: 'flags-svg/flag-sl.svg', a: ['Фритаун', 'Бо', 'Кенема', 'Макени'] },
  { level: 3, country: 'Того', flag: 'flags-svg/flag-tg.svg', a: ['Ломе', 'Сокоде', 'Кара', 'Атакпаме'] },
  // ---------- Добавленные страны (уровень 3) ----------
  { level: 3, country: 'ОАЭ', flag: 'flags-svg/flag-ae.svg', a: ['Абу-Даби', 'Дубай', 'Шарджа', 'Аджман'] },
  { level: 3, country: 'Иран', flag: 'flags-svg/flag-ir.svg', a: ['Тегеран', 'Исфахан', 'Шираз', 'Мешхед'] },
  { level: 3, country: 'Лаос', flag: 'flags-svg/flag-la.svg', a: ['Вьентьян', 'Луангпхабанга', 'Саваннакхет', 'Ваксак'] },
  { level: 3, country: 'Камбоджа', flag: 'flags-svg/flag-kh.svg', a: ['Пномпень', 'Сием-Реап', 'Баттамбанг', 'Кампинг'] },
  { level: 3, country: 'Бангладеш', flag: 'flags-svg/flag-bd.svg', a: ['Дакка', 'Читтагонг', 'Хульна', 'Силхет'] },
  { level: 3, country: 'Эквадор', flag: 'flags-svg/flag-ec.svg', a: ['Кито', 'Гуаякиль', 'Куэнка', 'Амбато'] },
  { level: 3, country: 'Боливия', flag: 'flags-svg/flag-bo.svg', a: ['Сукре', 'Ла-Пас', 'Санта-Крус', 'Кочабамба'] },
  { level: 3, country: 'Парагвай', flag: 'flags-svg/flag-py.svg', a: ['Асунсьон', 'Сьюдад-дель-Эсте', 'Карапегуа', 'Мариана'] },
  { level: 3, country: 'Коста-Рика', flag: 'flags-svg/flag-cr.svg', a: ['Сан-Хосе', 'Эспириту-Санто', 'Либерто', 'Пурас'] },
  { level: 3, country: 'Куба', flag: 'flags-svg/flag-cu.svg', a: ['Гавана', 'Сантьяго-де-Куба', 'Матансас', 'Камагуей'] },
  { level: 3, country: 'Ямайка', flag: 'flags-svg/flag-jm.svg', a: ['Кингстон', 'Монтегобей', 'Очо-Риос', 'Манчестер'] },
  { level: 3, country: 'Маврикий', flag: 'flags-svg/flag-mu.svg', a: ['Порт-Луис', 'Куап', 'Боубой', 'Марильяж'] },
  { level: 3, country: 'Беларусь', flag: 'flags-svg/flag-by.svg', a: ['Минск', 'Гомель', 'Брест', 'Витебск'] },
  { level: 3, country: 'Сербия', flag: 'flags-svg/flag-rs.svg', a: ['Белград', 'Нови-Сад', 'Ниш', 'Крагуевац'] },
];
