// cards/cards_flash.js — данные для игры «Флеш карты» (games/kids-flash.js).
// FLASH_THEMES — список тем.
// FLASH_WORDS — карточки: { theme, group, word, transcription, translation }.
//   group — размер пула, в который входит карточка (для темы 'english'):
//   в подборку "100 слов" входят карточки group<=100, в подборку "250 слов"
//   — все карточки этой темы (те же 100 базовых + 150 более сложных, без
//   повторов). Для других тем (например, 'animals') поле group не влияет на
//   выборку — берутся все карточки темы.

const FLASH_THEMES = [
  { id: 'english', icon: '🇬🇧', name: 'Английский язык' },
  { id: 'animals', icon: '🐾', name: 'Животные' },
  { id: 'verbs', icon: '🔤', name: 'Глаголы' },
  { id: 'time', icon: '🕐', name: 'Время' },
];

const FLASH_WORDS = [
  { theme: 'english', group: 100, word: 'the', transcription: 'ðə', translation: 'определённый артикль' },
  { theme: 'english', group: 100, word: 'a', transcription: 'ə', translation: 'неопределённый артикль' },
  { theme: 'english', group: 100, word: 'I', transcription: 'aɪ', translation: 'я' },
  { theme: 'english', group: 100, word: 'you', transcription: 'juː', translation: 'ты, вы' },
  { theme: 'english', group: 100, word: 'he', transcription: 'hiː', translation: 'он' },
  { theme: 'english', group: 100, word: 'she', transcription: 'ʃiː', translation: 'она' },
  { theme: 'english', group: 100, word: 'it', transcription: 'ɪt', translation: 'он/она/оно (неодуш.)' },
  { theme: 'english', group: 100, word: 'we', transcription: 'wiː', translation: 'мы' },
  { theme: 'english', group: 100, word: 'they', transcription: 'ðeɪ', translation: 'они' },
  { theme: 'english', group: 100, word: 'is', transcription: 'ɪz', translation: 'есть (он/она/оно)' },
  { theme: 'english', group: 100, word: 'am', transcription: 'æm', translation: 'есть (я)' },
  { theme: 'english', group: 100, word: 'are', transcription: 'ɑːr', translation: 'есть (ты/мы/они)' },
  { theme: 'english', group: 100, word: 'was', transcription: 'wɒz', translation: 'был, была, было' },
  { theme: 'english', group: 100, word: 'were', transcription: 'wɜːr', translation: 'были' },
  { theme: 'english', group: 100, word: 'be', transcription: 'biː', translation: 'быть' },
  { theme: 'english', group: 100, word: 'have', transcription: 'hæv', translation: 'иметь' },
  { theme: 'english', group: 100, word: 'has', transcription: 'hæz', translation: 'имеет' },
  { theme: 'english', group: 100, word: 'do', transcription: 'duː', translation: 'делать' },
  { theme: 'english', group: 100, word: 'does', transcription: 'dʌz', translation: 'делает' },
  { theme: 'english', group: 100, word: 'go', transcription: 'ɡəʊ', translation: 'идти' },
  { theme: 'english', group: 100, word: 'yes', transcription: 'jes', translation: 'да' },
  { theme: 'english', group: 100, word: 'no', transcription: 'nəʊ', translation: 'нет' },
  { theme: 'english', group: 100, word: 'and', transcription: 'ænd', translation: 'и' },
  { theme: 'english', group: 100, word: 'or', transcription: 'ɔːr', translation: 'или' },
  { theme: 'english', group: 100, word: 'but', transcription: 'bʌt', translation: 'но' },
  { theme: 'english', group: 100, word: 'not', transcription: 'nɒt', translation: 'не' },
  { theme: 'english', group: 100, word: 'this', transcription: 'ðɪs', translation: 'это, этот' },
  { theme: 'english', group: 100, word: 'that', transcription: 'ðæt', translation: 'то, тот' },
  { theme: 'english', group: 100, word: 'these', transcription: 'ðiːz', translation: 'эти' },
  { theme: 'english', group: 100, word: 'those', transcription: 'ðəʊz', translation: 'те' },
  { theme: 'english', group: 100, word: 'what', transcription: 'wɒt', translation: 'что' },
  { theme: 'english', group: 100, word: 'who', transcription: 'huː', translation: 'кто' },
  { theme: 'english', group: 100, word: 'where', transcription: 'weər', translation: 'где' },
  { theme: 'english', group: 100, word: 'when', transcription: 'wen', translation: 'когда' },
  { theme: 'english', group: 100, word: 'why', transcription: 'waɪ', translation: 'почему' },
  { theme: 'english', group: 100, word: 'how', transcription: 'haʊ', translation: 'как' },
  { theme: 'english', group: 100, word: 'my', transcription: 'maɪ', translation: 'мой' },
  { theme: 'english', group: 100, word: 'your', transcription: 'jɔːr', translation: 'твой' },
  { theme: 'english', group: 100, word: 'his', transcription: 'hɪz', translation: 'его' },
  { theme: 'english', group: 100, word: 'her', transcription: 'hɜːr', translation: 'её' },
  { theme: 'english', group: 100, word: 'our', transcription: 'aʊər', translation: 'наш' },
  { theme: 'english', group: 100, word: 'their', transcription: 'ðeər', translation: 'их' },
  { theme: 'english', group: 100, word: 'name', transcription: 'neɪm', translation: 'имя' },
  { theme: 'english', group: 100, word: 'house', transcription: 'haʊs', translation: 'дом' },
  { theme: 'english', group: 100, word: 'water', transcription: 'ˈwɔːtər', translation: 'вода' },
  { theme: 'english', group: 100, word: 'food', transcription: 'fuːd', translation: 'еда' },
  { theme: 'english', group: 100, word: 'day', transcription: 'deɪ', translation: 'день' },
  { theme: 'english', group: 100, word: 'night', transcription: 'naɪt', translation: 'ночь' },
  { theme: 'english', group: 100, word: 'time', transcription: 'taɪm', translation: 'время' },
  { theme: 'english', group: 100, word: 'year', transcription: 'jɪər', translation: 'год' },
  { theme: 'english', group: 100, word: 'man', transcription: 'mæn', translation: 'мужчина' },
  { theme: 'english', group: 100, word: 'woman', transcription: 'ˈwʊmən', translation: 'женщина' },
  { theme: 'english', group: 100, word: 'child', transcription: 'tʃaɪld', translation: 'ребёнок' },
  { theme: 'english', group: 100, word: 'friend', transcription: 'frend', translation: 'друг' },
  { theme: 'english', group: 100, word: 'family', transcription: 'ˈfæməli', translation: 'семья' },
  { theme: 'english', group: 100, word: 'school', transcription: 'skuːl', translation: 'школа' },
  { theme: 'english', group: 100, word: 'work', transcription: 'wɜːrk', translation: 'работа' },
  { theme: 'english', group: 100, word: 'book', transcription: 'bʊk', translation: 'книга' },
  { theme: 'english', group: 100, word: 'table', transcription: 'ˈteɪbl', translation: 'стол' },
  { theme: 'english', group: 100, word: 'chair', transcription: 'tʃeər', translation: 'стул' },
  { theme: 'english', group: 100, word: 'door', transcription: 'dɔːr', translation: 'дверь' },
  { theme: 'english', group: 100, word: 'window', transcription: 'ˈwɪndəʊ', translation: 'окно' },
  { theme: 'english', group: 100, word: 'car', transcription: 'kɑːr', translation: 'машина' },
  { theme: 'english', group: 100, word: 'city', transcription: 'ˈsɪti', translation: 'город' },
  { theme: 'english', group: 100, word: 'country', transcription: 'ˈkʌntri', translation: 'страна' },
  { theme: 'english', group: 100, word: 'street', transcription: 'striːt', translation: 'улица' },
  { theme: 'english', group: 100, word: 'money', transcription: 'ˈmʌni', translation: 'деньги' },
  { theme: 'english', group: 100, word: 'love', transcription: 'lʌv', translation: 'любовь' },
  { theme: 'english', group: 100, word: 'happy', transcription: 'ˈhæpi', translation: 'счастливый' },
  { theme: 'english', group: 100, word: 'sad', transcription: 'sæd', translation: 'грустный' },
  { theme: 'english', group: 100, word: 'big', transcription: 'bɪɡ', translation: 'большой' },
  { theme: 'english', group: 100, word: 'small', transcription: 'smɔːl', translation: 'маленький' },
  { theme: 'english', group: 100, word: 'good', transcription: 'ɡʊd', translation: 'хороший' },
  { theme: 'english', group: 100, word: 'bad', transcription: 'bæd', translation: 'плохой' },
  { theme: 'english', group: 100, word: 'new', transcription: 'njuː', translation: 'новый' },
  { theme: 'english', group: 100, word: 'old', transcription: 'əʊld', translation: 'старый' },
  { theme: 'english', group: 100, word: 'hot', transcription: 'hɒt', translation: 'горячий' },
  { theme: 'english', group: 100, word: 'cold', transcription: 'kəʊld', translation: 'холодный' },
  { theme: 'english', group: 100, word: 'one', transcription: 'wʌn', translation: 'один' },
  { theme: 'english', group: 100, word: 'two', transcription: 'tuː', translation: 'два' },
  { theme: 'english', group: 100, word: 'three', transcription: 'θriː', translation: 'три' },
  { theme: 'english', group: 100, word: 'four', transcription: 'fɔːr', translation: 'четыре' },
  { theme: 'english', group: 100, word: 'five', transcription: 'faɪv', translation: 'пять' },
  { theme: 'english', group: 100, word: 'six', transcription: 'sɪks', translation: 'шесть' },
  { theme: 'english', group: 100, word: 'seven', transcription: 'ˈsevən', translation: 'семь' },
  { theme: 'english', group: 100, word: 'eight', transcription: 'eɪt', translation: 'восемь' },
  { theme: 'english', group: 100, word: 'nine', transcription: 'naɪn', translation: 'девять' },
  { theme: 'english', group: 100, word: 'ten', transcription: 'ten', translation: 'десять' },
  { theme: 'english', group: 100, word: 'hello', transcription: 'həˈləʊ', translation: 'привет' },
  { theme: 'english', group: 100, word: 'goodbye', transcription: 'ˌɡʊdˈbaɪ', translation: 'до свидания' },
  { theme: 'english', group: 100, word: 'please', transcription: 'pliːz', translation: 'пожалуйста' },
  { theme: 'english', group: 100, word: 'thanks', transcription: 'θæŋks', translation: 'спасибо' },
  { theme: 'english', group: 100, word: 'sorry', transcription: 'ˈsɒri', translation: 'извини' },
  { theme: 'english', group: 100, word: 'eat', transcription: 'iːt', translation: 'есть, кушать' },
  { theme: 'english', group: 100, word: 'drink', transcription: 'drɪŋk', translation: 'пить' },
  { theme: 'english', group: 100, word: 'sleep', transcription: 'sliːp', translation: 'спать' },
  { theme: 'english', group: 100, word: 'run', transcription: 'rʌn', translation: 'бежать' },
  { theme: 'english', group: 100, word: 'walk', transcription: 'wɔːk', translation: 'идти пешком' },
  { theme: 'english', group: 100, word: 'see', transcription: 'siː', translation: 'видеть' },
  { theme: 'english', group: 100, word: 'know', transcription: 'nəʊ', translation: 'знать' },
  { theme: 'english', group: 250, word: 'want', transcription: 'wɒnt', translation: 'хотеть' },
  { theme: 'english', group: 250, word: 'need', transcription: 'niːd', translation: 'нуждаться' },
  { theme: 'english', group: 250, word: 'like', transcription: 'laɪk', translation: 'нравиться' },
  { theme: 'english', group: 250, word: 'think', transcription: 'θɪŋk', translation: 'думать' },
  { theme: 'english', group: 250, word: 'say', transcription: 'seɪ', translation: 'говорить, сказать' },
  { theme: 'english', group: 250, word: 'tell', transcription: 'tel', translation: 'рассказать' },
  { theme: 'english', group: 250, word: 'speak', transcription: 'spiːk', translation: 'говорить' },
  { theme: 'english', group: 250, word: 'talk', transcription: 'tɔːk', translation: 'разговаривать' },
  { theme: 'english', group: 250, word: 'ask', transcription: 'ɑːsk', translation: 'спрашивать' },
  { theme: 'english', group: 250, word: 'answer', transcription: 'ˈɑːnsər', translation: 'отвечать' },
  { theme: 'english', group: 250, word: 'read', transcription: 'riːd', translation: 'читать' },
  { theme: 'english', group: 250, word: 'write', transcription: 'raɪt', translation: 'писать' },
  { theme: 'english', group: 250, word: 'listen', transcription: 'ˈlɪsən', translation: 'слушать' },
  { theme: 'english', group: 250, word: 'hear', transcription: 'hɪər', translation: 'слышать' },
  { theme: 'english', group: 250, word: 'look', transcription: 'lʊk', translation: 'смотреть' },
  { theme: 'english', group: 250, word: 'watch', transcription: 'wɒtʃ', translation: 'наблюдать' },
  { theme: 'english', group: 250, word: 'play', transcription: 'pleɪ', translation: 'играть' },
  { theme: 'english', group: 250, word: 'help', transcription: 'help', translation: 'помогать' },
  { theme: 'english', group: 250, word: 'give', transcription: 'ɡɪv', translation: 'давать' },
  { theme: 'english', group: 250, word: 'take', transcription: 'teɪk', translation: 'брать' },
  { theme: 'english', group: 250, word: 'get', transcription: 'ɡet', translation: 'получать' },
  { theme: 'english', group: 250, word: 'make', transcription: 'meɪk', translation: 'делать, создавать' },
  { theme: 'english', group: 250, word: 'put', transcription: 'pʊt', translation: 'класть' },
  { theme: 'english', group: 250, word: 'find', transcription: 'faɪnd', translation: 'находить' },
  { theme: 'english', group: 250, word: 'lose', transcription: 'luːz', translation: 'терять' },
  { theme: 'english', group: 250, word: 'buy', transcription: 'baɪ', translation: 'покупать' },
  { theme: 'english', group: 250, word: 'sell', transcription: 'sel', translation: 'продавать' },
  { theme: 'english', group: 250, word: 'pay', transcription: 'peɪ', translation: 'платить' },
  { theme: 'english', group: 250, word: 'open', transcription: 'ˈəʊpən', translation: 'открывать' },
  { theme: 'english', group: 250, word: 'close', transcription: 'kləʊz', translation: 'закрывать' },
  { theme: 'english', group: 250, word: 'start', transcription: 'stɑːrt', translation: 'начинать' },
  { theme: 'english', group: 250, word: 'stop', transcription: 'stɒp', translation: 'останавливать' },
  { theme: 'english', group: 250, word: 'finish', transcription: 'ˈfɪnɪʃ', translation: 'заканчивать' },
  { theme: 'english', group: 250, word: 'wait', transcription: 'weɪt', translation: 'ждать' },
  { theme: 'english', group: 250, word: 'live', transcription: 'lɪv', translation: 'жить' },
  { theme: 'english', group: 250, word: 'die', transcription: 'daɪ', translation: 'умирать' },
  { theme: 'english', group: 250, word: 'born', transcription: 'bɔːrn', translation: 'рождённый' },
  { theme: 'english', group: 250, word: 'grow', transcription: 'ɡrəʊ', translation: 'расти' },
  { theme: 'english', group: 250, word: 'change', transcription: 'tʃeɪndʒ', translation: 'менять' },
  { theme: 'english', group: 250, word: 'move', transcription: 'muːv', translation: 'двигаться' },
  { theme: 'english', group: 250, word: 'stay', transcription: 'steɪ', translation: 'оставаться' },
  { theme: 'english', group: 250, word: 'leave', transcription: 'liːv', translation: 'уходить' },
  { theme: 'english', group: 250, word: 'arrive', transcription: 'əˈraɪv', translation: 'прибывать' },
  { theme: 'english', group: 250, word: 'come', transcription: 'kʌm', translation: 'приходить' },
  { theme: 'english', group: 250, word: 'bring', transcription: 'brɪŋ', translation: 'приносить' },
  { theme: 'english', group: 250, word: 'send', transcription: 'send', translation: 'отправлять' },
  { theme: 'english', group: 250, word: 'use', transcription: 'juːz', translation: 'использовать' },
  { theme: 'english', group: 250, word: 'try', transcription: 'traɪ', translation: 'пытаться' },
  { theme: 'english', group: 250, word: 'learn', transcription: 'lɜːrn', translation: 'учить, учиться' },
  { theme: 'english', group: 250, word: 'teach', transcription: 'tiːtʃ', translation: 'обучать' },
  { theme: 'english', group: 250, word: 'study', transcription: 'ˈstʌdi', translation: 'изучать' },
  { theme: 'english', group: 250, word: 'remember', transcription: 'rɪˈmembər', translation: 'помнить' },
  { theme: 'english', group: 250, word: 'forget', transcription: 'fərˈɡet', translation: 'забывать' },
  { theme: 'english', group: 250, word: 'understand', transcription: 'ˌʌndərˈstænd', translation: 'понимать' },
  { theme: 'english', group: 250, word: 'believe', transcription: 'bɪˈliːv', translation: 'верить' },
  { theme: 'english', group: 250, word: 'hope', transcription: 'həʊp', translation: 'надеяться' },
  { theme: 'english', group: 250, word: 'feel', transcription: 'fiːl', translation: 'чувствовать' },
  { theme: 'english', group: 250, word: 'wish', transcription: 'wɪʃ', translation: 'желать' },
  { theme: 'english', group: 250, word: 'dream', transcription: 'driːm', translation: 'мечтать' },
  { theme: 'english', group: 250, word: 'laugh', transcription: 'lɑːf', translation: 'смеяться' },
  { theme: 'english', group: 250, word: 'cry', transcription: 'kraɪ', translation: 'плакать' },
  { theme: 'english', group: 250, word: 'smile', transcription: 'smaɪl', translation: 'улыбаться' },
  { theme: 'english', group: 250, word: 'shout', transcription: 'ʃaʊt', translation: 'кричать' },
  { theme: 'english', group: 250, word: 'sing', transcription: 'sɪŋ', translation: 'петь' },
  { theme: 'english', group: 250, word: 'dance', transcription: 'dɑːns', translation: 'танцевать' },
  { theme: 'english', group: 250, word: 'cook', transcription: 'kʊk', translation: 'готовить' },
  { theme: 'english', group: 250, word: 'clean', transcription: 'kliːn', translation: 'убирать' },
  { theme: 'english', group: 250, word: 'wash', transcription: 'wɒʃ', translation: 'мыть' },
  { theme: 'english', group: 250, word: 'build', transcription: 'bɪld', translation: 'строить' },
  { theme: 'english', group: 250, word: 'break', transcription: 'breɪk', translation: 'ломать' },
  { theme: 'english', group: 250, word: 'fix', transcription: 'fɪks', translation: 'чинить' },
  { theme: 'english', group: 250, word: 'push', transcription: 'pʊʃ', translation: 'толкать' },
  { theme: 'english', group: 250, word: 'pull', transcription: 'pʊl', translation: 'тянуть' },
  { theme: 'english', group: 250, word: 'carry', transcription: 'ˈkæri', translation: 'нести' },
  { theme: 'english', group: 250, word: 'hold', transcription: 'həʊld', translation: 'держать' },
  { theme: 'english', group: 250, word: 'touch', transcription: 'tʌtʃ', translation: 'трогать' },
  { theme: 'english', group: 250, word: 'kiss', transcription: 'kɪs', translation: 'целовать' },
  { theme: 'english', group: 250, word: 'hug', transcription: 'hʌɡ', translation: 'обнимать' },
  { theme: 'english', group: 250, word: 'meet', transcription: 'miːt', translation: 'встречать' },
  { theme: 'english', group: 250, word: 'visit', transcription: 'ˈvɪzɪt', translation: 'посещать' },
  { theme: 'english', group: 250, word: 'travel', transcription: 'ˈtrævəl', translation: 'путешествовать' },
  { theme: 'english', group: 250, word: 'fly', transcription: 'flaɪ', translation: 'летать' },
  { theme: 'english', group: 250, word: 'drive', transcription: 'draɪv', translation: 'водить машину' },
  { theme: 'english', group: 250, word: 'ride', transcription: 'raɪd', translation: 'кататься' },
  { theme: 'english', group: 250, word: 'swim', transcription: 'swɪm', translation: 'плавать' },
  { theme: 'english', group: 250, word: 'jump', transcription: 'dʒʌmp', translation: 'прыгать' },
  { theme: 'english', group: 250, word: 'sit', transcription: 'sɪt', translation: 'сидеть' },
  { theme: 'english', group: 250, word: 'stand', transcription: 'stænd', translation: 'стоять' },
  { theme: 'english', group: 250, word: 'wake', transcription: 'weɪk', translation: 'просыпаться' },
  { theme: 'english', group: 250, word: 'wear', transcription: 'weər', translation: 'носить (одежду)' },
  { theme: 'english', group: 250, word: 'shop', transcription: 'ʃɒp', translation: 'магазин, делать покупки' },
  { theme: 'english', group: 250, word: 'spend', transcription: 'spend', translation: 'тратить' },
  { theme: 'english', group: 250, word: 'save', transcription: 'seɪv', translation: 'сохранять, копить' },
  { theme: 'english', group: 250, word: 'cost', transcription: 'kɒst', translation: 'стоить' },
  { theme: 'english', group: 250, word: 'cheap', transcription: 'tʃiːp', translation: 'дешёвый' },
  { theme: 'english', group: 250, word: 'expensive', transcription: 'ɪkˈspensɪv', translation: 'дорогой' },
  { theme: 'english', group: 250, word: 'easy', transcription: 'ˈiːzi', translation: 'лёгкий' },
  { theme: 'english', group: 250, word: 'difficult', transcription: 'ˈdɪfɪkəlt', translation: 'трудный' },
  { theme: 'english', group: 250, word: 'important', transcription: 'ɪmˈpɔːrtənt', translation: 'важный' },
  { theme: 'english', group: 250, word: 'beautiful', transcription: 'ˈbjuːtɪfl', translation: 'красивый' },
  { theme: 'english', group: 250, word: 'ugly', transcription: 'ˈʌɡli', translation: 'некрасивый' },
  { theme: 'english', group: 250, word: 'strong', transcription: 'strɒŋ', translation: 'сильный' },
  { theme: 'english', group: 250, word: 'weak', transcription: 'wiːk', translation: 'слабый' },
  { theme: 'english', group: 250, word: 'fast', transcription: 'fɑːst', translation: 'быстрый' },
  { theme: 'english', group: 250, word: 'slow', transcription: 'sləʊ', translation: 'медленный' },
  { theme: 'english', group: 250, word: 'early', transcription: 'ˈɜːrli', translation: 'ранний' },
  { theme: 'english', group: 250, word: 'late', transcription: 'leɪt', translation: 'поздний' },
  { theme: 'english', group: 250, word: 'near', transcription: 'nɪər', translation: 'близко' },
  { theme: 'english', group: 250, word: 'far', transcription: 'fɑːr', translation: 'далеко' },
  { theme: 'english', group: 250, word: 'high', transcription: 'haɪ', translation: 'высокий' },
  { theme: 'english', group: 250, word: 'low', transcription: 'ləʊ', translation: 'низкий' },
  { theme: 'english', group: 250, word: 'long', transcription: 'lɒŋ', translation: 'длинный' },
  { theme: 'english', group: 250, word: 'short', transcription: 'ʃɔːrt', translation: 'короткий' },
  { theme: 'english', group: 250, word: 'wide', transcription: 'waɪd', translation: 'широкий' },
  { theme: 'english', group: 250, word: 'narrow', transcription: 'ˈnærəʊ', translation: 'узкий' },
  { theme: 'english', group: 250, word: 'full', transcription: 'fʊl', translation: 'полный' },
  { theme: 'english', group: 250, word: 'empty', transcription: 'ˈempti', translation: 'пустой' },
  { theme: 'english', group: 250, word: 'dirty', transcription: 'ˈdɜːrti', translation: 'грязный' },
  { theme: 'english', group: 250, word: 'quiet', transcription: 'ˈkwaɪət', translation: 'тихий' },
  { theme: 'english', group: 250, word: 'loud', transcription: 'laʊd', translation: 'громкий' },
  { theme: 'english', group: 250, word: 'dark', transcription: 'dɑːrk', translation: 'тёмный' },
  { theme: 'english', group: 250, word: 'light', transcription: 'laɪt', translation: 'светлый, лёгкий' },
  { theme: 'english', group: 250, word: 'soft', transcription: 'sɒft', translation: 'мягкий' },
  { theme: 'english', group: 250, word: 'hard', transcription: 'hɑːrd', translation: 'твёрдый, трудный' },
  { theme: 'english', group: 250, word: 'sweet', transcription: 'swiːt', translation: 'сладкий' },
  { theme: 'english', group: 250, word: 'bitter', transcription: 'ˈbɪtər', translation: 'горький' },
  { theme: 'english', group: 250, word: 'sour', transcription: 'ˈsaʊər', translation: 'кислый' },
  { theme: 'english', group: 250, word: 'salty', transcription: 'ˈsɔːlti', translation: 'солёный' },
  { theme: 'english', group: 250, word: 'spicy', transcription: 'ˈspaɪsi', translation: 'острый (о еде)' },
  { theme: 'english', group: 250, word: 'fresh', transcription: 'freʃ', translation: 'свежий' },
  { theme: 'english', group: 250, word: 'rich', transcription: 'rɪtʃ', translation: 'богатый' },
  { theme: 'english', group: 250, word: 'poor', transcription: 'pɔːr', translation: 'бедный' },
  { theme: 'english', group: 250, word: 'free', transcription: 'friː', translation: 'свободный, бесплатный' },
  { theme: 'english', group: 250, word: 'busy', transcription: 'ˈbɪzi', translation: 'занятой' },
  { theme: 'english', group: 250, word: 'tired', transcription: 'ˈtaɪərd', translation: 'уставший' },
  { theme: 'english', group: 250, word: 'hungry', transcription: 'ˈhʌŋɡri', translation: 'голодный' },
  { theme: 'english', group: 250, word: 'thirsty', transcription: 'ˈθɜːrsti', translation: 'испытывающий жажду' },
  { theme: 'english', group: 250, word: 'sick', transcription: 'sɪk', translation: 'больной' },
  { theme: 'english', group: 250, word: 'healthy', transcription: 'ˈhelθi', translation: 'здоровый' },
  { theme: 'english', group: 250, word: 'safe', transcription: 'seɪf', translation: 'безопасный' },
  { theme: 'english', group: 250, word: 'dangerous', transcription: 'ˈdeɪndʒərəs', translation: 'опасный' },
  { theme: 'english', group: 250, word: 'true', transcription: 'truː', translation: 'правдивый' },
  { theme: 'english', group: 250, word: 'false', transcription: 'fɔːls', translation: 'ложный' },
  { theme: 'english', group: 250, word: 'real', transcription: 'rɪəl', translation: 'настоящий' },
  { theme: 'english', group: 250, word: 'same', transcription: 'seɪm', translation: 'одинаковый' },
  { theme: 'english', group: 250, word: 'different', transcription: 'ˈdɪfrənt', translation: 'разный' },
  { theme: 'english', group: 250, word: 'right', transcription: 'raɪt', translation: 'правильный, правый' },
  { theme: 'english', group: 250, word: 'wrong', transcription: 'rɒŋ', translation: 'неправильный' },
  { theme: 'english', group: 250, word: 'today', transcription: 'təˈdeɪ', translation: 'сегодня' },
  { theme: 'english', group: 250, word: 'tomorrow', transcription: 'təˈmɒrəʊ', translation: 'завтра' },

  // ---------- Тема: Животные (animals) ----------
  { theme: 'animals', group: 1, word: 'cat', transcription: 'kæt', translation: 'кошка' },
  { theme: 'animals', group: 1, word: 'dog', transcription: 'dɒɡ', translation: 'собака' },
  { theme: 'animals', group: 1, word: 'cow', transcription: 'kaʊ', translation: 'корова' },
  { theme: 'animals', group: 1, word: 'pig', transcription: 'pɪɡ', translation: 'свинья' },
  { theme: 'animals', group: 1, word: 'sheep', transcription: 'ʃiːp', translation: 'овца' },
  { theme: 'animals', group: 1, word: 'goat', transcription: 'ɡəʊt', translation: 'коза' },
  { theme: 'animals', group: 1, word: 'horse', transcription: 'hɔːs', translation: 'лошадь' },
  { theme: 'animals', group: 1, word: 'donkey', transcription: 'ˈdɒŋki', translation: 'осёл' },
  { theme: 'animals', group: 1, word: 'rabbit', transcription: 'ˈræbɪt', translation: 'кролик' },
  { theme: 'animals', group: 1, word: 'mouse', transcription: 'maʊs', translation: 'мышь' },
  { theme: 'animals', group: 1, word: 'rat', transcription: 'ræt', translation: 'крыса' },
  { theme: 'animals', group: 1, word: 'hamster', transcription: 'ˈhæmstə', translation: 'хомяк' },
  { theme: 'animals', group: 1, word: 'guinea pig', transcription: 'ˈɡɪni pɪɡ', translation: 'морская свинка' },
  { theme: 'animals', group: 1, word: 'bird', transcription: 'bɜːd', translation: 'птица' },
  { theme: 'animals', group: 1, word: 'duck', transcription: 'dʌk', translation: 'утка' },
  { theme: 'animals', group: 1, word: 'chicken', transcription: 'ˈtʃɪkɪn', translation: 'курица' },
  { theme: 'animals', group: 1, word: 'goose', transcription: 'ɡuːs', translation: 'гусь' },
  { theme: 'animals', group: 1, word: 'turkey', transcription: 'ˈtɜːki', translation: 'индюк' },
  { theme: 'animals', group: 1, word: 'fish', transcription: 'fɪʃ', translation: 'рыба' },
  { theme: 'animals', group: 1, word: 'frog', transcription: 'frɒɡ', translation: 'лягушка' },
  { theme: 'animals', group: 1, word: 'turtle', transcription: 'ˈtɜːtl', translation: 'черепаха' },
  { theme: 'animals', group: 1, word: 'snake', transcription: 'sneɪk', translation: 'змея' },
  { theme: 'animals', group: 1, word: 'lizard', transcription: 'ˈlɪzəd', translation: 'ящерица' },
  { theme: 'animals', group: 1, word: 'crocodile', transcription: 'ˈkrɒkədaɪl', translation: 'крокодил' },
  { theme: 'animals', group: 1, word: 'bee', transcription: 'biː', translation: 'пчела' },
  { theme: 'animals', group: 1, word: 'butterfly', transcription: 'ˈbʌtəflaɪ', translation: 'бабочка' },
  { theme: 'animals', group: 1, word: 'spider', transcription: 'ˈspaɪdə', translation: 'паук' },
  { theme: 'animals', group: 1, word: 'ant', transcription: 'ænt', translation: 'муравей' },
  { theme: 'animals', group: 1, word: 'ladybug', transcription: 'ˈleɪdɪbʌɡ', translation: 'божья коровка' },
  { theme: 'animals', group: 1, word: 'bear', transcription: 'beə', translation: 'медведь' },
  { theme: 'animals', group: 1, word: 'wolf', transcription: 'wʊlf', translation: 'волк' },
  { theme: 'animals', group: 1, word: 'fox', transcription: 'fɒks', translation: 'лиса' },
  { theme: 'animals', group: 1, word: 'deer', transcription: 'dɪə', translation: 'олень' },
  { theme: 'animals', group: 1, word: 'hare', transcription: 'heə', translation: 'заяц' },
  { theme: 'animals', group: 1, word: 'squirrel', transcription: 'ˈskwɪrəl', translation: 'белка' },
  { theme: 'animals', group: 1, word: 'hedgehog', transcription: 'ˈhedʒhɒɡ', translation: 'ёж' },
  { theme: 'animals', group: 1, word: 'lion', transcription: 'ˈlaɪən', translation: 'лев' },
  { theme: 'animals', group: 1, word: 'tiger', transcription: 'ˈtaɪɡə', translation: 'тигр' },
  { theme: 'animals', group: 1, word: 'elephant', transcription: 'ˈelɪfənt', translation: 'слон' },
  { theme: 'animals', group: 1, word: 'giraffe', transcription: 'dʒɪˈrɑːf', translation: 'жираф' },
  { theme: 'animals', group: 1, word: 'monkey', transcription: 'ˈmʌŋki', translation: 'обезьяна' },
  { theme: 'animals', group: 1, word: 'zebra', transcription: 'ˈziːbrə', translation: 'зебра' },
  { theme: 'animals', group: 1, word: 'hippo', transcription: 'ˈhɪpəʊ', translation: 'бегемот' },
  { theme: 'animals', group: 1, word: 'rhino', transcription: 'ˈraɪnəʊ', translation: 'носорог' },
  { theme: 'animals', group: 1, word: 'camel', transcription: 'ˈkæml', translation: 'верблюд' },
  { theme: 'animals', group: 1, word: 'kangaroo', transcription: 'ˌkæŋɡəˈruː', translation: 'кенгуру' },
  { theme: 'animals', group: 1, word: 'penguin', transcription: 'ˈpeŋɡwɪn', translation: 'пингвин' },
  { theme: 'animals', group: 1, word: 'owl', transcription: 'aʊl', translation: 'сова' },
  { theme: 'animals', group: 1, word: 'eagle', transcription: 'ˈiːɡl', translation: 'орёл' },
  { theme: 'animals', group: 1, word: 'parrot', transcription: 'ˈpærət', translation: 'попугай' },
  { theme: 'animals', group: 1, word: 'swan', transcription: 'swɒn', translation: 'лебедь' },
  { theme: 'animals', group: 1, word: 'rooster', transcription: 'ˈruːstə', translation: 'петух' },
  { theme: 'animals', group: 1, word: 'crab', transcription: 'kræb', translation: 'краб' },
  { theme: 'animals', group: 1, word: 'shrimp', transcription: 'ʃrɪmp', translation: 'креветка' },
  { theme: 'animals', group: 1, word: 'whale', transcription: 'weɪl', translation: 'кит' },
  { theme: 'animals', group: 1, word: 'dolphin', transcription: 'ˈdɒlfɪn', translation: 'дельфин' },
  { theme: 'animals', group: 1, word: 'shark', transcription: 'ʃɑːk', translation: 'акула' },
  { theme: 'animals', group: 1, word: 'octopus', transcription: 'ˈɒktəpəs', translation: 'осьминог' },
  { theme: 'animals', group: 1, word: 'seal', transcription: 'siːl', translation: 'тюлень' },
  { theme: 'animals', group: 1, word: 'panda', transcription: 'ˈpændə', translation: 'панда' },
  { theme: 'animals', group: 1, word: 'koala', transcription: 'kəʊˈɑːlə', translation: 'коала' },
  { theme: 'animals', group: 1, word: 'bat', transcription: 'bæt', translation: 'летучая мышь' },
  { theme: 'animals', group: 1, word: 'snail', transcription: 'sneɪl', translation: 'улитка' },
  { theme: 'animals', group: 1, word: 'worm', transcription: 'wɜːm', translation: 'червь' },
  { theme: 'animals', group: 1, word: 'caterpillar', transcription: 'ˈkætəpɪlə', translation: 'гусеница' },
  { theme: 'animals', group: 1, word: 'grasshopper', transcription: 'ˈɡrɑːshɒpə', translation: 'кузнечик' },
  { theme: 'animals', group: 1, word: 'beetle', transcription: 'ˈbiːtl', translation: 'жук' },
  { theme: 'animals', group: 1, word: 'lamb', transcription: 'læm', translation: 'ягнёнок' },
  { theme: 'animals', group: 1, word: 'calf', transcription: 'kɑːf', translation: 'телёнок' },
  { theme: 'animals', group: 1, word: 'puppy', transcription: 'ˈpʌpi', translation: 'щенок' },
  { theme: 'animals', group: 1, word: 'kitten', transcription: 'ˈkɪtn', translation: 'котёнок' },
  { theme: 'animals', group: 1, word: 'ox', transcription: 'ɒks', translation: 'бык' },
  { theme: 'animals', group: 1, word: 'buffalo', transcription: 'ˈbʌfələʊ', translation: 'буйвол' },
  { theme: 'animals', group: 1, word: 'peacock', transcription: 'ˈpiːkɒk', translation: 'павлин' },
  { theme: 'animals', group: 1, word: 'flamingo', transcription: 'fləˈmɪŋɡəʊ', translation: 'фламинго' },
  { theme: 'animals', group: 1, word: 'ostrich', transcription: 'ˈɒstrɪtʃ', translation: 'страус' },

  // ---------- Тема: Глаголы (verbs) ----------
  { theme: 'verbs', group: 1, word: 'be', transcription: 'biː', translation: 'быть' },
  { theme: 'verbs', group: 1, word: 'have', transcription: 'hæv', translation: 'иметь' },
  { theme: 'verbs', group: 1, word: 'do', transcription: 'duː', translation: 'делать' },
  { theme: 'verbs', group: 1, word: 'say', transcription: 'seɪ', translation: 'говорить, сказать' },
  { theme: 'verbs', group: 1, word: 'go', transcription: 'ɡəʊ', translation: 'идти' },
  { theme: 'verbs', group: 1, word: 'get', transcription: 'ɡet', translation: 'получать, становиться' },
  { theme: 'verbs', group: 1, word: 'make', transcription: 'meɪk', translation: 'делать, создавать' },
  { theme: 'verbs', group: 1, word: 'know', transcription: 'nəʊ', translation: 'знать' },
  { theme: 'verbs', group: 1, word: 'think', transcription: 'θɪŋk', translation: 'думать' },
  { theme: 'verbs', group: 1, word: 'take', transcription: 'teɪk', translation: 'брать' },
  { theme: 'verbs', group: 1, word: 'see', transcription: 'siː', translation: 'видеть' },
  { theme: 'verbs', group: 1, word: 'come', transcription: 'kʌm', translation: 'приходить' },
  { theme: 'verbs', group: 1, word: 'want', transcription: 'wɒnt', translation: 'хотеть' },
  { theme: 'verbs', group: 1, word: 'use', transcription: 'juːz', translation: 'использовать' },
  { theme: 'verbs', group: 1, word: 'find', transcription: 'faɪnd', translation: 'находить' },
  { theme: 'verbs', group: 1, word: 'give', transcription: 'ɡɪv', translation: 'давать' },
  { theme: 'verbs', group: 1, word: 'tell', transcription: 'tel', translation: 'рассказывать' },
  { theme: 'verbs', group: 1, word: 'work', transcription: 'wɜːk', translation: 'работать' },
  { theme: 'verbs', group: 1, word: 'call', transcription: 'kɔːl', translation: 'звать, звонить' },
  { theme: 'verbs', group: 1, word: 'try', transcription: 'traɪ', translation: 'пытаться' },
  { theme: 'verbs', group: 1, word: 'ask', transcription: 'ɑːsk', translation: 'спрашивать' },
  { theme: 'verbs', group: 1, word: 'need', transcription: 'niːd', translation: 'нуждаться' },
  { theme: 'verbs', group: 1, word: 'feel', transcription: 'fiːl', translation: 'чувствовать' },
  { theme: 'verbs', group: 1, word: 'become', transcription: 'bɪˈkʌm', translation: 'становиться' },
  { theme: 'verbs', group: 1, word: 'leave', transcription: 'liːv', translation: 'уходить, оставлять' },
  { theme: 'verbs', group: 1, word: 'put', transcription: 'pʊt', translation: 'класть' },
  { theme: 'verbs', group: 1, word: 'mean', transcription: 'miːn', translation: 'значить' },
  { theme: 'verbs', group: 1, word: 'keep', transcription: 'kiːp', translation: 'держать, хранить' },
  { theme: 'verbs', group: 1, word: 'let', transcription: 'let', translation: 'позволять' },
  { theme: 'verbs', group: 1, word: 'begin', transcription: 'bɪˈɡɪn', translation: 'начинать' },
  { theme: 'verbs', group: 1, word: 'seem', transcription: 'siːm', translation: 'казаться' },
  { theme: 'verbs', group: 1, word: 'help', transcription: 'help', translation: 'помогать' },
  { theme: 'verbs', group: 1, word: 'talk', transcription: 'tɔːk', translation: 'говорить, беседовать' },
  { theme: 'verbs', group: 1, word: 'turn', transcription: 'tɜːn', translation: 'поворачивать' },
  { theme: 'verbs', group: 1, word: 'start', transcription: 'stɑːt', translation: 'начинать' },
  { theme: 'verbs', group: 1, word: 'show', transcription: 'ʃəʊ', translation: 'показывать' },
  { theme: 'verbs', group: 1, word: 'hear', transcription: 'hɪə', translation: 'слышать' },
  { theme: 'verbs', group: 1, word: 'play', transcription: 'pleɪ', translation: 'играть' },
  { theme: 'verbs', group: 1, word: 'run', transcription: 'rʌn', translation: 'бегать, бежать' },
  { theme: 'verbs', group: 1, word: 'move', transcription: 'muːv', translation: 'двигать(ся)' },
  { theme: 'verbs', group: 1, word: 'like', transcription: 'laɪk', translation: 'нравиться, любить' },
  { theme: 'verbs', group: 1, word: 'live', transcription: 'lɪv', translation: 'жить' },
  { theme: 'verbs', group: 1, word: 'believe', transcription: 'bɪˈliːv', translation: 'верить' },
  { theme: 'verbs', group: 1, word: 'hold', transcription: 'həʊld', translation: 'держать' },
  { theme: 'verbs', group: 1, word: 'bring', transcription: 'brɪŋ', translation: 'приносить' },
  { theme: 'verbs', group: 1, word: 'happen', transcription: 'ˈhæpən', translation: 'случаться' },
  { theme: 'verbs', group: 1, word: 'write', transcription: 'raɪt', translation: 'писать' },
  { theme: 'verbs', group: 1, word: 'sit', transcription: 'sɪt', translation: 'сидеть' },
  { theme: 'verbs', group: 1, word: 'stand', transcription: 'stænd', translation: 'стоять' },
  { theme: 'verbs', group: 1, word: 'lose', transcription: 'luːz', translation: 'терять' },
  { theme: 'verbs', group: 1, word: 'pay', transcription: 'peɪ', translation: 'платить' },
  { theme: 'verbs', group: 1, word: 'meet', transcription: 'miːt', translation: 'встречать' },
  { theme: 'verbs', group: 1, word: 'include', transcription: 'ɪnˈkluːd', translation: 'включать' },
  { theme: 'verbs', group: 1, word: 'learn', transcription: 'lɜːn', translation: 'учить(ся)' },
  { theme: 'verbs', group: 1, word: 'change', transcription: 'tʃeɪndʒ', translation: 'менять(ся)' },
  { theme: 'verbs', group: 1, word: 'lead', transcription: 'liːd', translation: 'вести' },
  { theme: 'verbs', group: 1, word: 'understand', transcription: 'ˌʌndəˈstænd', translation: 'понимать' },
  { theme: 'verbs', group: 1, word: 'watch', transcription: 'wɒtʃ', translation: 'смотреть' },
  { theme: 'verbs', group: 1, word: 'follow', transcription: 'ˈfɒləʊ', translation: 'следовать' },
  { theme: 'verbs', group: 1, word: 'stop', transcription: 'stɒp', translation: 'останавливать(ся)' },
  { theme: 'verbs', group: 1, word: 'speak', transcription: 'spiːk', translation: 'говорить (на языке)' },
  { theme: 'verbs', group: 1, word: 'read', transcription: 'riːd', translation: 'читать' },
  { theme: 'verbs', group: 1, word: 'eat', transcription: 'iːt', translation: 'есть, кушать' },
  { theme: 'verbs', group: 1, word: 'drink', transcription: 'drɪŋk', translation: 'пить' },
  { theme: 'verbs', group: 1, word: 'sleep', transcription: 'sliːp', translation: 'спать' },
  { theme: 'verbs', group: 1, word: 'walk', transcription: 'wɔːk', translation: 'гулять, идти пешком' },
  { theme: 'verbs', group: 1, word: 'open', transcription: 'ˈəʊpən', translation: 'открывать' },
  { theme: 'verbs', group: 1, word: 'close', transcription: 'kləʊz', translation: 'закрывать' },
  { theme: 'verbs', group: 1, word: 'love', transcription: 'lʌv', translation: 'любить' },
  { theme: 'verbs', group: 1, word: 'buy', transcription: 'baɪ', translation: 'покупать' },
  { theme: 'verbs', group: 1, word: 'sell', transcription: 'sel', translation: 'продавать' },
  { theme: 'verbs', group: 1, word: 'teach', transcription: 'tiːtʃ', translation: 'учить, преподавать' },
  { theme: 'verbs', group: 1, word: 'study', transcription: 'ˈstʌdi', translation: 'учить, изучать' },
  { theme: 'verbs', group: 1, word: 'travel', transcription: 'ˈtrævl', translation: 'путешествовать' },
  { theme: 'verbs', group: 1, word: 'drive', transcription: 'draɪv', translation: 'водить (машину)' },
  { theme: 'verbs', group: 1, word: 'fly', transcription: 'flaɪ', translation: 'летать' },
  { theme: 'verbs', group: 1, word: 'swim', transcription: 'swɪm', translation: 'плавать' },
  { theme: 'verbs', group: 1, word: 'sing', transcription: 'sɪŋ', translation: 'петь' },
  { theme: 'verbs', group: 1, word: 'cook', transcription: 'kʊk', translation: 'готовить (еду)' },
  { theme: 'verbs', group: 1, word: 'build', transcription: 'bɪld', translation: 'строить' },
  { theme: 'verbs', group: 1, word: 'catch', transcription: 'kætʃ', translation: 'ловить' },
  { theme: 'verbs', group: 1, word: 'grow', transcription: 'ɡrəʊ', translation: 'расти, выращивать' },
  { theme: 'verbs', group: 1, word: 'cut', transcription: 'kʌt', translation: 'резать' },
  { theme: 'verbs', group: 1, word: 'fall', transcription: 'fɔːl', translation: 'падать' },
  { theme: 'verbs', group: 1, word: 'forget', transcription: 'fəˈɡet', translation: 'забывать' },
  { theme: 'verbs', group: 1, word: 'remember', transcription: 'rɪˈmembə', translation: 'помнить' },

  // ---------- Тема: Время (time) ----------
  // sub: 'digital' — перевод 24-часового времени в 12-часовой формат (и обратно);
  //      'mech' — чтение аналогового (механического) циферблата словами.
  { theme: 'time', sub: 'digital', word: '14:00', transcription: 'fourteen o’clock', translation: '2 часа дня (PM)' },
  { theme: 'time', sub: 'digital', word: '15:30', transcription: 'three thirty p.m.', translation: '3 часа 30 минут дня' },
  { theme: 'time', sub: 'digital', word: '18:45', transcription: 'six forty-five p.m.', translation: '6 часов 45 минут вечера' },
  { theme: 'time', sub: 'digital', word: '20:15', transcription: 'eight fifteen p.m.', translation: '8 часов 15 минут вечера' },
  { theme: 'time', sub: 'digital', word: '22:00', transcription: 'ten p.m.', translation: '10 часов вечера' },
  { theme: 'time', sub: 'digital', word: '23:59', transcription: 'eleven fifty-nine p.m.', translation: '11 часов 59 минут ночи' },
  { theme: 'time', sub: 'digital', word: '00:00', transcription: 'twelve midnight', translation: 'полночь (12:00)' },
  { theme: 'time', sub: 'digital', word: '09:00', transcription: 'nine a.m.', translation: '9 часов утра' },
  { theme: 'time', sub: 'digital', word: '12:00', transcription: 'twelve noon', translation: 'полдень (12:00)' },
  { theme: 'time', sub: 'digital', word: '13:00', transcription: 'one p.m.', translation: '1 час дня' },
  { theme: 'time', sub: 'digital', word: '16:20', transcription: 'four twenty p.m.', translation: '4 часа 20 минут дня' },
  { theme: 'time', sub: 'digital', word: '19:05', transcription: 'seven oh five p.m.', translation: '7 часов 05 минут вечера' },
  { theme: 'time', sub: 'digital', word: '21:40', transcription: 'nine forty p.m.', translation: '9 часов 40 минут вечера' },
  { theme: 'time', sub: 'digital', word: '07:30', transcription: 'seven thirty a.m.', translation: '7 часов 30 минут утра' },
  { theme: 'time', sub: 'digital', word: '11:15', transcription: 'eleven fifteen a.m.', translation: '11 часов 15 минут утра' },
  { theme: 'time', sub: 'digital', word: '17:50', transcription: 'five fifty p.m.', translation: '5 часов 50 минут вечера' },
  { theme: 'time', sub: 'digital', word: '08:45', transcription: 'eight forty-five a.m.', translation: '8 часов 45 минут утра' },
  { theme: 'time', sub: 'digital', word: '10:10', transcription: 'ten ten a.m.', translation: '10 часов 10 минут утра' },
  { theme: 'time', sub: 'digital', word: '06:00', transcription: 'six a.m.', translation: '6 часов утра' },
  { theme: 'time', sub: 'digital', word: '04:30', transcription: 'four thirty a.m.', translation: '4 часа 30 минут утра' },
  { theme: 'time', sub: 'digital', word: '2 часа дня', transcription: 'two p.m.', translation: '14:00' },
  { theme: 'time', sub: 'digital', word: 'полдень', transcription: 'twelve noon', translation: '12:00' },
  { theme: 'time', sub: 'digital', word: 'полночь', transcription: 'twelve midnight', translation: '00:00' },
  { theme: 'time', sub: 'digital', word: '7 часов вечера', transcription: 'seven p.m.', translation: '19:00' },
  { theme: 'time', sub: 'digital', word: '9 часов утра', transcription: 'nine a.m.', translation: '09:00' },
  { theme: 'time', sub: 'digital', word: '11 часов ночи', transcription: 'eleven p.m.', translation: '23:00' },

  { theme: 'time', sub: 'mech', word: 'Без пяти минут три', transcription: 'quarter to three', translation: '2:55' },
  { theme: 'time', sub: 'mech', word: 'Без четверти три', transcription: 'quarter to three', translation: '2:45' },
  { theme: 'time', sub: 'mech', word: 'Четверть третьего', transcription: 'quarter past two', translation: '2:15' },
  { theme: 'time', sub: 'mech', word: 'Половина третьего', transcription: 'half past two', translation: '2:30' },
  { theme: 'time', sub: 'mech', word: 'Без двадцати три', transcription: 'twenty to three', translation: '2:40' },
  { theme: 'time', sub: 'mech', word: 'Пять минут третьего', transcription: 'five past two', translation: '2:05' },
  { theme: 'time', sub: 'mech', word: 'Ровно три', transcription: 'three o’clock', translation: '3:00' },
  { theme: 'time', sub: 'mech', word: 'Десять минут четвёртого', transcription: 'ten past three', translation: '3:10' },
  { theme: 'time', sub: 'mech', word: 'Без десяти четыре', transcription: 'ten to four', translation: '3:50' },
  { theme: 'time', sub: 'mech', word: 'Четверть пятого', transcription: 'quarter past four', translation: '4:15' },
  { theme: 'time', sub: 'mech', word: 'Половина шестого', transcription: 'half past five', translation: '5:30' },
  { theme: 'time', sub: 'mech', word: 'Без четверти семь', transcription: 'quarter to seven', translation: '6:45' },
  { theme: 'time', sub: 'mech', word: 'Двадцать минут восьмого', transcription: 'twenty past seven', translation: '7:20' },
  { theme: 'time', sub: 'mech', word: 'Четверть первого', transcription: 'quarter past twelve', translation: '12:15' },
  { theme: 'time', sub: 'mech', word: 'Половина второго', transcription: 'half past one', translation: '1:30' },
  { theme: 'time', sub: 'mech', word: 'Без пятнадцати два', transcription: 'quarter to two', translation: '1:45' },
  { theme: 'time', sub: 'mech', word: 'Десять минут третьего', transcription: 'ten past two', translation: '2:10' },
  { theme: 'time', sub: 'mech', word: 'Пятнадцать минут одиннадцатого', transcription: 'quarter past ten', translation: '10:15' },
  { theme: 'time', sub: 'mech', word: 'Ровно семь', transcription: 'seven o’clock', translation: '7:00' },
  { theme: 'time', sub: 'mech', word: 'Двадцать пять минут десятого', transcription: 'twenty-five past nine', translation: '9:25' },
  { theme: 'time', sub: 'mech', word: 'Без десяти шесть', transcription: 'ten to six', translation: '5:50' },
  { theme: 'time', sub: 'mech', word: 'Пять минут первого', transcription: 'five past twelve', translation: '12:05' },
  { theme: 'time', sub: 'mech', word: 'Ровно двенадцать', transcription: 'twelve o’clock', translation: '12:00' },
  { theme: 'time', sub: 'mech', word: 'Без двадцати пять', transcription: 'twenty to five', translation: '4:40' },
  { theme: 'time', sub: 'mech', word: 'Двадцать минут второго', transcription: 'twenty past one', translation: '1:20' },
  { theme: 'time', sub: 'mech', word: 'Половина десятого', transcription: 'half past nine', translation: '9:30' },
];
