// cards/cards_flash.js — данные для игры «Флеш карты» (games/kids-flash.js).
// FLASH_THEMES — список тем.
// FLASH_WORDS — карточки: { theme, group, word, transcription, translation }.
//   group — размер пула, в который входит карточка (для темы 'english'):
//   в подборку "100 слов" входят карточки group<=100 (100 базовых слов),
//   в подборку "250 слов" — group>100 (250 слов — те же 150 с intermediate +
//   100 новых, не пересекающихся с базовыми 100). Для других тем (например,
//   'animals') поле group не влияет на выборку — берутся все карточки темы.

const FLASH_THEMES = [
  { id: 'english', icon: '🇬🇧', name: 'Английский язык' },
  { id: 'animals', icon: '🐾', name: 'Животные' },
  { id: 'verbs', icon: '🔤', name: 'Глаголы' },
];

const FLASH_WORDS = [
  { theme: 'english', group: 100, word: 'the', transcription: 'ðə', translation: 'определённый артикль' },
  { theme: 'english', group: 100, word: 'a', transcription: 'ə', translation: 'неопределённый артикль' },
  { theme: 'english', group: 100, word: 'I', transcription: 'aɪ', translation: 'я' },
  { theme: 'english', group: 100, word: 'you', transcription: 'juː', translation: 'ты, вы' },
  { theme: 'english', group: 100, word: 'he', transcription: 'hiː', translation: 'он' },
  { theme: 'english', group: 100, word: 'she', transcription: 'ʃiː', translation: 'она' },
  { theme: 'english', group: 100, word: 'it', transcription: 'ɪt', translation: 'он/она/оно (неодуш.)' },
  { theme: 'english', group: 100, word: 'we', transcription: 'wiː', translation: 'мы' },
  { theme: 'english', group: 100, word: 'they', transcription: 'ðeɪ', translation: 'они' },
  { theme: 'english', group: 100, word: 'is', transcription: 'ɪz', translation: 'есть (он/она/оно)' },
  { theme: 'english', group: 100, word: 'am', transcription: 'æm', translation: 'есть (я)' },
  { theme: 'english', group: 100, word: 'are', transcription: 'ɑːr', translation: 'есть (ты/мы/они)' },
  { theme: 'english', group: 100, word: 'was', transcription: 'wɒz', translation: 'был, была, было' },
  { theme: 'english', group: 100, word: 'were', transcription: 'wɜːr', translation: 'были' },
  { theme: 'english', group: 100, word: 'be', transcription: 'biː', translation: 'быть' },
  { theme: 'english', group: 100, word: 'have', transcription: 'hæv', translation: 'иметь' },
  { theme: 'english', group: 100, word: 'has', transcription: 'hæz', translation: 'имеет' },
  { theme: 'english', group: 100, word: 'do', transcription: 'duː', translation: 'делать' },
  { theme: 'english', group: 100, word: 'does', transcription: 'dʌz', translation: 'делает' },
  { theme: 'english', group: 100, word: 'go', transcription: 'ɡəʊ', translation: 'идти' },
  { theme: 'english', group: 100, word: 'yes', transcription: 'jes', translation: 'да' },
  { theme: 'english', group: 100, word: 'no', transcription: 'nəʊ', translation: 'нет' },
  { theme: 'english', group: 100, word: 'and', transcription: 'ænd', translation: 'и' },
  { theme: 'english', group: 100, word: 'or', transcription: 'ɔːr', translation: 'или' },
  { theme: 'english', group: 100, word: 'but', transcription: 'bʌt', translation: 'но' },
  { theme: 'english', group: 100, word: 'not', transcription: 'nɒt', translation: 'не' },
  { theme: 'english', group: 100, word: 'this', transcription: 'ðɪs', translation: 'это, этот' },
  { theme: 'english', group: 100, word: 'that', transcription: 'ðæt', translation: 'то, тот' },
  { theme: 'english', group: 100, word: 'these', transcription: 'ðiːz', translation: 'эти' },
  { theme: 'english', group: 100, word: 'those', transcription: 'ðəʊz', translation: 'те' },
  { theme: 'english', group: 100, word: 'what', transcription: 'wɒt', translation: 'что' },
  { theme: 'english', group: 100, word: 'who', transcription: 'huː', translation: 'кто' },
  { theme: 'english', group: 100, word: 'where', transcription: 'weər', translation: 'где' },
  { theme: 'english', group: 100, word: 'when', transcription: 'wen', translation: 'когда' },
  { theme: 'english', group: 100, word: 'why', transcription: 'waɪ', translation: 'почему' },
  { theme: 'english', group: 100, word: 'how', transcription: 'haʊ', translation: 'как' },
  { theme: 'english', group: 100, word: 'my', transcription: 'maɪ', translation: 'мой' },
  { theme: 'english', group: 100, word: 'your', transcription: 'jɔːr', translation: 'твой' },
  { theme: 'english', group: 100, word: 'his', transcription: 'hɪz', translation: 'его' },
  { theme: 'english', group: 100, word: 'her', transcription: 'hɜːr', translation: 'её' },
  { theme: 'english', group: 100, word: 'our', transcription: 'aʊər', translation: 'наш' },
  { theme: 'english', group: 100, word: 'their', transcription: 'ðeər', translation: 'их' },
  { theme: 'english', group: 100, word: 'name', transcription: 'neɪm', translation: 'имя' },
  { theme: 'english', group: 100, word: 'house', transcription: 'haʊs', translation: 'дом' },
  { theme: 'english', group: 100, word: 'water', transcription: 'ˈwɔːtər', translation: 'вода' },
  { theme: 'english', group: 100, word: 'food', transcription: 'fuːd', translation: 'еда' },
  { theme: 'english', group: 100, word: 'day', transcription: 'deɪ', translation: 'день' },
  { theme: 'english', group: 100, word: 'night', transcription: 'naɪt', translation: 'ночь' },
  { theme: 'english', group: 100, word: 'time', transcription: 'taɪm', translation: 'время' },
  { theme: 'english', group: 100, word: 'year', transcription: 'jɪər', translation: 'год' },
  { theme: 'english', group: 100, word: 'man', transcription: 'mæn', translation: 'мужчина' },
  { theme: 'english', group: 100, word: 'woman', transcription: 'ˈwʊmən', translation: 'женщина' },
  { theme: 'english', group: 100, word: 'child', transcription: 'tʃaɪld', translation: 'ребёнок' },
  { theme: 'english', group: 100, word: 'friend', transcription: 'frend', translation: 'друг' },
  { theme: 'english', group: 100, word: 'family', transcription: 'ˈfæməli', translation: 'семья' },
  { theme: 'english', group: 100, word: 'school', transcription: 'skuːl', translation: 'школа' },
  { theme: 'english', group: 100, word: 'work', transcription: 'wɜːrk', translation: 'работа' },
  { theme: 'english', group: 100, word: 'book', transcription: 'bʊk', translation: 'книга' },
  { theme: 'english', group: 100, word: 'table', transcription: 'ˈteɪbl', translation: 'стол' },
  { theme: 'english', group: 100, word: 'chair', transcription: 'tʃeər', translation: 'стул' },
  { theme: 'english', group: 100, word: 'door', transcription: 'dɔːr', translation: 'дверь' },
  { theme: 'english', group: 100, word: 'window', transcription: 'ˈwɪndəʊ', translation: 'окно' },
  { theme: 'english', group: 100, word: 'car', transcription: 'kɑːr', translation: 'машина' },
  { theme: 'english', group: 100, word: 'city', transcription: 'ˈsɪti', translation: 'город' },
  { theme: 'english', group: 100, word: 'country', transcription: 'ˈkʌntri', translation: 'страна' },
  { theme: 'english', group: 100, word: 'street', transcription: 'striːt', translation: 'улица' },
  { theme: 'english', group: 100, word: 'money', transcription: 'ˈmʌni', translation: 'деньги' },
  { theme: 'english', group: 100, word: 'love', transcription: 'lʌv', translation: 'любовь' },
  { theme: 'english', group: 100, word: 'happy', transcription: 'ˈhæpi', translation: 'счастливый' },
  { theme: 'english', group: 100, word: 'sad', transcription: 'sæd', translation: 'грустный' },
  { theme: 'english', group: 100, word: 'big', transcription: 'bɪɡ', translation: 'большой' },
  { theme: 'english', group: 100, word: 'small', transcription: 'smɔːl', translation: 'маленький' },
  { theme: 'english', group: 100, word: 'good', transcription: 'ɡʊd', translation: 'хороший' },
  { theme: 'english', group: 100, word: 'bad', transcription: 'bæd', translation: 'плохой' },
  { theme: 'english', group: 100, word: 'new', transcription: 'njuː', translation: 'новый' },
  { theme: 'english', group: 100, word: 'old', transcription: 'əʊld', translation: 'старый' },
  { theme: 'english', group: 100, word: 'hot', transcription: 'hɒt', translation: 'горячий' },
  { theme: 'english', group: 100, word: 'cold', transcription: 'kəʊld', translation: 'холодный' },
  { theme: 'english', group: 100, word: 'one', transcription: 'wʌn', translation: 'один' },
  { theme: 'english', group: 100, word: 'two', transcription: 'tuː', translation: 'два' },
  { theme: 'english', group: 100, word: 'three', transcription: 'θriː', translation: 'три' },
  { theme: 'english', group: 100, word: 'four', transcription: 'fɔːr', translation: 'четыре' },
  { theme: 'english', group: 100, word: 'five', transcription: 'faɪv', translation: 'пять' },
  { theme: 'english', group: 100, word: 'six', transcription: 'sɪks', translation: 'шесть' },
  { theme: 'english', group: 100, word: 'seven', transcription: 'ˈsevən', translation: 'семь' },
  { theme: 'english', group: 100, word: 'eight', transcription: 'eɪt', translation: 'восемь' },
  { theme: 'english', group: 100, word: 'nine', transcription: 'naɪn', translation: 'девять' },
  { theme: 'english', group: 100, word: 'ten', transcription: 'ten', translation: 'десять' },
  { theme: 'english', group: 100, word: 'hello', transcription: 'həˈləʊ', translation: 'привет' },
  { theme: 'english', group: 100, word: 'goodbye', transcription: 'ˌɡʊdˈbaɪ', translation: 'до свидания' },
  { theme: 'english', group: 100, word: 'please', transcription: 'pliːz', translation: 'пожалуйста' },
  { theme: 'english', group: 100, word: 'thanks', transcription: 'θæŋks', translation: 'спасибо' },
  { theme: 'english', group: 100, word: 'sorry', transcription: 'ˈsɒri', translation: 'извини' },
  { theme: 'english', group: 100, word: 'eat', transcription: 'iːt', translation: 'есть, кушать' },
  { theme: 'english', group: 100, word: 'drink', transcription: 'drɪŋk', translation: 'пить' },
  { theme: 'english', group: 100, word: 'sleep', transcription: 'sliːp', translation: 'спать' },
  { theme: 'english', group: 100, word: 'run', transcription: 'rʌn', translation: 'бежать' },
  { theme: 'english', group: 100, word: 'walk', transcription: 'wɔːk', translation: 'идти пешком' },
  { theme: 'english', group: 100, word: 'see', transcription: 'siː', translation: 'видеть' },
  { theme: 'english', group: 100, word: 'know', transcription: 'nəʊ', translation: 'знать' },
  { theme: 'english', group: 250, word: 'want', transcription: 'wɒnt', translation: 'хотеть' },
  { theme: 'english', group: 250, word: 'need', transcription: 'niːd', translation: 'нуждаться' },
  { theme: 'english', group: 250, word: 'like', transcription: 'laɪk', translation: 'нравиться' },
  { theme: 'english', group: 250, word: 'think', transcription: 'θɪŋk', translation: 'думать' },
  { theme: 'english', group: 250, word: 'say', transcription: 'seɪ', translation: 'говорить, сказать' },
  { theme: 'english', group: 250, word: 'tell', transcription: 'tel', translation: 'рассказать' },
  { theme: 'english', group: 250, word: 'speak', transcription: 'spiːk', translation: 'говорить' },
  { theme: 'english', group: 250, word: 'talk', transcription: 'tɔːk', translation: 'разговаривать' },
  { theme: 'english', group: 250, word: 'ask', transcription: 'ɑːsk', translation: 'спрашивать' },
  { theme: 'english', group: 250, word: 'answer', transcription: 'ˈɑːnsər', translation: 'отвечать' },
  { theme: 'english', group: 250, word: 'read', transcription: 'riːd', translation: 'читать' },
  { theme: 'english', group: 250, word: 'write', transcription: 'raɪt', translation: 'писать' },
  { theme: 'english', group: 250, word: 'listen', transcription: 'ˈlɪsən', translation: 'слушать' },
  { theme: 'english', group: 250, word: 'hear', transcription: 'hɪər', translation: 'слышать' },
  { theme: 'english', group: 250, word: 'look', transcription: 'lʊk', translation: 'смотреть' },
  { theme: 'english', group: 250, word: 'watch', transcription: 'wɒtʃ', translation: 'наблюдать' },
  { theme: 'english', group: 250, word: 'play', transcription: 'pleɪ', translation: 'играть' },
  { theme: 'english', group: 250, word: 'help', transcription: 'help', translation: 'помогать' },
  { theme: 'english', group: 250, word: 'give', transcription: 'ɡɪv', translation: 'давать' },
  { theme: 'english', group: 250, word: 'take', transcription: 'teɪk', translation: 'брать' },
  { theme: 'english', group: 250, word: 'get', transcription: 'ɡet', translation: 'получать' },
  { theme: 'english', group: 250, word: 'make', transcription: 'meɪk', translation: 'делать, создавать' },
  { theme: 'english', group: 250, word: 'put', transcription: 'pʊt', translation: 'класть' },
  { theme: 'english', group: 250, word: 'find', transcription: 'faɪnd', translation: 'находить' },
  { theme: 'english', group: 250, word: 'lose', transcription: 'luːz', translation: 'терять' },
  { theme: 'english', group: 250, word: 'buy', transcription: 'baɪ', translation: 'покупать' },
  { theme: 'english', group: 250, word: 'sell', transcription: 'sel', translation: 'продавать' },
  { theme: 'english', group: 250, word: 'pay', transcription: 'peɪ', translation: 'платить' },
  { theme: 'english', group: 250, word: 'open', transcription: 'ˈəʊpən', translation: 'открывать' },
  { theme: 'english', group: 250, word: 'close', transcription: 'kləʊz', translation: 'закрывать' },
  { theme: 'english', group: 250, word: 'start', transcription: 'stɑːrt', translation: 'начинать' },
  { theme: 'english', group: 250, word: 'stop', transcription: 'stɒp', translation: 'останавливать' },
  { theme: 'english', group: 250, word: 'finish', transcription: 'ˈfɪnɪʃ', translation: 'заканчивать' },
  { theme: 'english', group: 250, word: 'wait', transcription: 'weɪt', translation: 'ждать' },
  { theme: 'english', group: 250, word: 'live', transcription: 'lɪv', translation: 'жить' },
  { theme: 'english', group: 250, word: 'die', transcription: 'daɪ', translation: 'умирать' },
  { theme: 'english', group: 250, word: 'born', transcription: 'bɔːrn', translation: 'рождённый' },
  { theme: 'english', group: 250, word: 'grow', transcription: 'ɡrəʊ', translation: 'расти' },
  { theme: 'english', group: 250, word: 'change', transcription: 'tʃeɪndʒ', translation: 'менять' },
  { theme: 'english', group: 250, word: 'move', transcription: 'muːv', translation: 'двигаться' },
  { theme: 'english', group: 250, word: 'stay', transcription: 'steɪ', translation: 'оставаться' },
  { theme: 'english', group: 250, word: 'leave', transcription: 'liːv', translation: 'уходить' },
  { theme: 'english', group: 250, word: 'arrive', transcription: 'əˈraɪv', translation: 'прибывать' },
  { theme: 'english', group: 250, word: 'come', transcription: 'kʌm', translation: 'приходить' },
  { theme: 'english', group: 250, word: 'bring', transcription: 'brɪŋ', translation: 'приносить' },
  { theme: 'english', group: 250, word: 'send', transcription: 'send', translation: 'отправлять' },
  { theme: 'english', group: 250, word: 'use', transcription: 'juːz', translation: 'использовать' },
  { theme: 'english', group: 250, word: 'try', transcription: 'traɪ', translation: 'пытаться' },
  { theme: 'english', group: 250, word: 'learn', transcription: 'lɜːrn', translation: 'учить, учиться' },
  { theme: 'english', group: 250, word: 'teach', transcription: 'tiːtʃ', translation: 'обучать' },
  { theme: 'english', group: 250, word: 'study', transcription: 'ˈstʌdi', translation: 'изучать' },
  { theme: 'english', group: 250, word: 'remember', transcription: 'rɪˈmembər', translation: 'помнить' },
  { theme: 'english', group: 250, word: 'forget', transcription: 'fərˈɡet', translation: 'забывать' },
  { theme: 'english', group: 250, word: 'understand', transcription: 'ˌʌndərˈstænd', translation: 'понимать' },
  { theme: 'english', group: 250, word: 'believe', transcription: 'bɪˈliːv', translation: 'верить' },
  { theme: 'english', group: 250, word: 'hope', transcription: 'həʊp', translation: 'надеяться' },
  { theme: 'english', group: 250, word: 'feel', transcription: 'fiːl', translation: 'чувствовать' },
  { theme: 'english', group: 250, word: 'wish', transcription: 'wɪʃ', translation: 'желать' },
  { theme: 'english', group: 250, word: 'dream', transcription: 'driːm', translation: 'мечтать' },
  { theme: 'english', group: 250, word: 'laugh', transcription: 'lɑːf', translation: 'смеяться' },
  { theme: 'english', group: 250, word: 'cry', transcription: 'kraɪ', translation: 'плакать' },
  { theme: 'english', group: 250, word: 'smile', transcription: 'smaɪl', translation: 'улыбаться' },
  { theme: 'english', group: 250, word: 'shout', transcription: 'ʃaʊt', translation: 'кричать' },
  { theme: 'english', group: 250, word: 'sing', transcription: 'sɪŋ', translation: 'петь' },
  { theme: 'english', group: 250, word: 'dance', transcription: 'dɑːns', translation: 'танцевать' },
  { theme: 'english', group: 250, word: 'cook', transcription: 'kʊk', translation: 'готовить' },
  { theme: 'english', group: 250, word: 'clean', transcription: 'kliːn', translation: 'убирать' },
  { theme: 'english', group: 250, word: 'wash', transcription: 'wɒʃ', translation: 'мыть' },
  { theme: 'english', group: 250, word: 'build', transcription: 'bɪld', translation: 'строить' },
  { theme: 'english', group: 250, word: 'break', transcription: 'breɪk', translation: 'ломать' },
  { theme: 'english', group: 250, word: 'fix', transcription: 'fɪks', translation: 'чинить' },
  { theme: 'english', group: 250, word: 'push', transcription: 'pʊʃ', translation: 'толкать' },
  { theme: 'english', group: 250, word: 'pull', transcription: 'pʊl', translation: 'тянуть' },
  { theme: 'english', group: 250, word: 'carry', transcription: 'ˈkæri', translation: 'нести' },
  { theme: 'english', group: 250, word: 'hold', transcription: 'həʊld', translation: 'держать' },
  { theme: 'english', group: 250, word: 'touch', transcription: 'tʌtʃ', translation: 'трогать' },
  { theme: 'english', group: 250, word: 'kiss', transcription: 'kɪs', translation: 'целовать' },
  { theme: 'english', group: 250, word: 'hug', transcription: 'hʌɡ', translation: 'обнимать' },
  { theme: 'english', group: 250, word: 'meet', transcription: 'miːt', translation: 'встречать' },
  { theme: 'english', group: 250, word: 'visit', transcription: 'ˈvɪzɪt', translation: 'посещать' },
  { theme: 'english', group: 250, word: 'travel', transcription: 'ˈtrævəl', translation: 'путешествовать' },
  { theme: 'english', group: 250, word: 'fly', transcription: 'flaɪ', translation: 'летать' },
  { theme: 'english', group: 250, word: 'drive', transcription: 'draɪv', translation: 'водить машину' },
  { theme: 'english', group: 250, word: 'ride', transcription: 'raɪd', translation: 'кататься' },
  { theme: 'english', group: 250, word: 'swim', transcription: 'swɪm', translation: 'плавать' },
  { theme: 'english', group: 250, word: 'jump', transcription: 'dʒʌmp', translation: 'прыгать' },
  { theme: 'english', group: 250, word: 'sit', transcription: 'sɪt', translation: 'сидеть' },
  { theme: 'english', group: 250, word: 'stand', transcription: 'stænd', translation: 'стоять' },
  { theme: 'english', group: 250, word: 'wake', transcription: 'weɪk', translation: 'просыпаться' },
  { theme: 'english', group: 250, word: 'wear', transcription: 'weər', translation: 'носить (одежду)' },
  { theme: 'english', group: 250, word: 'shop', transcription: 'ʃɒp', translation: 'магазин, делать покупки' },
  { theme: 'english', group: 250, word: 'spend', transcription: 'spend', translation: 'тратить' },
  { theme: 'english', group: 250, word: 'save', transcription: 'seɪv', translation: 'сохранять, копить' },
  { theme: 'english', group: 250, word: 'cost', transcription: 'kɒst', translation: 'стоить' },
  { theme: 'english', group: 250, word: 'cheap', transcription: 'tʃiːp', translation: 'дешёвый' },
  { theme: 'english', group: 250, word: 'expensive', transcription: 'ɪkˈspensɪv', translation: 'дорогой' },
  { theme: 'english', group: 250, word: 'easy', transcription: 'ˈiːzi', translation: 'лёгкий' },
  { theme: 'english', group: 250, word: 'difficult', transcription: 'ˈdɪfɪkəlt', translation: 'трудный' },
  { theme: 'english', group: 250, word: 'important', transcription: 'ɪmˈpɔːrtənt', translation: 'важный' },
  { theme: 'english', group: 250, word: 'beautiful', transcription: 'ˈbjuːtɪfl', translation: 'красивый' },
  { theme: 'english', group: 250, word: 'ugly', transcription: 'ˈʌɡli', translation: 'некрасивый' },
  { theme: 'english', group: 250, word: 'strong', transcription: 'strɒŋ', translation: 'сильный' },
  { theme: 'english', group: 250, word: 'weak', transcription: 'wiːk', translation: 'слабый' },
  { theme: 'english', group: 250, word: 'fast', transcription: 'fɑːst', translation: 'быстрый' },
  { theme: 'english', group: 250, word: 'slow', transcription: 'sləʊ', translation: 'медленный' },
  { theme: 'english', group: 250, word: 'early', transcription: 'ˈɜːrli', translation: 'ранний' },
  { theme: 'english', group: 250, word: 'late', transcription: 'leɪt', translation: 'поздний' },
  { theme: 'english', group: 250, word: 'near', transcription: 'nɪər', translation: 'близко' },
  { theme: 'english', group: 250, word: 'far', transcription: 'fɑːr', translation: 'далеко' },
  { theme: 'english', group: 250, word: 'high', transcription: 'haɪ', translation: 'высокий' },
  { theme: 'english', group: 250, word: 'low', transcription: 'ləʊ', translation: 'низкий' },
  { theme: 'english', group: 250, word: 'long', transcription: 'lɒŋ', translation: 'длинный' },
  { theme: 'english', group: 250, word: 'short', transcription: 'ʃɔːrt', translation: 'короткий' },
  { theme: 'english', group: 250, word: 'wide', transcription: 'waɪd', translation: 'широкий' },
  { theme: 'english', group: 250, word: 'narrow', transcription: 'ˈnærəʊ', translation: 'узкий' },
  { theme: 'english', group: 250, word: 'full', transcription: 'fʊl', translation: 'полный' },
  { theme: 'english', group: 250, word: 'empty', transcription: 'ˈempti', translation: 'пустой' },
  { theme: 'english', group: 250, word: 'dirty', transcription: 'ˈdɜːrti', translation: 'грязный' },
  { theme: 'english', group: 250, word: 'quiet', transcription: 'ˈkwaɪət', translation: 'тихий' },
  { theme: 'english', group: 250, word: 'loud', transcription: 'laʊd', translation: 'громкий' },
  { theme: 'english', group: 250, word: 'dark', transcription: 'dɑːrk', translation: 'тёмный' },
  { theme: 'english', group: 250, word: 'light', transcription: 'laɪt', translation: 'светлый, лёгкий' },
  { theme: 'english', group: 250, word: 'soft', transcription: 'sɒft', translation: 'мягкий' },
  { theme: 'english', group: 250, word: 'hard', transcription: 'hɑːrd', translation: 'твёрдый, трудный' },
  { theme: 'english', group: 250, word: 'sweet', transcription: 'swiːt', translation: 'сладкий' },
  { theme: 'english', group: 250, word: 'bitter', transcription: 'ˈbɪtər', translation: 'горький' },
  { theme: 'english', group: 250, word: 'sour', transcription: 'ˈsaʊər', translation: 'кислый' },
  { theme: 'english', group: 250, word: 'salty', transcription: 'ˈsɔːlti', translation: 'солёный' },
  { theme: 'english', group: 250, word: 'spicy', transcription: 'ˈspaɪsi', translation: 'острый (о еде)' },
  { theme: 'english', group: 250, word: 'fresh', transcription: 'freʃ', translation: 'свежий' },
  { theme: 'english', group: 250, word: 'rich', transcription: 'rɪtʃ', translation: 'богатый' },
  { theme: 'english', group: 250, word: 'poor', transcription: 'pɔːr', translation: 'бедный' },
  { theme: 'english', group: 250, word: 'free', transcription: 'friː', translation: 'свободный, бесплатный' },
  { theme: 'english', group: 250, word: 'busy', transcription: 'ˈbɪzi', translation: 'занятой' },
  { theme: 'english', group: 250, word: 'tired', transcription: 'ˈtaɪərd', translation: 'уставший' },
  { theme: 'english', group: 250, word: 'hungry', transcription: 'ˈhʌŋɡri', translation: 'голодный' },
  { theme: 'english', group: 250, word: 'thirsty', transcription: 'ˈθɜːrsti', translation: 'испытывающий жажду' },
  { theme: 'english', group: 250, word: 'sick', transcription: 'sɪk', translation: 'больной' },
  { theme: 'english', group: 250, word: 'healthy', transcription: 'ˈhelθi', translation: 'здоровый' },
  { theme: 'english', group: 250, word: 'safe', transcription: 'seɪf', translation: 'безопасный' },
  { theme: 'english', group: 250, word: 'dangerous', transcription: 'ˈdeɪndʒərəs', translation: 'опасный' },
  { theme: 'english', group: 250, word: 'true', transcription: 'truː', translation: 'правдивый' },
  { theme: 'english', group: 250, word: 'false', transcription: 'fɔːls', translation: 'ложный' },
  { theme: 'english', group: 250, word: 'real', transcription: 'rɪəl', translation: 'настоящий' },
  { theme: 'english', group: 250, word: 'same', transcription: 'seɪm', translation: 'одинаковый' },
  { theme: 'english', group: 250, word: 'different', transcription: 'ˈdɪfrənt', translation: 'разный' },
  { theme: 'english', group: 250, word: 'right', transcription: 'raɪt', translation: 'правильный, правый' },
  { theme: 'english', group: 250, word: 'wrong', transcription: 'rɒŋ', translation: 'неправильный' },
  { theme: 'english', group: 250, word: 'today', transcription: 'təˈdeɪ', translation: 'сегодня' },
  { theme: 'english', group: 250, word: 'tomorrow', transcription: 'təˈmɒrəʊ', translation: 'завтра' },

  // ---------- 100 новых слов английского языка (группа 250, не пересекаются
  // с базовыми 100) ----------
  { theme: 'english', group: 250, word: 'abandon', transcription: 'əˈbændən', translation: 'покидать, оставлять' },
  { theme: 'english', group: 250, word: 'ability', transcription: 'əˈbɪləti', translation: 'способность' },
  { theme: 'english', group: 250, word: 'able', transcription: 'ˈeɪbl', translation: 'способный' },
  { theme: 'english', group: 250, word: 'abroad', transcription: 'əˈbrɔːd', translation: 'за границей' },
  { theme: 'english', group: 250, word: 'absent', transcription: 'ˈæbsənt', translation: 'отсутствующий' },
  { theme: 'english', group: 250, word: 'absolute', transcription: 'ˈæbsəluːt', translation: 'абсолутный' },
  { theme: 'english', group: 250, word: 'abstract', transcription: 'əbˈstrækt', translation: 'абстрактный' },
  { theme: 'english', group: 250, word: 'absurd', transcription: 'əbˈsɜːrd', translation: 'абсурдный' },
  { theme: 'english', group: 250, word: 'abuse', transcription: 'əˈbjuːs', translation: 'злоупотребление' },
  { theme: 'english', group: 250, word: 'access', transcription: 'ˈækses', translation: 'доступ' },
  { theme: 'english', group: 250, word: 'accident', transcription: 'ˈæksɪdənt', translation: 'несчастность' },
  { theme: 'english', group: 250, word: 'ache', transcription: 'eɪk', translation: 'боль, тошка' },
  { theme: 'english', group: 250, word: 'acquire', transcription: 'əˈkwaɪə', translation: 'получать' },
  { theme: 'english', group: 250, word: 'action', transcription: 'ˈækʃən', translation: 'действие' },
  { theme: 'english', group: 250, word: 'activity', transcription: 'ækˈtɪvəti', translation: 'активность' },
  { theme: 'english', group: 250, word: 'actor', transcription: 'ˈæktə', translation: 'актёр' },
  { theme: 'english', group: 250, word: 'actual', transcription: 'ˈæktʃuəl', translation: 'реальный' },
  { theme: 'english', group: 250, word: 'address', transcription: 'əˈdres', translation: 'адрес' },
  { theme: 'english', group: 250, word: 'admit', transcription: 'ədˈmɪt', translation: 'признавать' },
  { theme: 'english', group: 250, word: 'advance', transcription: 'ədˈvæns', translation: 'авансировать' },
  { theme: 'english', group: 250, word: 'afford', transcription: 'əˈfɔːrd', translation: 'позволять себе' },
  { theme: 'english', group: 250, word: 'alert', transcription: 'əˈlɜːrt', translation: 'тревога' },
  { theme: 'english', group: 250, word: 'alike', transcription: 'əˈlaɪk', translation: 'похожий' },
  { theme: 'english', group: 250, word: 'alive', transcription: 'əˈlaɪv', translation: 'живой' },
  { theme: 'english', group: 250, word: 'allow', transcription: 'əˈlaʊ', translation: 'разрешать' },
  { theme: 'english', group: 250, word: 'along', transcription: 'əˈlɒŋ', translation: 'вдоль' },
  { theme: 'english', group: 250, word: 'alter', transcription: 'ˈɔːltə', translation: 'менять' },
  { theme: 'english', group: 250, word: 'among', transcription: 'əˈmʌŋ', translation: 'среди' },
  { theme: 'english', group: 250, word: 'amount', transcription: 'əˈmaʊnt', translation: 'количество' },
  { theme: 'english', group: 250, word: 'ancient', transcription: 'ˈeɪnʃənt', translation: 'древний' },
  { theme: 'english', group: 250, word: 'angle', transcription: 'ˈæŋɡəl', translation: 'угол' },
  { theme: 'english', group: 250, word: 'angry', transcription: 'ˈæŋɡri', translation: 'серый' },
  { theme: 'english', group: 250, word: 'ankle', transcription: 'ˈæŋkəl', translation: 'лодыжка' },
  { theme: 'english', group: 250, word: 'annoy', transcription: 'əˈnɔɪ', translation: 'раздражать' },
  { theme: 'english', group: 250, word: 'annually', transcription: 'ˈjenjuəli', translation: 'ежегодно' },
  { theme: 'english', group: 250, word: 'anxiety', transcription: 'æŋˈzaɪəti', translation: 'тревога' },
  { theme: 'english', group: 250, word: 'anyone', transcription: 'ˈeniwʌn', translation: 'кто-либо' },
  { theme: 'english', group: 250, word: 'anything', transcription: 'ˈeniθɪŋ', translation: 'что-либо' },
  { theme: 'english', group: 250, word: 'anywhere', transcription: 'ˈenieweə', translation: 'где-либо' },
  { theme: 'english', group: 250, word: 'apology', transcription: 'əˈpɑːli', translation: 'извинение' },
  { theme: 'english', group: 250, word: 'apply', transcription: 'əˈplaɪ', translation: 'применять' },
  { theme: 'english', group: 250, word: 'approach', transcription: 'əˈprəʊtʃ', translation: 'приближение' },
  { theme: 'english', group: 250, word: 'approval', transcription: 'əˈpruːvəl', translation: 'одобрение' },
  { theme: 'english', group: 250, word: 'approve', transcription: 'əˈpruːv', translation: 'одобрять' },
  { theme: 'english', group: 250, word: 'apt', transcription: 'æpt', translation: 'уместный' },
  { theme: 'english', group: 250, word: 'architecture', transcription: 'ˈɑːktɪktʃə', translation: 'архитектура' },
  { theme: 'english', group: 250, word: 'argue', transcription: 'ˈɑːɡjuː', translation: 'спорить' },
  { theme: 'english', group: 250, word: 'arrest', transcription: 'əˈrest', translation: 'арестовывать' },
  { theme: 'english', group: 250, word: 'arrow', transcription: 'ˈæroʊ', translation: 'стрела' },
  { theme: 'english', group: 250, word: 'artist', transcription: 'ˈɑːrtɪst', translation: 'художник' },
  { theme: 'english', group: 250, word: 'ashtray', transcription: 'ˈæstreɪ', translation: 'подсовник' },
  { theme: 'english', group: 250, word: 'asleep', transcription: 'əˈsliːp', translation: 'спящий' },
  { theme: 'english', group: 250, word: 'attempt', transcription: 'əˈtɛmpt', translation: 'попытка' },
  { theme: 'english', group: 250, word: 'attract', transcription: 'əˈtrækt', translation: 'привлекать' },
  { theme: 'english', group: 250, word: 'available', transcription: 'əˈveɪləbl', translation: 'доступный' },
  { theme: 'english', group: 250, word: 'average', transcription: 'ˈævərɪdʒ', translation: 'в среднем' },
  { theme: 'english', group: 250, word: 'avoid', transcription: 'əˈvɔɪd', translation: 'избегать' },
  { theme: 'english', group: 250, word: 'award', transcription: 'əˈwɔːrd', translation: 'награда' },
  { theme: 'english', group: 250, word: 'aware', transcription: 'əˈweə', translation: 'осознающий' },
  { theme: 'english', group: 250, word: 'baby', transcription: 'ˈbeɪbi', translation: 'малыш' },
  { theme: 'english', group: 250, word: 'back', transcription: 'bæk', translation: 'назад' },
  { theme: 'english', group: 250, word: 'badly', transcription: 'ˈbædli', translation: 'плохо' },
  { theme: 'english', group: 250, word: 'baggage', transcription: 'ˈbæɡɪdʒ', translation: 'багаж' },
  { theme: 'english', group: 250, word: 'bake', transcription: 'beɪk', translation: 'пекать' },
  { theme: 'english', group: 250, word: 'ball', transcription: 'bɔːl', translation: 'мяч' },
  { theme: 'english', group: 250, word: 'band', transcription: 'bænd', translation: 'группа' },
  { theme: 'english', group: 250, word: 'bank', transcription: 'bæŋk', translation: 'банк' },
  { theme: 'english', group: 250, word: 'barbecue', transcription: 'bɑːrbɪkjuː', translation: 'барбекю' },
  { theme: 'english', group: 250, word: 'base', transcription: 'beɪs', translation: 'основа' },
  { theme: 'english', group: 250, word: 'basic', transcription: 'ˈbeɪsɪk', translation: 'базовый' },
  { theme: 'english', group: 250, word: 'basis', transcription: 'ˈbeɪsɪs', translation: 'основание' },
  { theme: 'english', group: 250, word: 'battle', transcription: 'ˈbætl', translation: 'сражение' },
  { theme: 'english', group: 250, word: 'bay', transcription: 'beɪ', translation: 'залив' },
  { theme: 'english', group: 250, word: 'beach', transcription: 'biːtʃ', translation: 'пляж' },
  { theme: 'english', group: 250, word: 'bead', transcription: 'biːd', translation: 'бусина' },
  { theme: 'english', group: 250, word: 'beam', transcription: 'biːm', translation: 'луч' },
  { theme: 'english', group: 250, word: 'bean', transcription: 'biːn', translation: 'боба' },
  { theme: 'english', group: 250, word: 'beat', transcription: 'biːt', translation: 'бить' },
  { theme: 'english', group: 250, word: 'beauty', transcription: 'ˈbjuːti', translation: 'красота' },
  { theme: 'english', group: 250, word: 'bed', transcription: 'bɛd', translation: 'кровать' },
  { theme: 'english', group: 250, word: 'before', transcription: 'bɪˈfɔː', translation: 'перед' },
  { theme: 'english', group: 250, word: 'behind', transcription: 'bɪˈhaɪnd', translation: 'за' },
  { theme: 'english', group: 250, word: 'bell', transcription: 'bɛl', translation: 'колокольчик' },
  { theme: 'english', group: 250, word: 'belt', transcription: 'bɛlt', translation: 'пояс' },
  { theme: 'english', group: 250, word: 'better', transcription: 'ˈbɛtər', translation: 'лучше' },
  { theme: 'english', group: 250, word: 'beyond', transcription: 'bɪˈjɒnd', translation: 'за пределами' },
  { theme: 'english', group: 250, word: 'bike', transcription: 'baɪk', translation: 'велосипед' },
  { theme: 'english', group: 250, word: 'bill', transcription: 'bɪl', translation: 'счёт' },
  { theme: 'english', group: 250, word: 'birth', transcription: 'bɜːθ', translation: 'рождение' },
  { theme: 'english', group: 250, word: 'black', transcription: 'blæk', translation: 'чёрный' },
  { theme: 'english', group: 250, word: 'blade', transcription: 'bleɪd', translation: 'лезвие' },
  { theme: 'english', group: 250, word: 'blanket', transcription: 'ˈblæŋkɪt', translation: 'одеяло' },
  { theme: 'english', group: 250, word: 'blind', transcription: 'blaɪnd', translation: 'слепой' },
  { theme: 'english', group: 250, word: 'block', transcription: 'blɒk', translation: 'блок' },
  { theme: 'english', group: 250, word: 'blood', transcription: 'blʌd', translation: 'кровь' },
  { theme: 'english', group: 250, word: 'blue', transcription: 'bluː', translation: 'синий' },
  { theme: 'english', group: 250, word: 'board', transcription: 'bɔːd', translation: 'доска' },
  { theme: 'english', group: 250, word: 'boat', transcription: 'bəʊt', translation: 'лодка' },
  { theme: 'english', group: 250, word: 'body', transcription: 'ˈbɒdi', translation: 'тело' },
  { theme: 'english', group: 250, word: 'boil', transcription: 'bɔɪl', translation: 'кипятить' },

  // ---------- Тема: Животные (animals) ----------
  { theme: 'animals', group: 1, word: 'cat', transcription: 'kæt', translation: 'кошка' },
  { theme: 'animals', group: 1, word: 'dog', transcription: 'dɒɡ', translation: 'собака' },
  { theme: 'animals', group: 1, word: 'cow', transcription: 'kaʊ', translation: 'корова' },
  { theme: 'animals', group: 1, word: 'pig', transcription: 'pɪɡ', translation: 'свинья' },
  { theme: 'animals', group: 1, word: 'sheep', transcription: 'ʃiːp', translation: 'овца' },
  { theme: 'animals', group: 1, word: 'goat', transcription: 'ɡəʊt', translation: 'коза' },
  { theme: 'animals', group: 1, word: 'horse', transcription: 'hɔːs', translation: 'лошадь' },
  { theme: 'animals', group: 1, word: 'donkey', transcription: 'ˈdɒŋki', translation: 'осёл' },
  { theme: 'animals', group: 1, word: 'rabbit', transcription: 'ˈræbɪt', translation: 'кролик' },
  { theme: 'animals', group: 1, word: 'mouse', transcription: 'maʊs', translation: 'мышь' },
  { theme: 'animals', group: 1, word: 'rat', transcription: 'ræt', translation: 'крыса' },
  { theme: 'animals', group: 1, word: 'hamster', transcription: 'ˈhæmstə', translation: 'хомяк' },
  { theme: 'animals', group: 1, word: 'guinea pig', transcription: 'ˈɡɪni pɪɡ', translation: 'морская свинка' },
  { theme: 'animals', group: 1, word: 'bird', transcription: 'bɜːd', translation: 'птица' },
  { theme: 'animals', group: 1, word: 'duck', transcription: 'dʌk', translation: 'утка' },
  { theme: 'animals', group: 1, word: 'chicken', transcription: 'ˈtʃɪkɪn', translation: 'курица' },
  { theme: 'animals', group: 1, word: 'goose', transcription: 'ɡuːs', translation: 'гусь' },
  { theme: 'animals', group: 1, word: 'turkey', transcription: 'ˈtɜːki', translation: 'индюк' },
  { theme: 'animals', group: 1, word: 'fish', transcription: 'fɪʃ', translation: 'рыба' },
  { theme: 'animals', group: 1, word: 'frog', transcription: 'frɒɡ', translation: 'лягушка' },
  { theme: 'animals', group: 1, word: 'turtle', transcription: 'ˈtɜːtl', translation: 'черепаха' },
  { theme: 'animals', group: 1, word: 'snake', transcription: 'sneɪk', translation: 'змея' },
  { theme: 'animals', group: 1, word: 'lizard', transcription: 'ˈlɪzəd', translation: 'ящерица' },
  { theme: 'animals', group: 1, word: 'crocodile', transcription: 'ˈkrɒkədaɪl', translation: 'крокодил' },
  { theme: 'animals', group: 1, word: 'bee', transcription: 'biː', translation: 'пчела' },
  { theme: 'animals', group: 1, word: 'butterfly', transcription: 'ˈbʌtəflaɪ', translation: 'бабочка' },
  { theme: 'animals', group: 1, word: 'spider', transcription: 'ˈspaɪdə', translation: 'паук' },
  { theme: 'animals', group: 1, word: 'ant', transcription: 'ænt', translation: 'муравей' },
  { theme: 'animals', group: 1, word: 'ladybug', transcription: 'ˈleɪdɪbʌɡ', translation: 'божья коровка' },
  { theme: 'animals', group: 1, word: 'bear', transcription: 'beə', translation: 'медведь' },
  { theme: 'animals', group: 1, word: 'wolf', transcription: 'wʊlf', translation: 'волк' },
  { theme: 'animals', group: 1, word: 'fox', transcription: 'fɒks', translation: 'лиса' },
  { theme: 'animals', group: 1, word: 'deer', transcription: 'dɪə', translation: 'олень' },
  { theme: 'animals', group: 1, word: 'hare', transcription: 'heə', translation: 'заяц' },
  { theme: 'animals', group: 1, word: 'squirrel', transcription: 'ˈskwɪrəl', translation: 'белка' },
  { theme: 'animals', group: 1, word: 'hedgehog', transcription: 'ˈhedʒhɒɡ', translation: 'ёж' },
  { theme: 'animals', group: 1, word: 'lion', transcription: 'ˈlaɪən', translation: 'лев' },
  { theme: 'animals', group: 1, word: 'tiger', transcription: 'ˈtaɪɡə', translation: 'тигр' },
  { theme: 'animals', group: 1, word: 'elephant', transcription: 'ˈelɪfənt', translation: 'слон' },
  { theme: 'animals', group: 1, word: 'giraffe', transcription: 'dʒɪˈrɑːf', translation: 'жираф' },
  { theme: 'animals', group: 1, word: 'monkey', transcription: 'ˈmʌŋki', translation: 'обезьяна' },
  { theme: 'animals', group: 1, word: 'zebra', transcription: 'ˈziːbrə', translation: 'зебра' },
  { theme: 'animals', group: 1, word: 'hippo', transcription: 'ˈhɪpəʊ', translation: 'бегемот' },
  { theme: 'animals', group: 1, word: 'rhino', transcription: 'ˈraɪnəʊ', translation: 'носорог' },
  { theme: 'animals', group: 1, word: 'camel', transcription: 'ˈkæml', translation: 'верблюд' },
  { theme: 'animals', group: 1, word: 'kangaroo', transcription: 'ˌkæŋɡəˈruː', translation: 'кенгуру' },
  { theme: 'animals', group: 1, word: 'penguin', transcription: 'ˈpeŋɡwɪn', translation: 'пингвин' },
  { theme: 'animals', group: 1, word: 'owl', transcription: 'aʊl', translation: 'сова' },
  { theme: 'animals', group: 1, word: 'eagle', transcription: 'ˈiːɡl', translation: 'орёл' },
  { theme: 'animals', group: 1, word: 'parrot', transcription: 'ˈpærət', translation: 'попугай' },
  { theme: 'animals', group: 1, word: 'swan', transcription: 'swɒn', translation: 'лебедь' },
  { theme: 'animals', group: 1, word: 'rooster', transcription: 'ˈruːstə', translation: 'петух' },
  { theme: 'animals', group: 1, word: 'crab', transcription: 'kræb', translation: 'краб' },
  { theme: 'animals', group: 1, word: 'shrimp', transcription: 'ʃrɪmp', translation: 'креветка' },
  { theme: 'animals', group: 1, word: 'whale', transcription: 'weɪl', translation: 'кит' },
  { theme: 'animals', group: 1, word: 'dolphin', transcription: 'ˈdɒlfɪn', translation: 'дельфин' },
  { theme: 'animals', group: 1, word: 'shark', transcription: 'ʃɑːk', translation: 'акула' },
  { theme: 'animals', group: 1, word: 'octopus', transcription: 'ˈɒktəpəs', translation: 'осьминог' },
  { theme: 'animals', group: 1, word: 'seal', transcription: 'siːl', translation: 'тюлень' },
  { theme: 'animals', group: 1, word: 'panda', transcription: 'ˈpændə', translation: 'панда' },
  { theme: 'animals', group: 1, word: 'koala', transcription: 'kəʊˈɑːlə', translation: 'коала' },
  { theme: 'animals', group: 1, word: 'bat', transcription: 'bæt', translation: 'летучая мышь' },
  { theme: 'animals', group: 1, word: 'snail', transcription: 'sneɪl', translation: 'улитка' },
  { theme: 'animals', group: 1, word: 'worm', transcription: 'wɜːm', translation: 'червь' },
  { theme: 'animals', group: 1, word: 'caterpillar', transcription: 'ˈkætəpɪlə', translation: 'гусеница' },
  { theme: 'animals', group: 1, word: 'grasshopper', transcription: 'ˈɡrɑːshɒpə', translation: 'кузнечик' },
  { theme: 'animals', group: 1, word: 'beetle', transcription: 'ˈbiːtl', translation: 'жук' },
  { theme: 'animals', group: 1, word: 'lamb', transcription: 'læm', translation: 'ягнёнок' },
  { theme: 'animals', group: 1, word: 'calf', transcription: 'kɑːf', translation: 'телёнок' },
  { theme: 'animals', group: 1, word: 'puppy', transcription: 'ˈpʌpi', translation: 'щенок' },
  { theme: 'animals', group: 1, word: 'kitten', transcription: 'ˈkɪtn', translation: 'котёнок' },
  { theme: 'animals', group: 1, word: 'ox', transcription: 'ɒks', translation: 'бык' },
  { theme: 'animals', group: 1, word: 'buffalo', transcription: 'ˈbʌfələʊ', translation: 'буйвол' },
  { theme: 'animals', group: 1, word: 'peacock', transcription: 'ˈpiːkɒk', translation: 'павлин' },
  { theme: 'animals', group: 1, word: 'flamingo', transcription: 'fləˈmɪŋɡəʊ', translation: 'фламинго' },
  { theme: 'animals', group: 1, word: 'ostrich', transcription: 'ˈɒstrɪtʃ', translation: 'страус' },

  // ---------- Тема: Глаголы (verbs) ----------
  { theme: 'verbs', group: 1, word: 'be', transcription: 'biː', translation: 'быть' },
  { theme: 'verbs', group: 1, word: 'have', transcription: 'hæv', translation: 'иметь' },
  { theme: 'verbs', group: 1, word: 'do', transcription: 'duː', translation: 'делать' },
  { theme: 'verbs', group: 1, word: 'say', transcription: 'seɪ', translation: 'говорить, сказать' },
  { theme: 'verbs', group: 1, word: 'go', transcription: 'ɡəʊ', translation: 'идти' },
  { theme: 'verbs', group: 1, word: 'get', transcription: 'ɡet', translation: 'получать, становиться' },
  { theme: 'verbs', group: 1, word: 'make', transcription: 'meɪk', translation: 'делать, создавать' },
  { theme: 'verbs', group: 1, word: 'know', transcription: 'nəʊ', translation: 'знать' },
  { theme: 'verbs', group: 1, word: 'think', transcription: 'θɪŋk', translation: 'думать' },
  { theme: 'verbs', group: 1, word: 'take', transcription: 'teɪk', translation: 'брать' },
  { theme: 'verbs', group: 1, word: 'see', transcription: 'siː', translation: 'видеть' },
  { theme: 'verbs', group: 1, word: 'come', transcription: 'kʌm', translation: 'приходить' },
  { theme: 'verbs', group: 1, word: 'want', transcription: 'wɒnt', translation: 'хотеть' },
  { theme: 'verbs', group: 1, word: 'use', transcription: 'juːz', translation: 'использовать' },
  { theme: 'verbs', group: 1, word: 'find', transcription: 'faɪnd', translation: 'находить' },
  { theme: 'verbs', group: 1, word: 'give', transcription: 'ɡɪv', translation: 'давать' },
  { theme: 'verbs', group: 1, word: 'tell', transcription: 'tel', translation: 'рассказывать' },
  { theme: 'verbs', group: 1, word: 'work', transcription: 'wɜːk', translation: 'работать' },
  { theme: 'verbs', group: 1, word: 'call', transcription: 'kɔːl', translation: 'звать, звонить' },
  { theme: 'verbs', group: 1, word: 'try', transcription: 'traɪ', translation: 'пытаться' },
  { theme: 'verbs', group: 1, word: 'ask', transcription: 'ɑːsk', translation: 'спрашивать' },
  { theme: 'verbs', group: 1, word: 'need', transcription: 'niːd', translation: 'нуждаться' },
  { theme: 'verbs', group: 1, word: 'feel', transcription: 'fiːl', translation: 'чувствовать' },
  { theme: 'verbs', group: 1, word: 'become', transcription: 'bɪˈkʌm', translation: 'становиться' },
  { theme: 'verbs', group: 1, word: 'leave', transcription: 'liːv', translation: 'уходить, оставлять' },
  { theme: 'verbs', group: 1, word: 'put', transcription: 'pʊt', translation: 'класть' },
  { theme: 'verbs', group: 1, word: 'mean', transcription: 'miːn', translation: 'значить' },
  { theme: 'verbs', group: 1, word: 'keep', transcription: 'kiːp', translation: 'держать, хранить' },
  { theme: 'verbs', group: 1, word: 'let', transcription: 'let', translation: 'позволять' },
  { theme: 'verbs', group: 1, word: 'begin', transcription: 'bɪˈɡɪn', translation: 'начинать' },
  { theme: 'verbs', group: 1, word: 'seem', transcription: 'siːm', translation: 'казаться' },
  { theme: 'verbs', group: 1, word: 'help', transcription: 'help', translation: 'помогать' },
  { theme: 'verbs', group: 1, word: 'talk', transcription: 'tɔːk', translation: 'говорить, беседовать' },
  { theme: 'verbs', group: 1, word: 'turn', transcription: 'tɜːn', translation: 'поворачивать' },
  { theme: 'verbs', group: 1, word: 'start', transcription: 'stɑːt', translation: 'начинать' },
  { theme: 'verbs', group: 1, word: 'show', transcription: 'ʃəʊ', translation: 'показывать' },
  { theme: 'verbs', group: 1, word: 'hear', transcription: 'hɪə', translation: 'слышать' },
  { theme: 'verbs', group: 1, word: 'play', transcription: 'pleɪ', translation: 'играть' },
  { theme: 'verbs', group: 1, word: 'run', transcription: 'rʌn', translation: 'бегать, бежать' },
  { theme: 'verbs', group: 1, word: 'move', transcription: 'muːv', translation: 'двигать(ся)' },
  { theme: 'verbs', group: 1, word: 'like', transcription: 'laɪk', translation: 'нравиться, любить' },
  { theme: 'verbs', group: 1, word: 'live', transcription: 'lɪv', translation: 'жить' },
  { theme: 'verbs', group: 1, word: 'believe', transcription: 'bɪˈliːv', translation: 'верить' },
  { theme: 'verbs', group: 1, word: 'hold', transcription: 'həʊld', translation: 'держать' },
  { theme: 'verbs', group: 1, word: 'bring', transcription: 'brɪŋ', translation: 'приносить' },
  { theme: 'verbs', group: 1, word: 'happen', transcription: 'ˈhæpən', translation: 'случаться' },
  { theme: 'verbs', group: 1, word: 'write', transcription: 'raɪt', translation: 'писать' },
  { theme: 'verbs', group: 1, word: 'sit', transcription: 'sɪt', translation: 'сидеть' },
  { theme: 'verbs', group: 1, word: 'stand', transcription: 'stænd', translation: 'стоять' },
  { theme: 'verbs', group: 1, word: 'lose', transcription: 'luːz', translation: 'терять' },
  { theme: 'verbs', group: 1, word: 'pay', transcription: 'peɪ', translation: 'платить' },
  { theme: 'verbs', group: 1, word: 'meet', transcription: 'miːt', translation: 'встречать' },
  { theme: 'verbs', group: 1, word: 'include', transcription: 'ɪnˈkluːd', translation: 'включать' },
  { theme: 'verbs', group: 1, word: 'learn', transcription: 'lɜːn', translation: 'учить(ся)' },
  { theme: 'verbs', group: 1, word: 'change', transcription: 'tʃeɪndʒ', translation: 'менять(ся)' },
  { theme: 'verbs', group: 1, word: 'lead', transcription: 'liːd', translation: 'вести' },
  { theme: 'verbs', group: 1, word: 'understand', transcription: 'ˌʌndəˈstænd', translation: 'понимать' },
  { theme: 'verbs', group: 1, word: 'watch', transcription: 'wɒtʃ', translation: 'смотреть' },
  { theme: 'verbs', group: 1, word: 'follow', transcription: 'ˈfɒləʊ', translation: 'следовать' },
  { theme: 'verbs', group: 1, word: 'stop', transcription: 'stɒp', translation: 'останавливать(ся)' },
  { theme: 'verbs', group: 1, word: 'speak', transcription: 'spiːk', translation: 'говорить (на языке)' },
  { theme: 'verbs', group: 1, word: 'read', transcription: 'riːd', translation: 'читать' },
  { theme: 'verbs', group: 1, word: 'eat', transcription: 'iːt', translation: 'есть, кушать' },
  { theme: 'verbs', group: 1, word: 'drink', transcription: 'drɪŋk', translation: 'пить' },
  { theme: 'verbs', group: 1, word: 'sleep', transcription: 'sliːp', translation: 'спать' },
  { theme: 'verbs', group: 1, word: 'walk', transcription: 'wɔːk', translation: 'гулять, идти пешком' },
  { theme: 'verbs', group: 1, word: 'open', transcription: 'ˈəʊpən', translation: 'открывать' },
  { theme: 'verbs', group: 1, word: 'close', transcription: 'kləʊz', translation: 'закрывать' },
  { theme: 'verbs', group: 1, word: 'love', transcription: 'lʌv', translation: 'любить' },
  { theme: 'verbs', group: 1, word: 'buy', transcription: 'baɪ', translation: 'покупать' },
  { theme: 'verbs', group: 1, word: 'sell', transcription: 'sel', translation: 'продавать' },
  { theme: 'verbs', group: 1, word: 'teach', transcription: 'tiːtʃ', translation: 'учить, преподавать' },
  { theme: 'verbs', group: 1, word: 'study', transcription: 'ˈstʌdi', translation: 'учить, изучать' },
  { theme: 'verbs', group: 1, word: 'travel', transcription: 'ˈtrævl', translation: 'путешествовать' },
  { theme: 'verbs', group: 1, word: 'drive', transcription: 'draɪv', translation: 'водить (машину)' },
  { theme: 'verbs', group: 1, word: 'fly', transcription: 'flaɪ', translation: 'летать' },
  { theme: 'verbs', group: 1, word: 'swim', transcription: 'swɪm', translation: 'плавать' },
  { theme: 'verbs', group: 1, word: 'sing', transcription: 'sɪŋ', translation: 'петь' },
  { theme: 'verbs', group: 1, word: 'cook', transcription: 'kʊk', translation: 'готовить (еду)' },
  { theme: 'verbs', group: 1, word: 'build', transcription: 'bɪld', translation: 'строить' },
  { theme: 'verbs', group: 1, word: 'catch', transcription: 'kætʃ', translation: 'ловить' },
  { theme: 'verbs', group: 1, word: 'grow', transcription: 'ɡrəʊ', translation: 'расти, выращивать' },
  { theme: 'verbs', group: 1, word: 'cut', transcription: 'kʌt', translation: 'резать' },
  { theme: 'verbs', group: 1, word: 'fall', transcription: 'fɔːl', translation: 'падать' },
  { theme: 'verbs', group: 1, word: 'forget', transcription: 'fəˈɡet', translation: 'забывать' },
  { theme: 'verbs', group: 1, word: 'remember', transcription: 'rɪˈmembə', translation: 'помнить' },

  // ---------- Тема: Время (time) ----------
  // Q&A: каждая карточка — вопрос и 4 варианта ответа (options + answer).
  // word — вопрос, translation — правильный ответ, options — 4 варианта, answer — индекс ответа.
  { theme: 'time', sub: 'digital', word: '14:00', translation: '2 часа дня (PM)', options: ['12 часов дня', '2 часа дня (PM)', '1 час дня', '3 часа дня'], answer: 1 },
  { theme: 'time', sub: 'digital', word: '15:30', translation: '3 часа 30 минут дня', options: ['1 час 30 минут дня', '2 часа 30 минут дня', '3 часа 30 минут дня', '4 часа 30 минут дня'], answer: 2 },
  { theme: 'time', sub: 'digital', word: '18:45', translation: '6 часов 45 минут вечера', options: ['4 часа 45 минут дня', '5 часов 45 минут дня', '6 часов 45 минут вечера', '7 часов 45 минут вечера'], answer: 2 },
  { theme: 'time', sub: 'digital', word: '20:15', translation: '8 часов 15 минут вечера', options: ['8 часов 15 минут вечера', '6 часов 15 минут вечера', '7 часов 15 минут вечера', '9 часов 15 минут вечера'], answer: 0 },
  { theme: 'time', sub: 'digital', word: '22:00', translation: '10 часов вечера', options: ['8 часов вечера', '10 часов вечера', '9 часов вечера', '11 часов ночи'], answer: 1 },
  { theme: 'time', sub: 'digital', word: '23:59', translation: '11 часов 59 минут ночи', options: ['9 часов 59 минут вечера', '11 часов 59 минут ночи', '10 часов 59 минут ночи', '12 часов 59 минут утра'], answer: 1 },
  { theme: 'time', sub: 'digital', word: '00:00', translation: 'полночь (12:00)', options: ['10 часов ночи', '11 часов ночи', '1 час утра', 'полночь (12:00)'], answer: 3 },
  { theme: 'time', sub: 'digital', word: '09:00', translation: '9 часов утра', options: ['7 часов утра', '8 часов утра', '9 часов утра', '10 часов утра'], answer: 2 },
  { theme: 'time', sub: 'digital', word: '12:00', translation: 'полдень (12:00)', options: ['10 часов утра', '11 часов утра', 'полдень (12:00)', '1 час дня'], answer: 2 },
  { theme: 'time', sub: 'digital', word: '13:00', translation: '1 час дня', options: ['11 часов утра', '1 час дня', '12 часов дня', '2 часа дня'], answer: 1 },
  { theme: 'time', sub: 'digital', word: '16:20', translation: '4 часа 20 минут дня', options: ['2 часа 20 минут дня', '3 часа 20 минут дня', '4 часа 20 минут дня', '5 часов 20 минут дня'], answer: 2 },
  { theme: 'time', sub: 'digital', word: '19:05', translation: '7 часов 05 минут вечера', options: ['5 часов 05 минут дня', '7 часов 05 минут вечера', '6 часов 05 минут вечера', '8 часов 05 минут вечера'], answer: 1 },
  { theme: 'time', sub: 'digital', word: '21:40', translation: '9 часов 40 минут вечера', options: ['9 часов 40 минут вечера', '7 часов 40 минут вечера', '8 часов 40 минут вечера', '10 часов 40 минут ночи'], answer: 0 },
  { theme: 'time', sub: 'digital', word: '07:30', translation: '7 часов 30 минут утра', options: ['7 часов 30 минут утра', '5 часов 30 минут утра', '6 часов 30 минут утра', '8 часов 30 минут утра'], answer: 0 },
  { theme: 'time', sub: 'digital', word: '11:15', translation: '11 часов 15 минут утра', options: ['9 часов 15 минут утра', '10 часов 15 минут утра', '11 часов 15 минут утра', '12 часов 15 минут дня'], answer: 2 },
  { theme: 'time', sub: 'digital', word: '17:50', translation: '5 часов 50 минут вечера', options: ['5 часов 50 минут вечера', '3 часа 50 минут дня', '4 часа 50 минут дня', '6 часов 50 минут вечера'], answer: 0 },
  { theme: 'time', sub: 'digital', word: '08:45', translation: '8 часов 45 минут утра', options: ['8 часов 45 минут утра', '6 часов 45 минут утра', '7 часов 45 минут утра', '9 часов 45 минут утра'], answer: 0 },
  { theme: 'time', sub: 'digital', word: '10:10', translation: '10 часов 10 минут утра', options: ['10 часов 10 минут утра', '8 часов 10 минут утра', '9 часов 10 минут утра', '11 часов 10 минут утра'], answer: 0 },
  { theme: 'time', sub: 'digital', word: '06:00', translation: '6 часов утра', options: ['6 часов утра', '4 часа утра', '5 часов утра', '7 часов утра'], answer: 0 },
  { theme: 'time', sub: 'digital', word: '04:30', translation: '4 часа 30 минут утра', options: ['2 часа 30 минут утра', '4 часа 30 минут утра', '3 часа 30 минут утра', '5 часов 30 минут утра'], answer: 1 },
  { theme: 'time', sub: 'digital', word: '2 часа дня', translation: '14:00', options: ['12:00', '13:00', '14:00', '15:00'], answer: 2 },
  { theme: 'time', sub: 'digital', word: 'полдень', translation: '12:00', options: ['10:00', '11:00', '12:00', '13:00'], answer: 2 },
  { theme: 'time', sub: 'digital', word: 'полночь', translation: '00:00', options: ['00:00', '22:00', '23:00', '01:00'], answer: 0 },
  { theme: 'time', sub: 'digital', word: '7 часов вечера', translation: '19:00', options: ['17:00', '18:00', '20:00', '19:00'], answer: 3 },
  { theme: 'time', sub: 'digital', word: '9 часов утра', translation: '09:00', options: ['07:00', '08:00', '10:00', '09:00'], answer: 3 },
  { theme: 'time', sub: 'digital', word: '11 часов ночи', translation: '23:00', options: ['21:00', '22:00', '00:00', '23:00'], answer: 3 },
  { theme: 'time', sub: 'mech', word: 'Без пяти минут три', translation: '2:55', options: ['2:45', '2:50', '2:55', '3:00'], answer: 2 },
  { theme: 'time', sub: 'mech', word: 'Без четверти три', translation: '2:45', options: ['2:35', '2:40', '2:45', '2:50'], answer: 2 },
  { theme: 'time', sub: 'mech', word: 'Четверть третьего', translation: '2:15', options: ['2:05', '2:10', '2:15', '2:20'], answer: 2 },
  { theme: 'time', sub: 'mech', word: 'Половина третьего', translation: '2:30', options: ['2:20', '2:25', '2:35', '2:30'], answer: 3 },
  { theme: 'time', sub: 'mech', word: 'Без двадцати три', translation: '2:40', options: ['2:30', '2:40', '2:35', '2:45'], answer: 1 },
  { theme: 'time', sub: 'mech', word: 'Пять минут третьего', translation: '2:05', options: ['1:55', '2:00', '2:10', '2:05'], answer: 3 },
  { theme: 'time', sub: 'mech', word: 'Ровно три', translation: '3:00', options: ['3:00', '2:50', '2:55', '3:05'], answer: 0 },
  { theme: 'time', sub: 'mech', word: 'Десять минут четвёртого', translation: '3:10', options: ['3:00', '3:05', '3:10', '3:15'], answer: 2 },
  { theme: 'time', sub: 'mech', word: 'Без десяти четыре', translation: '3:50', options: ['3:40', '3:45', '3:55', '3:50'], answer: 3 },
  { theme: 'time', sub: 'mech', word: 'Четверть пятого', translation: '4:15', options: ['4:15', '4:05', '4:10', '4:20'], answer: 0 },
  { theme: 'time', sub: 'mech', word: 'Половина шестого', translation: '5:30', options: ['5:20', '5:25', '5:35', '5:30'], answer: 3 },
  { theme: 'time', sub: 'mech', word: 'Без четверти семь', translation: '6:45', options: ['6:35', '6:40', '6:45', '6:50'], answer: 2 },
  { theme: 'time', sub: 'mech', word: 'Двадцать минут восьмого', translation: '7:20', options: ['7:10', '7:20', '7:15', '7:25'], answer: 1 },
  { theme: 'time', sub: 'mech', word: 'Четверть первого', translation: '12:15', options: ['12:15', '12:05', '12:10', '12:20'], answer: 0 },
  { theme: 'time', sub: 'mech', word: 'Половина второго', translation: '1:30', options: ['1:30', '1:20', '1:25', '1:35'], answer: 0 },
  { theme: 'time', sub: 'mech', word: 'Без пятнадцати два', translation: '1:45', options: ['1:35', '1:40', '1:50', '1:45'], answer: 3 },
  { theme: 'time', sub: 'mech', word: 'Десять минут третьего', translation: '2:10', options: ['2:00', '2:10', '2:05', '2:15'], answer: 1 },
  { theme: 'time', sub: 'mech', word: 'Пятнадцать минут одиннадцатого', translation: '10:15', options: ['10:05', '10:10', '10:20', '10:15'], answer: 3 },
  { theme: 'time', sub: 'mech', word: 'Ровно семь', translation: '7:00', options: ['6:50', '7:00', '6:55', '7:05'], answer: 1 },
  { theme: 'time', sub: 'mech', word: 'Двадцать пять минут десятого', translation: '9:25', options: ['9:15', '9:20', '9:30', '9:25'], answer: 3 },
  { theme: 'time', sub: 'mech', word: 'Без десяти шесть', translation: '5:50', options: ['5:40', '5:50', '5:45', '5:55'], answer: 1 },
  { theme: 'time', sub: 'mech', word: 'Пять минут первого', translation: '12:05', options: ['11:55', '12:00', '12:10', '12:05'], answer: 3 },
  { theme: 'time', sub: 'mech', word: 'Ровно двенадцать', translation: '12:00', options: ['11:50', '11:55', '12:05', '12:00'], answer: 3 },
  { theme: 'time', sub: 'mech', word: 'Без двадцати пять', translation: '4:40', options: ['4:30', '4:40', '4:35', '4:45'], answer: 1 },
  { theme: 'time', sub: 'mech', word: 'Двадцать минут второго', translation: '1:20', options: ['1:20', '1:10', '1:15', '1:25'], answer: 0 },
   { theme: 'time', sub: 'mech', word: 'Половина десятого', translation: '9:30', options: ['9:20', '9:25', '9:35', '9:30'], answer: 3 },
];

