// cards_krokodil.js — данные для игры «Крокодил» (шарады): один игрок
// молча показывает слово/фразу с карточки, остальные угадывают. Раунд на
// время — сколько слов угадали, столько очков за раунд.
// KROKODIL_LEVELS — 4 уровня (id, name, desc, icon).
// KROKODIL_CARDS — { level, text, icon, mode? }, по 250 карточек на каждый
// уровень (1000 всего): 200 без поля mode — режим «Действие» (сценки,
// эмоции, персонажи, часто из нескольких слов) и 50 с mode:'word' — режим
// «Слово» (только одиночные существительные, для классического угадывания
// слов). icon — крупная иконка-подсказка, показывается над словом на карточке.

const KROKODIL_LEVELS = [
  {id:1, name:'До 12 лет', desc:'Для всей семьи', icon:'🧒'},
  {id:2, name:'До 18 лет', desc:'Для подростковой компании', icon:'🎈'},
  {id:3, name:'18+', desc:'Для взрослой компании', icon:'🔥'},
  {id:4, name:'Пошлые', desc:'Только для смелых', icon:'😈'},
];

const KROKODIL_CARDS = [
  { level: 1, text: 'Слон', icon: '🐘' },
  { level: 1, text: 'Жираф', icon: '🦒' },
  { level: 1, text: 'Лев', icon: '🦁' },
  { level: 1, text: 'Тигр', icon: '🐯' },
  { level: 1, text: 'Обезьяна', icon: '🐒' },
  { level: 1, text: 'Кенгуру', icon: '🦘' },
  { level: 1, text: 'Пингвин', icon: '🐧' },
  { level: 1, text: 'Крокодил', icon: '🐊' },
  { level: 1, text: 'Зебра', icon: '🦓' },
  { level: 1, text: 'Панда', icon: '🐼' },
  { level: 1, text: 'Медведь', icon: '🐻' },
  { level: 1, text: 'Заяц', icon: '🐰' },
  { level: 1, text: 'Лиса', icon: '🦊' },
  { level: 1, text: 'Волк', icon: '🐺' },
  { level: 1, text: 'Ёж', icon: '🦔' },
  { level: 1, text: 'Белка', icon: '🐿️' },
  { level: 1, text: 'Черепаха', icon: '🐢' },
  { level: 1, text: 'Лягушка', icon: '🐸' },
  { level: 1, text: 'Паук', icon: '🕷️' },
  { level: 1, text: 'Бабочка', icon: '🦋' },
  { level: 1, text: 'Пчела', icon: '🐝' },
  { level: 1, text: 'Курица', icon: '🐔' },
  { level: 1, text: 'Петух', icon: '🐓' },
  { level: 1, text: 'Корова', icon: '🐄' },
  { level: 1, text: 'Свинья', icon: '🐖' },
  { level: 1, text: 'Лошадь', icon: '🐴' },
  { level: 1, text: 'Кошка', icon: '🐱' },
  { level: 1, text: 'Собака', icon: '🐶' },
  { level: 1, text: 'Мышь', icon: '🐭' },
  { level: 1, text: 'Змея', icon: '🐍' },
  { level: 1, text: 'Прыгать', icon: '🤸' },
  { level: 1, text: 'Бегать', icon: '🏃' },
  { level: 1, text: 'Плавать', icon: '🏊' },
  { level: 1, text: 'Летать', icon: '🕊️' },
  { level: 1, text: 'Танцевать', icon: '💃' },
  { level: 1, text: 'Петь', icon: '🎤' },
  { level: 1, text: 'Спать', icon: '😴' },
  { level: 1, text: 'Есть', icon: '🍽️' },
  { level: 1, text: 'Пить', icon: '🥤' },
  { level: 1, text: 'Читать', icon: '📖' },
  { level: 1, text: 'Писать', icon: '✍️' },
  { level: 1, text: 'Рисовать', icon: '🎨' },
  { level: 1, text: 'Играть в футбол', icon: '⚽' },
  { level: 1, text: 'Кататься на велосипеде', icon: '🚴' },
  { level: 1, text: 'Чистить зубы', icon: '🪥' },
  { level: 1, text: 'Мыть посуду', icon: '🧼' },
  { level: 1, text: 'Готовить еду', icon: '🍳' },
  { level: 1, text: 'Стричь волосы', icon: '✂️' },
  { level: 1, text: 'Ловить рыбу', icon: '🎣' },
  { level: 1, text: 'Строить замок из песка', icon: '🏖️' },
  { level: 1, text: 'Врач', icon: '🩺' },
  { level: 1, text: 'Учитель', icon: '👩‍🏫' },
  { level: 1, text: 'Пожарный', icon: '🚒' },
  { level: 1, text: 'Полицейский', icon: '👮' },
  { level: 1, text: 'Повар', icon: '👨‍🍳' },
  { level: 1, text: 'Художник', icon: '🖌️' },
  { level: 1, text: 'Музыкант', icon: '🎸' },
  { level: 1, text: 'Космонавт', icon: '🚀' },
  { level: 1, text: 'Водитель автобуса', icon: '🚌' },
  { level: 1, text: 'Парикмахер', icon: '💇' },
  { level: 1, text: 'Зонтик', icon: '☂️' },
  { level: 1, text: 'Ножницы', icon: '✂️' },
  { level: 1, text: 'Будильник', icon: '⏰' },
  { level: 1, text: 'Телефон', icon: '📱' },
  { level: 1, text: 'Зубная щётка', icon: '🪥' },
  { level: 1, text: 'Воздушный шар', icon: '🎈' },
  { level: 1, text: 'Светофор', icon: '🚦' },
  { level: 1, text: 'Велосипед', icon: '🚲' },
  { level: 1, text: 'Снеговик', icon: '☃️' },
  { level: 1, text: 'Ёлка', icon: '🎄' },
  { level: 1, text: 'Колобок', icon: '🍞' },
  { level: 1, text: 'Красная Шапочка', icon: '🔴' },
  { level: 1, text: 'Три поросёнка', icon: '🐷' },
  { level: 1, text: 'Чебурашка', icon: '🧸' },
  { level: 1, text: 'Винни-Пух', icon: '🍯' },
  { level: 1, text: 'Дед Мороз', icon: '🎅' },
  { level: 1, text: 'Снегурочка', icon: '❄️' },
  { level: 1, text: 'Баба Яга', icon: '🧙‍♀️' },
  { level: 1, text: 'Золушка', icon: '👠' },
  { level: 1, text: 'Буратино', icon: '🪵' },
  { level: 1, text: 'Играть в баскетбол', icon: '🏀' },
  { level: 1, text: 'Кататься на коньках', icon: '⛸️' },
  { level: 1, text: 'Прыгать через скакалку', icon: '🪢' },
  { level: 1, text: 'Играть в снежки', icon: '⚪' },
  { level: 1, text: 'Лепить снеговика', icon: '⛄' },
  { level: 1, text: 'Качаться на качелях', icon: '🛝' },
  { level: 1, text: 'Надувать шарик', icon: '🎈' },
  { level: 1, text: 'Запускать воздушного змея', icon: '🪁' },
  { level: 1, text: 'Собирать пазл', icon: '🧩' },
  { level: 1, text: 'Кормить рыбок', icon: '🐟' },
  { level: 1, text: 'Дельфин', icon: '🐬' },
  { level: 1, text: 'Кит', icon: '🐳' },
  { level: 1, text: 'Осьминог', icon: '🐙' },
  { level: 1, text: 'Краб', icon: '🦀' },
  { level: 1, text: 'Улитка', icon: '🐌' },
  { level: 1, text: 'Сова', icon: '🦉' },
  { level: 1, text: 'Попугай', icon: '🦜' },
  { level: 1, text: 'Страус', icon: '🦤' },
  { level: 1, text: 'Верблюд', icon: '🐫' },
  { level: 1, text: 'Олень', icon: '🦌' },
  { level: 2, text: 'Контрольная работа', icon: '📝' },
  { level: 2, text: 'Звонок с урока', icon: '🔔' },
  { level: 2, text: 'Шпаргалка', icon: '📄' },
  { level: 2, text: 'Экзамен', icon: '📋' },
  { level: 2, text: 'Домашнее задание', icon: '📚' },
  { level: 2, text: 'Школьная линейка', icon: '🎒' },
  { level: 2, text: 'Классный час', icon: '🏫' },
  { level: 2, text: 'Дневник с двойкой', icon: '📕' },
  { level: 2, text: 'Учитель ругается', icon: '😠' },
  { level: 2, text: 'Перемена', icon: '🏃' },
  { level: 2, text: 'Селфи', icon: '🤳' },
  { level: 2, text: 'Лайк в инстаграме', icon: '❤️' },
  { level: 2, text: 'Видеозвонок', icon: '📹' },
  { level: 2, text: 'Залипание в телефоне', icon: '📱' },
  { level: 2, text: 'Тикток-танец', icon: '💃' },
  { level: 2, text: 'Компьютерная игра', icon: '🎮' },
  { level: 2, text: 'Зарядка телефона на нуле', icon: '🔋' },
  { level: 2, text: 'Вай-фай пропал', icon: '📶' },
  { level: 2, text: 'Стрим блогера', icon: '📡' },
  { level: 2, text: 'Мем в чате', icon: '😂' },
  { level: 2, text: 'Футбольный матч', icon: '⚽' },
  { level: 2, text: 'Баскетбольный бросок', icon: '🏀' },
  { level: 2, text: 'Скейтборд', icon: '🛹' },
  { level: 2, text: 'Сноуборд', icon: '🏂' },
  { level: 2, text: 'Вратарь берёт мяч', icon: '🥅' },
  { level: 2, text: 'Финиш забега', icon: '🏁' },
  { level: 2, text: 'Качаться в спортзале', icon: '🏋️' },
  { level: 2, text: 'Йога', icon: '🧘' },
  { level: 2, text: 'Армрестлинг', icon: '💪' },
  { level: 2, text: 'Теннисная подача', icon: '🎾' },
  { level: 2, text: 'Супергерой летит', icon: '🦸' },
  { level: 2, text: 'Зомби-апокалипсис', icon: '🧟' },
  { level: 2, text: 'Пиратский корабль', icon: '🏴‍☠️' },
  { level: 2, text: 'Космический корабль', icon: '🚀' },
  { level: 2, text: 'Робот-трансформер', icon: '🤖' },
  { level: 2, text: 'Вампир кусает', icon: '🧛' },
  { level: 2, text: 'Оборотень воет', icon: '🐺' },
  { level: 2, text: 'Детектив расследует', icon: '🕵️' },
  { level: 2, text: 'Привидение пугает', icon: '👻' },
  { level: 2, text: 'Дракон дышит огнём', icon: '🐉' },
  { level: 2, text: 'Смущение на свидании', icon: '😳' },
  { level: 2, text: 'Ссора с другом', icon: '😤' },
  { level: 2, text: 'Влюблённость с первого взгляда', icon: '😍' },
  { level: 2, text: 'Паника перед экзаменом', icon: '😱' },
  { level: 2, text: 'Восторг от подарка', icon: '🤩' },
  { level: 2, text: 'Скука на уроке', icon: '🥱' },
  { level: 2, text: 'Ревность', icon: '😒' },
  { level: 2, text: 'Зависть к однокласснику', icon: '😑' },
  { level: 2, text: 'Гордость за оценку', icon: '🥇' },
  { level: 2, text: 'Обида на друга', icon: '😢' },
  { level: 2, text: 'Игра на гитаре', icon: '🎸' },
  { level: 2, text: 'Рисование граффити', icon: '🎨' },
  { level: 2, text: 'Катание на роликах', icon: '🛼' },
  { level: 2, text: 'Косплей', icon: '🎭' },
  { level: 2, text: 'Чтение манги', icon: '📖' },
  { level: 2, text: 'Ведение блога', icon: '📝' },
  { level: 2, text: 'Фотография заката', icon: '📸' },
  { level: 2, text: 'Коллекционирование наклеек', icon: '🏷️' },
  { level: 2, text: 'Настольная игра', icon: '🎲' },
  { level: 2, text: 'Квест-комната', icon: '🔍' },
  { level: 2, text: 'Выпускной', icon: '🎓' },
  { level: 2, text: 'День рождения с тортом', icon: '🎂' },
  { level: 2, text: 'Новогодняя дискотека', icon: '🎉' },
  { level: 2, text: 'Хэллоуин костюм', icon: '🎃' },
  { level: 2, text: 'Школьная дискотека', icon: '🕺' },
  { level: 2, text: 'Летний лагерь', icon: '🏕️' },
  { level: 2, text: 'Поездка на море', icon: '🏖️' },
  { level: 2, text: 'Первый поцелуй', icon: '💋' },
  { level: 2, text: 'Первое свидание', icon: '🌹' },
  { level: 2, text: 'Драка подушками', icon: '🛏️' },
  { level: 2, text: 'Блогер снимает видео', icon: '🎥' },
  { level: 2, text: 'Программист пишет код', icon: '💻' },
  { level: 2, text: 'Диджей на вечеринке', icon: '🎧' },
  { level: 2, text: 'Модель на подиуме', icon: '💃' },
  { level: 2, text: 'Певец на сцене', icon: '🎤' },
  { level: 2, text: 'Актёр в кино', icon: '🎬' },
  { level: 2, text: 'Спортивный комментатор', icon: '🎙️' },
  { level: 2, text: 'Ветеринар лечит собаку', icon: '🐕‍🦺' },
  { level: 2, text: 'Стендап-комик шутит', icon: '🎙️' },
  { level: 2, text: 'Тату-мастер набивает тату', icon: '🖋️' },
  { level: 2, text: 'Зомби в компьютерной игре', icon: '🧟' },
  { level: 2, text: 'Батл рэперов', icon: '🎤' },
  { level: 2, text: 'Флешмоб', icon: '🕺' },
  { level: 2, text: 'Киберспорт-турнир', icon: '🎮' },
  { level: 2, text: 'Пранк над другом', icon: '🎭' },
  { level: 2, text: 'Вписка у друга', icon: '🏠' },
  { level: 2, text: 'Поход в кино', icon: '🎬' },
  { level: 2, text: 'Шоппинг с подругой', icon: '🛍️' },
  { level: 2, text: 'Очередь за новым телефоном', icon: '📱' },
  { level: 2, text: 'Потерянный наушник', icon: '🎧' },
  { level: 2, text: 'Мем «рикролл»', icon: '😂' },
  { level: 2, text: 'Тренд в тиктоке', icon: '📱' },
  { level: 2, text: 'Распаковка посылки', icon: '📦' },
  { level: 2, text: 'Розыгрыш в классе', icon: '🤡' },
  { level: 2, text: 'Урок физкультуры', icon: '🤸' },
  { level: 2, text: 'Экзамен по вождению', icon: '🚗' },
  { level: 2, text: 'Спор в чате класса', icon: '💬' },
  { level: 2, text: 'Выбор профессии', icon: '🎯' },
  { level: 2, text: 'Поступление в институт', icon: '🎓' },
  { level: 2, text: 'Летние каникулы', icon: '☀️' },
  { level: 3, text: 'Первое свидание вслепую', icon: '🌹' },
  { level: 3, text: 'Знакомство в баре', icon: '🍸' },
  { level: 3, text: 'Признание в любви', icon: '💘' },
  { level: 3, text: 'Предложение руки и сердца', icon: '💍' },
  { level: 3, text: 'Свадьба', icon: '👰' },
  { level: 3, text: 'Развод', icon: '💔' },
  { level: 3, text: 'Ссора с партнёром', icon: '😠' },
  { level: 3, text: 'Ревнивый партнёр', icon: '😒' },
  { level: 3, text: 'Романтический ужин', icon: '🕯️' },
  { level: 3, text: 'Медовый месяц', icon: '🏝️' },
  { level: 3, text: 'Дедлайн на работе', icon: '⏰' },
  { level: 3, text: 'Начальник кричит', icon: '😡' },
  { level: 3, text: 'Повышение зарплаты', icon: '💰' },
  { level: 3, text: 'Увольнение', icon: '📤' },
  { level: 3, text: 'Собеседование', icon: '🤝' },
  { level: 3, text: 'Корпоратив', icon: '🥂' },
  { level: 3, text: 'Переговоры с клиентом', icon: '🤝' },
  { level: 3, text: 'Работа из дома', icon: '💻' },
  { level: 3, text: 'Отпуск мечты', icon: '✈️' },
  { level: 3, text: 'Понедельник после выходных', icon: '😩' },
  { level: 3, text: 'Похмелье утром', icon: '🤢' },
  { level: 3, text: 'Тост на дне рождения', icon: '🥂' },
  { level: 3, text: 'Пьяный танец', icon: '🕺' },
  { level: 3, text: 'Бармен смешивает коктейль', icon: '🍹' },
  { level: 3, text: 'Вечеринка в клубе', icon: '🎉' },
  { level: 3, text: 'Караоке с друзьями', icon: '🎤' },
  { level: 3, text: 'Застолье с тостами', icon: '🍷' },
  { level: 3, text: 'Откупоривание шампанского', icon: '🍾' },
  { level: 3, text: 'Дегустация вина', icon: '🍷' },
  { level: 3, text: 'Пивной живот', icon: '🍺' },
  { level: 3, text: 'Пелёнки новорождённого', icon: '👶' },
  { level: 3, text: 'Бессонная ночь с ребёнком', icon: '😴' },
  { level: 3, text: 'Ипотека', icon: '🏠' },
  { level: 3, text: 'Ремонт квартиры', icon: '🔨' },
  { level: 3, text: 'Поход в ИКЕА', icon: '🛋️' },
  { level: 3, text: 'Ссора из-за посуды', icon: '🍽️' },
  { level: 3, text: 'Тёща в гостях', icon: '👵' },
  { level: 3, text: 'Семейный ужин', icon: '🍽️' },
  { level: 3, text: 'Воспитание подростка', icon: '🧑' },
  { level: 3, text: 'Поход к стоматологу', icon: '🦷' },
  { level: 3, text: 'Поход к врачу', icon: '👨‍⚕️' },
  { level: 3, text: 'Боль в спине', icon: '🦴' },
  { level: 3, text: 'Диета', icon: '🥗' },
  { level: 3, text: 'Утренняя пробежка', icon: '🏃' },
  { level: 3, text: 'Отказ от курения', icon: '🚭' },
  { level: 3, text: 'Первая седина', icon: '⚪' },
  { level: 3, text: 'Кризис среднего возраста', icon: '🚗' },
  { level: 3, text: 'Врач-гинеколог', icon: '👩‍⚕️' },
  { level: 3, text: 'УЗИ беременной', icon: '🤰' },
  { level: 3, text: 'Роды в больнице', icon: '🏥' },
  { level: 3, text: 'Похмельный завтрак', icon: '🍳' },
  { level: 3, text: 'Будильник не разбудил', icon: '⏰' },
  { level: 3, text: 'Пробка на дороге', icon: '🚗' },
  { level: 3, text: 'Забытый пароль', icon: '🔑' },
  { level: 3, text: 'Спам-звонок', icon: '📞' },
  { level: 3, text: 'Налоговая декларация', icon: '🧾' },
  { level: 3, text: 'Очередь в поликлинике', icon: '🏥' },
  { level: 3, text: 'Потерянные ключи', icon: '🔑' },
  { level: 3, text: 'Разряженный телефон в такси', icon: '🔋' },
  { level: 3, text: 'Опоздание на самолёт', icon: '✈️' },
  { level: 3, text: 'Отпуск на пляже', icon: '🏖️' },
  { level: 3, text: 'Дайвинг', icon: '🤿' },
  { level: 3, text: 'Горнолыжный курорт', icon: '⛷️' },
  { level: 3, text: 'Пикник на природе', icon: '🧺' },
  { level: 3, text: 'Рыбалка с друзьями', icon: '🎣' },
  { level: 3, text: 'Поход в баню', icon: '🧖' },
  { level: 3, text: 'Спа-салон', icon: '💆' },
  { level: 3, text: 'Массаж', icon: '💆‍♀️' },
  { level: 3, text: 'Йога-ретрит', icon: '🧘' },
  { level: 3, text: 'Круиз на лайнере', icon: '🚢' },
  { level: 3, text: 'Стриптиз-пятница в клубе', icon: '🎭' },
  { level: 3, text: 'Покерный турнир', icon: '♠️' },
  { level: 3, text: 'Казино', icon: '🎰' },
  { level: 3, text: 'Скачки на ипподроме', icon: '🐎' },
  { level: 3, text: 'Дегустация виски', icon: '🥃' },
  { level: 3, text: 'Сигара после ужина', icon: '🚬' },
  { level: 3, text: 'Вечер настольных игр', icon: '🎲' },
  { level: 3, text: 'Квиз в баре', icon: '🧠' },
  { level: 3, text: 'Боулинг с друзьями', icon: '🎳' },
  { level: 3, text: 'Бильярд', icon: '🎱' },
  { level: 3, text: 'Адвокат в суде', icon: '⚖️' },
  { level: 3, text: 'Риелтор показывает квартиру', icon: '🏠' },
  { level: 3, text: 'Психолог на приёме', icon: '🛋️' },
  { level: 3, text: 'Финансовый консультант', icon: '📊' },
  { level: 3, text: 'Бизнесмен на встрече', icon: '💼' },
  { level: 3, text: 'Стендап про отношения', icon: '🎤' },
  { level: 3, text: 'Ведущий свадьбы', icon: '🎙️' },
  { level: 3, text: 'Фотограф на свадьбе', icon: '📷' },
  { level: 3, text: 'Визажист', icon: '💄' },
  { level: 3, text: 'Личный тренер', icon: '🏋️' },
  { level: 3, text: 'Пробуждение с похмелья без памяти', icon: '🤯' },
  { level: 3, text: 'Свидание через приложение знакомств', icon: '📱' },
  { level: 3, text: 'Зависание в баре после работы', icon: '🍹' },
  { level: 3, text: 'Случайная встреча с бывшим партнёром', icon: '😳' },
  { level: 3, text: 'Ночная смена в баре', icon: '🌙' },
  { level: 3, text: 'Вызов такси в 3 ночи', icon: '🚕' },
  { level: 3, text: 'Ссора соседей за стеной', icon: '🧱' },
  { level: 3, text: 'Вечеринка-сюрприз', icon: '🎉' },
  { level: 3, text: 'Мальчишник', icon: '🍻' },
  { level: 3, text: 'Девичник', icon: '💃' },
  { level: 4, text: 'Стриптиз', icon: '💃' },
  { level: 4, text: 'Оргазм', icon: '😩' },
  { level: 4, text: 'Минет', icon: '👄' },
  { level: 4, text: 'Куннилингус', icon: '👅' },
  { level: 4, text: 'Секс на одну ночь', icon: '🌙' },
  { level: 4, text: 'Измена', icon: '💔' },
  { level: 4, text: 'Оргия', icon: '🔥' },
  { level: 4, text: 'Свингеры', icon: '🔄' },
  { level: 4, text: 'БДСМ', icon: '⛓️' },
  { level: 4, text: 'Страпон', icon: '🍆' },
  { level: 4, text: 'Вибратор', icon: '⚡' },
  { level: 4, text: 'Наручники в спальне', icon: '🔒' },
  { level: 4, text: 'Ролевые игры в постели', icon: '🎭' },
  { level: 4, text: 'Костюм медсестры', icon: '👩‍⚕️' },
  { level: 4, text: 'Стриптизёрша на шесте', icon: '💃' },
  { level: 4, text: 'Мужской стриптизёр', icon: '🕺' },
  { level: 4, text: 'Порно-фильм', icon: '🎬' },
  { level: 4, text: 'Секс-шоп', icon: '🛍️' },
  { level: 4, text: 'Камасутра', icon: '📖' },
  { level: 4, text: 'Эротический массаж', icon: '💆' },
  { level: 4, text: 'Засос на шее', icon: '💋' },
  { level: 4, text: 'Поцелуй взасос', icon: '💋' },
  { level: 4, text: 'Обжиманья на танцполе', icon: '🕺' },
  { level: 4, text: 'Секс в самолёте', icon: '✈️' },
  { level: 4, text: 'Секс в примерочной', icon: '👗' },
  { level: 4, text: 'Быстрый секс в туалете клуба', icon: '🚪' },
  { level: 4, text: 'Утренний секс', icon: '🌅' },
  { level: 4, text: 'Оральный секс', icon: '👅' },
  { level: 4, text: 'Анальный секс', icon: '🍑' },
  { level: 4, text: 'Групповуха', icon: '👥' },
  { level: 4, text: 'Тройничок', icon: '👥' },
  { level: 4, text: 'Любовный треугольник', icon: '🔺' },
  { level: 4, text: 'Свидание из тиндера', icon: '📱' },
  { level: 4, text: 'Пикантная переписка', icon: '💬' },
  { level: 4, text: 'Секс по телефону', icon: '📞' },
  { level: 4, text: 'Виртуальный секс', icon: '💻' },
  { level: 4, text: 'Трусы на люстре', icon: '🩲' },
  { level: 4, text: 'Соблазнение начальника', icon: '💼' },
  { level: 4, text: 'Секретарша и босс', icon: '👔' },
  { level: 4, text: 'Стрип-покер', icon: '🃏' },
  { level: 4, text: 'Эротическое бельё', icon: '👙' },
  { level: 4, text: 'Прозрачная ночнушка', icon: '👗' },
  { level: 4, text: 'Пикантное фото в зеркале', icon: '🤳' },
  { level: 4, text: 'Домашнее видео', icon: '📹' },
  { level: 4, text: 'Камера в спальне', icon: '📷' },
  { level: 4, text: 'Ролевая игра «медсестра и пациент»', icon: '🩺' },
  { level: 4, text: 'Ролевая игра «учитель и ученица»', icon: '🍎' },
  { level: 4, text: 'Плётка', icon: '🪢' },
  { level: 4, text: 'Ошейник с поводком', icon: '🐕' },
  { level: 4, text: 'Кляп', icon: '🤐' },
  { level: 4, text: 'Связывание верёвками', icon: '🪢' },
  { level: 4, text: 'Секс с завязанными глазами', icon: '🎭' },
  { level: 4, text: 'Афродизиак', icon: '💊' },
  { level: 4, text: 'Возбуждающие капли', icon: '💧' },
  { level: 4, text: 'Смазка', icon: '💧' },
  { level: 4, text: 'Презерватив с ароматом', icon: '🍓' },
  { level: 4, text: 'Клубничка на теле партнёра', icon: '🍓' },
  { level: 4, text: 'Взбитые сливки в постели', icon: '🍦' },
  { level: 4, text: 'Мёд на теле', icon: '🍯' },
  { level: 4, text: 'Лёд в эротической игре', icon: '🧊' },
  { level: 4, text: 'Стриптиз на дне рождения', icon: '🎂' },
  { level: 4, text: 'Девичник со стриптизёром', icon: '💃' },
  { level: 4, text: 'Мальчишник в стрип-клубе', icon: '🕺' },
  { level: 4, text: 'Секс-марафон', icon: '🏃' },
  { level: 4, text: 'Ночь страсти в отеле', icon: '🏨' },
  { level: 4, text: 'Медовый месяц без остановок', icon: '🏝️' },
  { level: 4, text: 'Ревнивый партнёр застукал', icon: '😱' },
  { level: 4, text: 'Признание в измене', icon: '😢' },
  { level: 4, text: 'Скандал из-за смс от любовницы', icon: '📱' },
  { level: 4, text: 'Тайное свидание', icon: '🤫' },
  { level: 4, text: 'Роман на стороне', icon: '💔' },
  { level: 4, text: 'Соблазнительный танец у шеста', icon: '💃' },
  { level: 4, text: 'Лап-данс', icon: '💃' },
  { level: 4, text: 'Голая йога', icon: '🧘' },
  { level: 4, text: 'Нудистский пляж', icon: '🏖️' },
  { level: 4, text: 'Стриптиз-вечеринка', icon: '🎉' },
  { level: 4, text: 'Эротический квест', icon: '🔍' },
  { level: 4, text: 'Игра «правда или действие» на раздевание', icon: '🎲' },
  { level: 4, text: 'Бутылочка на поцелуи', icon: '🍾' },
  { level: 4, text: 'Фанты на раздевание', icon: '🎴' },
  { level: 4, text: 'Оральные ласки', icon: '👅' },
  { level: 4, text: 'Секс втроём', icon: '👥' },
  { level: 4, text: 'Ночь без белья', icon: '🌙' },
  { level: 4, text: 'Пикантный подарок на день рождения', icon: '🎁' },
  { level: 4, text: 'Секс-игрушка в подарок', icon: '🎀' },
  { level: 4, text: 'Возбуждение с первого взгляда', icon: '😍' },
  { level: 4, text: 'Флирт в баре', icon: '😉' },
  { level: 4, text: 'Знакомство в баре, закончившееся дома', icon: '🏠' },
  { level: 4, text: 'Утро после — не помнит имя', icon: '🤷' },
  { level: 4, text: 'Друзья с привилегиями', icon: '🤝' },
  { level: 4, text: 'Отношения на одну ночь', icon: '🌙' },
  { level: 4, text: 'Секс на пляже', icon: '🏖️' },
  { level: 4, text: 'Секс в бассейне', icon: '🏊' },
  { level: 4, text: 'Секс в душе', icon: '🚿' },
  { level: 4, text: 'Секс под одеялом при родителях', icon: '🤫' },
  { level: 4, text: 'Скрип кровати за стеной', icon: '🛏️' },
  { level: 4, text: 'Громкий стон соседки', icon: '🔊' },
  { level: 4, text: 'Эротический сон', icon: '💭' },
  { level: 4, text: 'Мокрый сон', icon: '💦' },
  { level: 4, text: 'Утренняя эрекция', icon: '🌅' },
  { level: 1, text: 'Носорог', icon: '🦏' },
  { level: 1, text: 'Бегемот', icon: '🦛' },
  { level: 1, text: 'Коала', icon: '🐨' },
  { level: 1, text: 'Ленивец', icon: '🦥' },
  { level: 1, text: 'Скунс', icon: '🦨' },
  { level: 1, text: 'Барсук', icon: '🦡' },
  { level: 1, text: 'Хомяк', icon: '🐹' },
  { level: 1, text: 'Морская свинка', icon: '🐹' },
  { level: 1, text: 'Индюк', icon: '🦃' },
  { level: 1, text: 'Гусь', icon: '🦢' },
  { level: 1, text: 'Утка', icon: '🦆' },
  { level: 1, text: 'Голубь', icon: '🕊️' },
  { level: 1, text: 'Ворона', icon: '🐦‍⬛' },
  { level: 1, text: 'Дятел', icon: '🐦' },
  { level: 1, text: 'Летучая мышь', icon: '🦇' },
  { level: 1, text: 'Крот', icon: '🕳️' },
  { level: 1, text: 'Выдра', icon: '🦦' },
  { level: 1, text: 'Бобр', icon: '🦫' },
  { level: 1, text: 'Тюлень', icon: '🦭' },
  { level: 1, text: 'Морж', icon: '🦭' },
  { level: 1, text: 'Акула', icon: '🦈' },
  { level: 1, text: 'Морской конёк', icon: '🐠' },
  { level: 1, text: 'Медуза', icon: '🪼' },
  { level: 1, text: 'Рак', icon: '🦞' },
  { level: 1, text: 'Жук', icon: '🪲' },
  { level: 1, text: 'Муравей', icon: '🐜' },
  { level: 1, text: 'Кузнечик', icon: '🦗' },
  { level: 1, text: 'Стрекоза', icon: '🦋' },
  { level: 1, text: 'Божья коровка', icon: '🐞' },
  { level: 1, text: 'Комар', icon: '🦟' },
  { level: 1, text: 'Ползать', icon: '🐛' },
  { level: 1, text: 'Кувыркаться', icon: '🤸' },
  { level: 1, text: 'Прятаться', icon: '🙈' },
  { level: 1, text: 'Искать', icon: '🔍' },
  { level: 1, text: 'Считать', icon: '🔢' },
  { level: 1, text: 'Смеяться', icon: '😂' },
  { level: 1, text: 'Плакать', icon: '😢' },
  { level: 1, text: 'Кричать', icon: '😱' },
  { level: 1, text: 'Шептать', icon: '🤫' },
  { level: 1, text: 'Зевать', icon: '🥱' },
  { level: 1, text: 'Обниматься', icon: '🤗' },
  { level: 1, text: 'Целоваться', icon: '😘' },
  { level: 1, text: 'Махать рукой', icon: '👋' },
  { level: 1, text: 'Хлопать в ладоши', icon: '👏' },
  { level: 1, text: 'Топать ногами', icon: '🦶' },
  { level: 1, text: 'Дуть на свечи', icon: '🎂' },
  { level: 1, text: 'Нюхать цветок', icon: '🌸' },
  { level: 1, text: 'Слушать музыку', icon: '🎵' },
  { level: 1, text: 'Смотреть мультфильм', icon: '📺' },
  { level: 1, text: 'Играть в прятки', icon: '🙈' },
  { level: 1, text: 'Ветеринар', icon: '🐾' },
  { level: 1, text: 'Строитель', icon: '👷' },
  { level: 1, text: 'Фермер', icon: '🚜' },
  { level: 1, text: 'Рыбак', icon: '🎣' },
  { level: 1, text: 'Лётчик', icon: '✈️' },
  { level: 1, text: 'Моряк', icon: '⚓' },
  { level: 1, text: 'Почтальон', icon: '📮' },
  { level: 1, text: 'Продавец', icon: '🛒' },
  { level: 1, text: 'Уборщик', icon: '🧹' },
  { level: 1, text: 'Садовник', icon: '🌱' },
  { level: 1, text: 'Библиотекарь', icon: '📚' },
  { level: 1, text: 'Дрессировщик', icon: '🐅' },
  { level: 1, text: 'Клоун', icon: '🤡' },
  { level: 1, text: 'Фокусник', icon: '🎩' },
  { level: 1, text: 'Дирижёр', icon: '🎼' },
  { level: 1, text: 'Балерина', icon: '🩰' },
  { level: 1, text: 'Акробат', icon: '🤸' },
  { level: 1, text: 'Мороженщик', icon: '🍦' },
  { level: 1, text: 'Смотритель зоопарка', icon: '🦁' },
  { level: 1, text: 'Пекарь', icon: '🥖' },
  { level: 1, text: 'Расчёска', icon: '💇' },
  { level: 1, text: 'Подушка', icon: '🛏️' },
  { level: 1, text: 'Одеяло', icon: '🛌' },
  { level: 1, text: 'Кастрюля', icon: '🍲' },
  { level: 1, text: 'Сковорода', icon: '🍳' },
  { level: 1, text: 'Ложка', icon: '🥄' },
  { level: 1, text: 'Вилка', icon: '🍴' },
  { level: 1, text: 'Тарелка', icon: '🍽️' },
  { level: 1, text: 'Чашка', icon: '☕' },
  { level: 1, text: 'Рюкзак', icon: '🎒' },
  { level: 1, text: 'Карандаш', icon: '✏️' },
  { level: 1, text: 'Ластик', icon: '🧽' },
  { level: 1, text: 'Линейка', icon: '📏' },
  { level: 1, text: 'Глобус', icon: '🌍' },
  { level: 1, text: 'Барабан', icon: '🥁' },
  { level: 1, text: 'Пианино', icon: '🎹' },
  { level: 1, text: 'Скрипка', icon: '🎻' },
  { level: 1, text: 'Флейта', icon: '🎶' },
  { level: 1, text: 'Труба', icon: '🎺' },
  { level: 1, text: 'Аккордеон', icon: '🪗' },
  { level: 1, text: 'Незнайка', icon: '🌟' },
  { level: 1, text: 'Карлсон', icon: '🎈' },
  { level: 1, text: 'Емеля', icon: '🪄' },
  { level: 1, text: 'Кот в сапогах', icon: '👢' },
  { level: 1, text: 'Аленький цветочек', icon: '🌺' },
  { level: 1, text: 'Курочка Ряба', icon: '🐔' },
  { level: 1, text: 'Теремок', icon: '🏠' },
  { level: 1, text: 'Гадкий утёнок', icon: '🦢' },
  { level: 1, text: 'Мальчик-с-пальчик', icon: '👦' },
  { level: 1, text: 'Спящая красавица', icon: '👸' },
  { level: 2, text: 'Донат в игре', icon: '💰' },
  { level: 2, text: 'Читер в игре', icon: '😡' },
  { level: 2, text: 'Лаги в игре', icon: '🐢' },
  { level: 2, text: 'Обновление игры', icon: '🔄' },
  { level: 2, text: 'Ливень багов', icon: '🐛' },
  { level: 2, text: 'Стрим на Твиче', icon: '🎮' },
  { level: 2, text: 'Подписчики в тиктоке', icon: '📈' },
  { level: 2, text: 'Хайп в чате', icon: '🔥' },
  { level: 2, text: 'Виртуальный питомец', icon: '🐾' },
  { level: 2, text: 'VR-очки', icon: '🥽' },
  { level: 2, text: 'Сторис в инстаграме', icon: '📸' },
  { level: 2, text: 'Фильтр на лицо', icon: '🫥' },
  { level: 2, text: 'Прямой эфир', icon: '📡' },
  { level: 2, text: 'Дизлайк', icon: '👎' },
  { level: 2, text: 'Бан в чате', icon: '🚫' },
  { level: 2, text: 'Скриншот переписки', icon: '📱' },
  { level: 2, text: 'Голосовое сообщение', icon: '🎙️' },
  { level: 2, text: 'Смайлик в переписке', icon: '😊' },
  { level: 2, text: 'Групповой чат', icon: '👥' },
  { level: 2, text: 'Аватарка', icon: '🖼️' },
  { level: 2, text: 'Волейбольная подача', icon: '🏐' },
  { level: 2, text: 'Гандбольный бросок', icon: '🤾' },
  { level: 2, text: 'Плавание брассом', icon: '🏊' },
  { level: 2, text: 'Лёгкая атлетика', icon: '🏃' },
  { level: 2, text: 'Настольный теннис', icon: '🏓' },
  { level: 2, text: 'Бадминтон', icon: '🏸' },
  { level: 2, text: 'Дзюдо', icon: '🥋' },
  { level: 2, text: 'Карате', icon: '🥋' },
  { level: 2, text: 'Фехтование', icon: '🤺' },
  { level: 2, text: 'Гимнастика на бревне', icon: '🤸' },
  { level: 2, text: 'Ниндзя крадётся', icon: '🥷' },
  { level: 2, text: 'Волшебник колдует', icon: '🧙' },
  { level: 2, text: 'Эльф стреляет из лука', icon: '🧝' },
  { level: 2, text: 'Гоблин ворует', icon: '👺' },
  { level: 2, text: 'Тролль под мостом', icon: '🧌' },
  { level: 2, text: 'Русалка плывёт', icon: '🧜' },
  { level: 2, text: 'Единорог скачет', icon: '🦄' },
  { level: 2, text: 'Фея летает', icon: '🧚' },
  { level: 2, text: 'Титан разрушает', icon: '🤖' },
  { level: 2, text: 'Мутант с суперсилой', icon: '🧟' },
  { level: 2, text: 'Смущение от комплимента', icon: '😊' },
  { level: 2, text: 'Стыд за опоздание', icon: '😳' },
  { level: 2, text: 'Радость от пятёрки', icon: '😄' },
  { level: 2, text: 'Грусть от расставания', icon: '😢' },
  { level: 2, text: 'Страх перед сценой', icon: '😰' },
  { level: 2, text: 'Азарт на соревновании', icon: '😆' },
  { level: 2, text: 'Нетерпение перед каникулами', icon: '😩' },
  { level: 2, text: 'Разочарование в друге', icon: '😞' },
  { level: 2, text: 'Вдохновение от фильма', icon: '🤩' },
  { level: 2, text: 'Ностальгия по детству', icon: '🥹' },
  { level: 2, text: 'Рисование аниме', icon: '🎨' },
  { level: 2, text: 'Игра на барабанах', icon: '🥁' },
  { level: 2, text: 'Сборка кубика Рубика', icon: '🧩' },
  { level: 2, text: 'Скейт-трюк', icon: '🛹' },
  { level: 2, text: 'Паркур', icon: '🏃' },
  { level: 2, text: 'Йога для начинающих', icon: '🧘' },
  { level: 2, text: 'Ведение личного дневника', icon: '📓' },
  { level: 2, text: 'Коллаж из фотографий', icon: '🖼️' },
  { level: 2, text: 'Оригами', icon: '📄' },
  { level: 2, text: 'Вязание крючком', icon: '🧶' },
  { level: 2, text: 'Пижамная вечеринка', icon: '🛌' },
  { level: 2, text: 'Ночёвка у подруги', icon: '🎉' },
  { level: 2, text: 'Караоке-батл', icon: '🎤' },
  { level: 2, text: 'Квиз на эрудицию', icon: '🧠' },
  { level: 2, text: 'Боулинг с классом', icon: '🎳' },
  { level: 2, text: 'Пикник у озера', icon: '🏞️' },
  { level: 2, text: 'Велопрогулка компанией', icon: '🚴' },
  { level: 2, text: 'Игра в мафию', icon: '🕵️' },
  { level: 2, text: 'Настольный хоккей', icon: '🏒' },
  { level: 2, text: 'Игра в фанты', icon: '🎲' },
  { level: 2, text: 'Ютубер снимает влог', icon: '📹' },
  { level: 2, text: 'Тиктокер танцует тренд', icon: '💃' },
  { level: 2, text: 'Диджитал-художник рисует', icon: '🖌️' },
  { level: 2, text: 'Комик выступает', icon: '😂' },
  { level: 2, text: 'Модератор чата банит', icon: '🚫' },
  { level: 2, text: 'Организатор вечеринки', icon: '🎪' },
  { level: 2, text: 'Фотомодель позирует', icon: '📸' },
  { level: 2, text: 'Диджей включает трек', icon: '🎧' },
  { level: 2, text: 'Рэпер читает куплет', icon: '🎤' },
  { level: 2, text: 'Косплеер в костюме', icon: '🎭' },
  { level: 2, text: 'Разбитый экран телефона', icon: '📱' },
  { level: 2, text: 'Севшая батарейка наушников', icon: '🔋' },
  { level: 2, text: 'Забытая тетрадь дома', icon: '📓' },
  { level: 2, text: 'Опоздание на автобус', icon: '🚌' },
  { level: 2, text: 'Промокшие кроссовки', icon: '👟' },
  { level: 2, text: 'Порванные джинсы', icon: '👖' },
  { level: 2, text: 'Потерянный кошелёк', icon: '👛' },
  { level: 2, text: 'Сломанный зонт', icon: '☂️' },
  { level: 2, text: 'Разлитый сок на клавиатуру', icon: '💦' },
  { level: 2, text: 'Застрявший лифт', icon: '🛗' },
  { level: 2, text: 'Первая влюблённость', icon: '💘' },
  { level: 2, text: 'Записка с признанием', icon: '💌' },
  { level: 2, text: 'Совместный проект в школе', icon: '📚' },
  { level: 2, text: 'Ссора из-за игры', icon: '😤' },
  { level: 2, text: 'Дружба по переписке', icon: '✉️' },
  { level: 2, text: 'Секретный поклонник', icon: '🕵️' },
  { level: 2, text: 'Букет на 8 марта', icon: '💐' },
  { level: 2, text: 'Валентинка', icon: '💝' },
  { level: 2, text: 'Слёзы после фильма', icon: '😭' },
  { level: 2, text: 'Смех до слёз', icon: '😂' },
  { level: 3, text: 'Онлайн-знакомство', icon: '💻' },
  { level: 3, text: 'Свидание в дождь', icon: '🌧️' },
  { level: 3, text: 'Ревность в соцсетях', icon: '📵' },
  { level: 3, text: 'Совместный отпуск впервые', icon: '✈️' },
  { level: 3, text: 'Помолвочное кольцо', icon: '💍' },
  { level: 3, text: 'Родители знакомятся', icon: '👨‍👩‍👧' },
  { level: 3, text: 'Свадебное платье', icon: '👗' },
  { level: 3, text: 'Мальчишник в бане', icon: '🧖' },
  { level: 3, text: 'Годовщина свадьбы', icon: '🎉' },
  { level: 3, text: 'Расставание по переписке', icon: '💔' },
  { level: 3, text: 'Дедлайн в пятницу вечером', icon: '😩' },
  { level: 3, text: 'Токсичный коллега', icon: '🙄' },
  { level: 3, text: 'Планёрка в понедельник', icon: '📅' },
  { level: 3, text: 'Опоздание на важную встречу', icon: '🏃' },
  { level: 3, text: 'Премия в конце года', icon: '💵' },
  { level: 3, text: 'Больничный лист', icon: '🤒' },
  { level: 3, text: 'Рабочая командировка', icon: '🧳' },
  { level: 3, text: 'Совещание в зуме зависает', icon: '💻' },
  { level: 3, text: 'Отпуск за свой счёт', icon: '🌴' },
  { level: 3, text: 'Работа мечты', icon: '✨' },
  { level: 3, text: 'Шампанское на юбилее', icon: '🍾' },
  { level: 3, text: 'Похмельный понедельник', icon: '🤕' },
  { level: 3, text: 'Дегустация пива', icon: '🍺' },
  { level: 3, text: 'Барная стойка', icon: '🍸' },
  { level: 3, text: 'Коктейль на пляже', icon: '🍹' },
  { level: 3, text: 'Тост за здоровье', icon: '🥂' },
  { level: 3, text: 'Вечеринка в стиле 90-х', icon: '🕺' },
  { level: 3, text: 'Салют на Новый год', icon: '🎆' },
  { level: 3, text: 'Танцы до утра', icon: '💃' },
  { level: 3, text: 'Застолье большой компанией', icon: '🍽️' },
  { level: 3, text: 'Первая ссора молодожёнов', icon: '😤' },
  { level: 3, text: 'Совместные покупки в магазине', icon: '🛒' },
  { level: 3, text: 'Уборка по расписанию', icon: '🧹' },
  { level: 3, text: 'Свекровь даёт советы', icon: '👵' },
  { level: 3, text: 'Домашние обязанности пополам', icon: '🏠' },
  { level: 3, text: 'Воскресный обед у родителей', icon: '🍽️' },
  { level: 3, text: 'Планирование семейного бюджета', icon: '💰' },
  { level: 3, text: 'Ремонт своими руками', icon: '🔨' },
  { level: 3, text: 'Выбор имени для ребёнка', icon: '👶' },
  { level: 3, text: 'Семейный поход в зоопарк', icon: '🦒' },
  { level: 3, text: 'Утренняя зарядка через силу', icon: '🤸' },
  { level: 3, text: 'Поход в спортзал через силу', icon: '🏋️' },
  { level: 3, text: 'Первая пара очков', icon: '👓' },
  { level: 3, text: 'Боль в колене после пробежки', icon: '🦵' },
  { level: 3, text: 'Диспансеризация', icon: '🏥' },
  { level: 3, text: 'Отказ от сладкого', icon: '🍫' },
  { level: 3, text: 'Бессонница из-за забот', icon: '😵' },
  { level: 3, text: 'Массаж после тяжёлого дня', icon: '💆' },
  { level: 3, text: 'Правильное питание', icon: '🥗' },
  { level: 3, text: 'Стресс на работе', icon: '😩' },
  { level: 3, text: 'Соседи шумят допоздна', icon: '🔊' },
  { level: 3, text: 'Пробка на МКАДе', icon: '🚗' },
  { level: 3, text: 'Забытый зонт под дождём', icon: '☔' },
  { level: 3, text: 'Сломанный каблук', icon: '👠' },
  { level: 3, text: 'Испорченный маникюр', icon: '💅' },
  { level: 3, text: 'Долгая очередь в банке', icon: '🏦' },
  { level: 3, text: 'Штраф за парковку', icon: '🎫' },
  { level: 3, text: 'Разряженный ноутбук на встрече', icon: '💻' },
  { level: 3, text: 'Спам в почте', icon: '📧' },
  { level: 3, text: 'Забытый день рождения друга', icon: '🎂' },
  { level: 3, text: 'Отель all inclusive', icon: '🏨' },
  { level: 3, text: 'Экскурсия с гидом', icon: '🗺️' },
  { level: 3, text: 'Потерянный багаж в аэропорту', icon: '🧳' },
  { level: 3, text: 'Загранпаспорт на границе', icon: '🛂' },
  { level: 3, text: 'Пляжный волейбол в отпуске', icon: '🏐' },
  { level: 3, text: 'Дегустация местной кухни', icon: '🍜' },
  { level: 3, text: 'Сувениры из отпуска', icon: '🎁' },
  { level: 3, text: 'Фотосессия на фоне заката', icon: '📸' },
  { level: 3, text: 'Поход с палатками', icon: '⛺' },
  { level: 3, text: 'Рыбалка на рассвете', icon: '🎣' },
  { level: 3, text: 'Ставка на спорт', icon: '💵' },
  { level: 3, text: 'Рулетка в казино', icon: '🎰' },
  { level: 3, text: 'Покерфейс', icon: '🃏' },
  { level: 3, text: 'Дартс в баре', icon: '🎯' },
  { level: 3, text: 'Настольный футбол', icon: '⚽' },
  { level: 3, text: 'Викторина в баре', icon: '🍻' },
  { level: 3, text: 'Шахматный турнир', icon: '♟️' },
  { level: 3, text: 'Бильярдный удар в лузу', icon: '🎱' },
  { level: 3, text: 'Домино во дворе', icon: '🁉' },
  { level: 3, text: 'Нарды с друзьями', icon: '🎲' },
  { level: 3, text: 'Стоматолог сверлит зуб', icon: '🦷' },
  { level: 3, text: 'Парикмахер стрижёт клиента', icon: '💇' },
  { level: 3, text: 'Косметолог делает процедуру', icon: '💅' },
  { level: 3, text: 'Автомеханик под капотом', icon: '🔧' },
  { level: 3, text: 'Электрик чинит проводку', icon: '🔌' },
  { level: 3, text: 'Сантехник в квартире', icon: '🚿' },
  { level: 3, text: 'Курьер с доставкой', icon: '📦' },
  { level: 3, text: 'Продавец-консультант', icon: '🛍️' },
  { level: 3, text: 'Бухгалтер сводит баланс', icon: '📊' },
  { level: 3, text: 'Директор на планёрке', icon: '👔' },
  { level: 3, text: 'Утренний кофе перед работой', icon: '☕' },
  { level: 3, text: 'Пробуждение будильником в 6 утра', icon: '⏰' },
  { level: 3, text: 'Очередь в поликлинику к терапевту', icon: '🏥' },
  { level: 3, text: 'Ипотечный платёж', icon: '💳' },
  { level: 3, text: 'Автосервис и ожидание', icon: '🚗' },
  { level: 3, text: 'Родительское собрание в школе', icon: '🏫' },
  { level: 3, text: 'Выбор детского сада', icon: '🧸' },
  { level: 3, text: 'Совместный отдых с друзьями семьи', icon: '👨‍👩‍👧‍👦' },
  { level: 3, text: 'Юбилей на работе', icon: '🎉' },
  { level: 3, text: 'Пенсия родителей', icon: '👴' },
  { level: 4, text: 'Секс на кухне', icon: '🍳' },
  { level: 4, text: 'Секс в лифте', icon: '🛗' },
  { level: 4, text: 'Секс в машине', icon: '🚗' },
  { level: 4, text: 'Секс на балконе', icon: '🌃' },
  { level: 4, text: 'Секс в палатке', icon: '⛺' },
  { level: 4, text: 'Секс в бассейне ночью', icon: '🌙' },
  { level: 4, text: 'Секс на пляже под луной', icon: '🌊' },
  { level: 4, text: 'Секс в примерочной кабинке', icon: '👗' },
  { level: 4, text: 'Секс перед зеркалом', icon: '🪞' },
  { level: 4, text: 'Секс в отеле', icon: '🏨' },
  { level: 4, text: 'Ролевая игра «доктор и пациентка»', icon: '👨‍⚕️' },
  { level: 4, text: 'Ролевая игра «начальник и секретарша»', icon: '💼' },
  { level: 4, text: 'Ролевая игра «полицейский и нарушительница»', icon: '👮' },
  { level: 4, text: 'Ролевая игра «горничная»', icon: '🧹' },
  { level: 4, text: 'Костюм зайки', icon: '🐰' },
  { level: 4, text: 'Костюм кошечки', icon: '🐱' },
  { level: 4, text: 'Латексный костюм', icon: '🖤' },
  { level: 4, text: 'Чулки и пояс', icon: '🧦' },
  { level: 4, text: 'Кружевное бельё', icon: '🎀' },
  { level: 4, text: 'Прозрачный пеньюар', icon: '👘' },
  { level: 4, text: 'Массажное масло', icon: '🕯️' },
  { level: 4, text: 'Свечи и вино', icon: '🍷' },
  { level: 4, text: 'Лепестки роз на кровати', icon: '🌹' },
  { level: 4, text: 'Игра в стрип-бильярд', icon: '🎱' },
  { level: 4, text: 'Игра в стрип-твистер', icon: '🕸️' },
  { level: 4, text: 'Эротическая фотосессия', icon: '📷' },
  { level: 4, text: 'Селфи в белье', icon: '🤳' },
  { level: 4, text: 'Пикантное видео на телефон', icon: '📱' },
  { level: 4, text: 'Флирт по переписке', icon: '💬' },
  { level: 4, text: 'Секс-переписка перед встречей', icon: '📲' },
  { level: 4, text: 'Возбуждающая музыка', icon: '🎶' },
  { level: 4, text: 'Танец на коленях', icon: '💃' },
  { level: 4, text: 'Стриптиз под дождём', icon: '🌧️' },
  { level: 4, text: 'Обольщение в баре', icon: '🍸' },
  { level: 4, text: 'Флирт с барменом', icon: '🍹' },
  { level: 4, text: 'Ревнивая сцена', icon: '😠' },
  { level: 4, text: 'Тайный роман на работе', icon: '🤫' },
  { level: 4, text: 'Служебный роман', icon: '💼' },
  { level: 4, text: 'Секс на корпоративе', icon: '🎉' },
  { level: 4, text: 'Поцелуй в лифте офиса', icon: '🛗' },
  { level: 4, text: 'Оргазм от массажа', icon: '💆' },
  { level: 4, text: 'Множественный оргазм', icon: '💥' },
  { level: 4, text: 'Затяжные прелюдии', icon: '⏳' },
  { level: 4, text: 'Долгая прелюдия', icon: '⏱️' },
  { level: 4, text: 'Быстрый перепихон', icon: '⚡' },
  { level: 4, text: 'Секс на бегу перед работой', icon: '🏃' },
  { level: 4, text: 'Утренняя близость', icon: '🌅' },
  { level: 4, text: 'Ночь без сна от страсти', icon: '🌙' },
  { level: 4, text: 'Секс после ссоры', icon: '😤' },
  { level: 4, text: 'Примирительный секс', icon: '🤝' },
  { level: 4, text: 'Игрушка для двоих', icon: '🎁' },
  { level: 4, text: 'Кольцо для эрекции', icon: '💍' },
  { level: 4, text: 'Анальная пробка', icon: '🍑' },
  { level: 4, text: 'Вагинальные шарики', icon: '⚪' },
  { level: 4, text: 'Эрекционное кольцо с вибрацией', icon: '💍' },
  { level: 4, text: 'Секс-качели', icon: '🪑' },
  { level: 4, text: 'Подвесные наручники', icon: '⛓️' },
  { level: 4, text: 'Верёвочное искусство шибари', icon: '🪢' },
  { level: 4, text: 'Игра в господина и рабыню', icon: '👑' },
  { level: 4, text: 'Спанкинг', icon: '✋' },
  { level: 4, text: 'Дразнилка и отказ', icon: '😏' },
  { level: 4, text: 'Оральная ласка стоя', icon: '🧎' },
  { level: 4, text: 'Секс стоя у стены', icon: '🧱' },
  { level: 4, text: 'Секс в позе наездницы', icon: '🤠' },
  { level: 4, text: 'Секс сзади', icon: '🔄' },
  { level: 4, text: 'Секс лицом к лицу', icon: '🔁' },
  { level: 4, text: 'Смена поз посреди акта', icon: '😮‍💨' },
  { level: 4, text: 'Секс на грани оргазма и остановка', icon: '🎢' },
  { level: 4, text: 'Продление возбуждения эджингом', icon: '🏁' },
  { level: 4, text: 'Совместный оргазм', icon: '🎯' },
  { level: 4, text: 'Порно на большом экране', icon: '📺' },
  { level: 4, text: 'Просмотр порно вместе', icon: '🍿' },
  { level: 4, text: 'Обсуждение фантазий вслух', icon: '💬' },
  { level: 4, text: 'Список желаний в постели', icon: '📝' },
  { level: 4, text: 'Список того, что хочется попробовать', icon: '📋' },
  { level: 4, text: 'Ролевая игра «незнакомцы в баре»', icon: '🚪' },
  { level: 4, text: 'Ролевая игра «доставка пиццы»', icon: '🍕' },
  { level: 4, text: 'Ролевая игра «сосед зашёл за солью»', icon: '🏠' },
  { level: 4, text: 'Эротический массаж маслом', icon: '💆' },
  { level: 4, text: 'Массаж с завязанными глазами', icon: '🙈' },
  { level: 4, text: 'Секс под открытым небом', icon: '🌌' },
  { level: 4, text: 'Секс в лесу', icon: '🌲' },
  { level: 4, text: 'Секс в поезде', icon: '🚂' },
  { level: 4, text: 'Секс в самолёте бизнес-класса', icon: '✈️' },
  { level: 4, text: 'Секс на крыше', icon: '🏙️' },
  { level: 4, text: 'Секс в джакузи', icon: '🛁' },
  { level: 4, text: 'Секс в сауне', icon: '🧖' },
  { level: 4, text: 'Секс в раздевалке спортзала', icon: '👗' },
  { level: 4, text: 'Секс на заднем сиденье такси', icon: '🚕' },
  { level: 4, text: 'Быстрый секс в кладовке на вечеринке', icon: '🗄️' },
  { level: 4, text: 'Признание в фантазии', icon: '💭' },
  { level: 4, text: 'Секс-игра «правда или действие» для двоих', icon: '🎯' },
  { level: 4, text: 'Обмен эротическими фото', icon: '📸' },
  { level: 4, text: 'Голосовое сообщение со стонами', icon: '🎙️' },
  { level: 4, text: 'Флирт на расстоянии', icon: '📶' },
  { level: 4, text: 'Сообщение «скучаю и хочу тебя»', icon: '💌' },
  { level: 4, text: 'Возвращение с работы и сразу в постель', icon: '🏃' },
  { level: 4, text: 'Секс перед сном', icon: '🛏️' },
  { level: 4, text: 'Секс сразу после пробуждения', icon: '🌄' },
  { level: 4, text: 'Долгие объятия после секса', icon: '🤗' },

  // ---------- РЕЖИМ "СЛОВО": только одиночные существительные ----------
  // 50 новых слов на каждый уровень (200 всего), с тем же уровнем сложности
  // тематики, что и обычные карточки того же level. Помечены mode:"word",
  // чтобы фильтр режима "Слово" отбирал только их (см. getKrCardsList).
  // --- Уровень 1 ---
  { level: 1, text: 'Радуга', icon: '🌈', mode: 'word' },
  { level: 1, text: 'Облако', icon: '☁️', mode: 'word' },
  { level: 1, text: 'Дождь', icon: '🌧️', mode: 'word' },
  { level: 1, text: 'Снег', icon: '❄️', mode: 'word' },
  { level: 1, text: 'Солнце', icon: '☀️', mode: 'word' },
  { level: 1, text: 'Луна', icon: '🌙', mode: 'word' },
  { level: 1, text: 'Звезда', icon: '⭐', mode: 'word' },
  { level: 1, text: 'Ракета', icon: '🚀', mode: 'word' },
  { level: 1, text: 'Самолёт', icon: '✈️', mode: 'word' },
  { level: 1, text: 'Поезд', icon: '🚂', mode: 'word' },
  { level: 1, text: 'Корабль', icon: '🚢', mode: 'word' },
  { level: 1, text: 'Машина', icon: '🚗', mode: 'word' },
  { level: 1, text: 'Автобус', icon: '🚌', mode: 'word' },
  { level: 1, text: 'Трамвай', icon: '🚋', mode: 'word' },
  { level: 1, text: 'Метро', icon: '🚇', mode: 'word' },
  { level: 1, text: 'Лифт', icon: '🛗', mode: 'word' },
  { level: 1, text: 'Лестница', icon: '🪜', mode: 'word' },
  { level: 1, text: 'Дверь', icon: '🚪', mode: 'word' },
  { level: 1, text: 'Окно', icon: '🪟', mode: 'word' },
  { level: 1, text: 'Стол', icon: '🍽️', mode: 'word' },
  { level: 1, text: 'Стул', icon: '🪑', mode: 'word' },
  { level: 1, text: 'Диван', icon: '🛋️', mode: 'word' },
  { level: 1, text: 'Шкаф', icon: '🗄️', mode: 'word' },
  { level: 1, text: 'Ковёр', icon: '🟫', mode: 'word' },
  { level: 1, text: 'Лампа', icon: '💡', mode: 'word' },
  { level: 1, text: 'Свеча', icon: '🕯️', mode: 'word' },
  { level: 1, text: 'Ваза', icon: '🏺', mode: 'word' },
  { level: 1, text: 'Книга', icon: '📕', mode: 'word' },
  { level: 1, text: 'Тетрадь', icon: '📓', mode: 'word' },
  { level: 1, text: 'Пенал', icon: '🖊️', mode: 'word' },
  { level: 1, text: 'Портфель', icon: '💼', mode: 'word' },
  { level: 1, text: 'Мяч', icon: '⚽', mode: 'word' },
  { level: 1, text: 'Кукла', icon: '🪆', mode: 'word' },
  { level: 1, text: 'Робот', icon: '🤖', mode: 'word' },
  { level: 1, text: 'Пазл', icon: '🧩', mode: 'word' },
  { level: 1, text: 'Кубики', icon: '🧱', mode: 'word' },
  { level: 1, text: 'Юла', icon: '🌀', mode: 'word' },
  { level: 1, text: 'Качели', icon: '🛝', mode: 'word' },
  { level: 1, text: 'Горка', icon: '🛝', mode: 'word' },
  { level: 1, text: 'Песочница', icon: '🏖️', mode: 'word' },
  { level: 1, text: 'Батут', icon: '🤸', mode: 'word' },
  { level: 1, text: 'Скакалка', icon: '🪢', mode: 'word' },
  { level: 1, text: 'Самокат', icon: '🛴', mode: 'word' },
  { level: 1, text: 'Ролики', icon: '🛼', mode: 'word' },
  { level: 1, text: 'Коньки', icon: '⛸️', mode: 'word' },
  { level: 1, text: 'Лыжи', icon: '🎿', mode: 'word' },
  { level: 1, text: 'Санки', icon: '🛷', mode: 'word' },
  { level: 1, text: 'Шапка', icon: '🧢', mode: 'word' },
  { level: 1, text: 'Шарф', icon: '🧣', mode: 'word' },
  { level: 1, text: 'Перчатки', icon: '🧤', mode: 'word' },
  // --- Уровень 2 ---
  { level: 2, text: 'Смартфон', icon: '📱', mode: 'word' },
  { level: 2, text: 'Наушники', icon: '🎧', mode: 'word' },
  { level: 2, text: 'Кроссовки', icon: '👟', mode: 'word' },
  { level: 2, text: 'Худи', icon: '🧥', mode: 'word' },
  { level: 2, text: 'Кепка', icon: '🧢', mode: 'word' },
  { level: 2, text: 'Планшет', icon: '📱', mode: 'word' },
  { level: 2, text: 'Пауэрбанк', icon: '🔋', mode: 'word' },
  { level: 2, text: 'Плеер', icon: '🎵', mode: 'word' },
  { level: 2, text: 'Мопед', icon: '🛵', mode: 'word' },
  { level: 2, text: 'Значок', icon: '📛', mode: 'word' },
  { level: 2, text: 'Стикер', icon: '🏷️', mode: 'word' },
  { level: 2, text: 'Чехол', icon: '📱', mode: 'word' },
  { level: 2, text: 'Клавиатура', icon: '⌨️', mode: 'word' },
  { level: 2, text: 'Мышка', icon: '🖱️', mode: 'word' },
  { level: 2, text: 'Провод', icon: '🔌', mode: 'word' },
  { level: 2, text: 'Мороженое', icon: '🍦', mode: 'word' },
  { level: 2, text: 'Пицца', icon: '🍕', mode: 'word' },
  { level: 2, text: 'Бургер', icon: '🍔', mode: 'word' },
  { level: 2, text: 'Матрас', icon: '🛏️', mode: 'word' },
  { level: 2, text: 'Штаны', icon: '👖', mode: 'word' },
  { level: 2, text: 'Скейт', icon: '🛹', mode: 'word' },
  { level: 2, text: 'Косуха', icon: '🧥', mode: 'word' },
  { level: 2, text: 'Кеды', icon: '👟', mode: 'word' },
  { level: 2, text: 'Гитара', icon: '🎸', mode: 'word' },
  { level: 2, text: 'Барабанщик', icon: '🥁', mode: 'word' },
  { level: 2, text: 'Микрофон', icon: '🎤', mode: 'word' },
  { level: 2, text: 'Колонка', icon: '🔊', mode: 'word' },
  { level: 2, text: 'Проектор', icon: '📽️', mode: 'word' },
  { level: 2, text: 'Учебник', icon: '📘', mode: 'word' },
  { level: 2, text: 'Форма', icon: '👕', mode: 'word' },
  { level: 2, text: 'Кулон', icon: '📿', mode: 'word' },
  { level: 2, text: 'Пирсинг', icon: '💎', mode: 'word' },
  { level: 2, text: 'Тату', icon: '🖋️', mode: 'word' },
  { level: 2, text: 'Веснушки', icon: '🙂', mode: 'word' },
  { level: 2, text: 'Брекеты', icon: '😬', mode: 'word' },
  { level: 2, text: 'Чипсы', icon: '🥔', mode: 'word' },
  { level: 2, text: 'Газировка', icon: '🥤', mode: 'word' },
  { level: 2, text: 'Энергетик', icon: '⚡', mode: 'word' },
  { level: 2, text: 'Жвачка', icon: '🍬', mode: 'word' },
  { level: 2, text: 'Леденец', icon: '🍭', mode: 'word' },
  { level: 2, text: 'Комикс', icon: '📚', mode: 'word' },
  { level: 2, text: 'Гироскутер', icon: '🛴', mode: 'word' },
  { level: 2, text: 'Пульт', icon: '🎮', mode: 'word' },
  { level: 2, text: 'Джойстик', icon: '🎮', mode: 'word' },
  { level: 2, text: 'Свисток', icon: '📯', mode: 'word' },
  { level: 2, text: 'Рогатка', icon: '🎯', mode: 'word' },
  { level: 2, text: 'Магнит', icon: '🧲', mode: 'word' },
  { level: 2, text: 'Батарейка', icon: '🔋', mode: 'word' },
  { level: 2, text: 'Розетка', icon: '🔌', mode: 'word' },
  { level: 2, text: 'Браслет', icon: '📿', mode: 'word' },
  // --- Уровень 3 ---
  { level: 3, text: 'Помада', icon: '💄', mode: 'word' },
  { level: 3, text: 'Духи', icon: '🧴', mode: 'word' },
  { level: 3, text: 'Каблуки', icon: '👠', mode: 'word' },
  { level: 3, text: 'Галстук', icon: '👔', mode: 'word' },
  { level: 3, text: 'Кольцо', icon: '💍', mode: 'word' },
  { level: 3, text: 'Букет', icon: '💐', mode: 'word' },
  { level: 3, text: 'Диплом', icon: '🎓', mode: 'word' },
  { level: 3, text: 'Виза', icon: '🛂', mode: 'word' },
  { level: 3, text: 'Зарплата', icon: '💰', mode: 'word' },
  { level: 3, text: 'Премия', icon: '💵', mode: 'word' },
  { level: 3, text: 'Начальник', icon: '👔', mode: 'word' },
  { level: 3, text: 'Коллега', icon: '🧑‍💼', mode: 'word' },
  { level: 3, text: 'Отпуск', icon: '🏖️', mode: 'word' },
  { level: 3, text: 'Больничный', icon: '🤒', mode: 'word' },
  { level: 3, text: 'Термос', icon: '🧉', mode: 'word' },
  { level: 3, text: 'Чемодан', icon: '🧳', mode: 'word' },
  { level: 3, text: 'Билет', icon: '🎫', mode: 'word' },
  { level: 3, text: 'Виски', icon: '🥃', mode: 'word' },
  { level: 3, text: 'Коктейль', icon: '🍹', mode: 'word' },
  { level: 3, text: 'Шампанское', icon: '🍾', mode: 'word' },
  { level: 3, text: 'Бокал', icon: '🍷', mode: 'word' },
  { level: 3, text: 'Сигара', icon: '🚬', mode: 'word' },
  { level: 3, text: 'Крупье', icon: '🎰', mode: 'word' },
  { level: 3, text: 'Рулетка', icon: '🎡', mode: 'word' },
  { level: 3, text: 'Фишки', icon: '🎲', mode: 'word' },
  { level: 3, text: 'Покер', icon: '🃏', mode: 'word' },
  { level: 3, text: 'Дартс', icon: '🎯', mode: 'word' },
  { level: 3, text: 'Кий', icon: '🎱', mode: 'word' },
  { level: 3, text: 'Фата', icon: '👰', mode: 'word' },
  { level: 3, text: 'Тамада', icon: '🎤', mode: 'word' },
  { level: 3, text: 'Лимузин', icon: '🚙', mode: 'word' },
  { level: 3, text: 'Массажист', icon: '💆', mode: 'word' },
  { level: 3, text: 'Тренажёр', icon: '🏋️', mode: 'word' },
  { level: 3, text: 'Гантели', icon: '🏋️', mode: 'word' },
  { level: 3, text: 'Пилатес', icon: '🧘', mode: 'word' },
  { level: 3, text: 'Весы', icon: '⚖️', mode: 'word' },
  { level: 3, text: 'Витамины', icon: '💊', mode: 'word' },
  { level: 3, text: 'Термометр', icon: '🌡️', mode: 'word' },
  { level: 3, text: 'Рассрочка', icon: '💳', mode: 'word' },
  { level: 3, text: 'Ломбард', icon: '💰', mode: 'word' },
  { level: 3, text: 'Нотариус', icon: '📜', mode: 'word' },
  { level: 3, text: 'Риелтор', icon: '🏠', mode: 'word' },
  { level: 3, text: 'Аллергия', icon: '🤧', mode: 'word' },
  { level: 3, text: 'Гастрит', icon: '🤕', mode: 'word' },
  { level: 3, text: 'Изжога', icon: '🔥', mode: 'word' },
  { level: 3, text: 'Мигрень', icon: '🤕', mode: 'word' },
  { level: 3, text: 'Радикулит', icon: '🦴', mode: 'word' },
  { level: 3, text: 'Целлюлит', icon: '🍑', mode: 'word' },
  { level: 3, text: 'Загранпаспорт', icon: '🛂', mode: 'word' },
  { level: 3, text: 'Ипотечник', icon: '💳', mode: 'word' },
  // --- Уровень 4 ---
  { level: 4, text: 'Фетиш', icon: '😈', mode: 'word' },
  { level: 4, text: 'Доминант', icon: '👑', mode: 'word' },
  { level: 4, text: 'Сабмиссив', icon: '⛓️', mode: 'word' },
  { level: 4, text: 'Плейбой', icon: '😏', mode: 'word' },
  { level: 4, text: 'Эскорт', icon: '💋', mode: 'word' },
  { level: 4, text: 'Гарем', icon: '👑', mode: 'word' },
  { level: 4, text: 'Кокетка', icon: '😉', mode: 'word' },
  { level: 4, text: 'Соблазн', icon: '😏', mode: 'word' },
  { level: 4, text: 'Искушение', icon: '🍎', mode: 'word' },
  { level: 4, text: 'Табу', icon: '🚫', mode: 'word' },
  { level: 4, text: 'Вожделение', icon: '🔥', mode: 'word' },
  { level: 4, text: 'Экстаз', icon: '😩', mode: 'word' },
  { level: 4, text: 'Страсть', icon: '🔥', mode: 'word' },
  { level: 4, text: 'Влечение', icon: '💘', mode: 'word' },
  { level: 4, text: 'Похоть', icon: '😈', mode: 'word' },
  { level: 4, text: 'Разврат', icon: '😈', mode: 'word' },
  { level: 4, text: 'Нагота', icon: '🙈', mode: 'word' },
  { level: 4, text: 'Разрядка', icon: '💥', mode: 'word' },
  { level: 4, text: 'Возбуждение', icon: '😍', mode: 'word' },
  { level: 4, text: 'Плеть', icon: '🪢', mode: 'word' },
  { level: 4, text: 'Кнут', icon: '🪢', mode: 'word' },
  { level: 4, text: 'Наручники', icon: '🔒', mode: 'word' },
  { level: 4, text: 'Верёвка', icon: '🪢', mode: 'word' },
  { level: 4, text: 'Маска', icon: '🎭', mode: 'word' },
  { level: 4, text: 'Пояс', icon: '🎀', mode: 'word' },
  { level: 4, text: 'Бельё', icon: '👙', mode: 'word' },
  { level: 4, text: 'Пеньюар', icon: '👘', mode: 'word' },
  { level: 4, text: 'Корсет', icon: '👙', mode: 'word' },
  { level: 4, text: 'Чулки', icon: '🧦', mode: 'word' },
  { level: 4, text: 'Стринги', icon: '🩲', mode: 'word' },
  { level: 4, text: 'Кружево', icon: '🎀', mode: 'word' },
  { level: 4, text: 'Аромасвеча', icon: '🕯️', mode: 'word' },
  { level: 4, text: 'Вино', icon: '🍷', mode: 'word' },
  { level: 4, text: 'Клубника', icon: '🍓', mode: 'word' },
  { level: 4, text: 'Мёд', icon: '🍯', mode: 'word' },
  { level: 4, text: 'Лёд', icon: '🧊', mode: 'word' },
  { level: 4, text: 'Джакузи', icon: '🛁', mode: 'word' },
  { level: 4, text: 'Будуар', icon: '🛏️', mode: 'word' },
  { level: 4, text: 'Гейша', icon: '👘', mode: 'word' },
  { level: 4, text: 'Обольщение', icon: '😏', mode: 'word' },
  { level: 4, text: 'Совращение', icon: '😈', mode: 'word' },
  { level: 4, text: 'Дефлорация', icon: '🩸', mode: 'word' },
  { level: 4, text: 'Целомудрие', icon: '😇', mode: 'word' },
  { level: 4, text: 'Возбудитель', icon: '💊', mode: 'word' },
  { level: 4, text: 'Извращение', icon: '😈', mode: 'word' },
  { level: 4, text: 'Разнузданность', icon: '🔥', mode: 'word' },
  { level: 4, text: 'Стриптизёрша', icon: '💃', mode: 'word' },
  { level: 4, text: 'Соблазнительница', icon: '💋', mode: 'word' },
  { level: 4, text: 'Ловелас', icon: '😏', mode: 'word' },
  { level: 4, text: 'Кокотка', icon: '💋', mode: 'word' },
  { level: 4, text: 'Доминирование', icon: '⛓️' },
  { level: 4, text: 'Подчинение в постели', icon: '😈' },
  { level: 4, text: 'Поза наездницы', icon: '🔥' },
  { level: 4, text: 'Поза 69', icon: '🍑' },
  { level: 4, text: 'Стриптиз для партнёра', icon: '👄' },
  { level: 4, text: 'Съедобное бельё', icon: '🍓' },
  { level: 4, text: 'Соски с зажимами', icon: '📎' },
  { level: 4, text: 'Клубничный поцелуй', icon: '🖤' },
  { level: 4, text: 'Ролевая игра "начальник и секретарша"', icon: '💼' },
  { level: 4, text: 'Порка ремнём', icon: '🪢' },
  { level: 4, text: 'Секс в общественном месте', icon: '🙊' },
  { level: 4, text: 'Стриптиз на кухонном столе', icon: '💃' },
  { level: 4, text: 'Ошейник', icon: '🔥', mode: 'word' },
  { level: 4, text: 'Бондаж', icon: '🖤', mode: 'word' },
  { level: 4, text: 'Оковы', icon: '😶', mode: 'word' },
];
