// cards_sexshop.js — данные для 5-го модуля игры «Предложи партнеру»:
// топ-150 товаров для секс-шопа (рейтинг по продажам в России). Формат
// такой же, как в cards_poses.js, плюс:
// - rank — номер в рейтинге продаж (1 = самый продаваемый), показывается
//   крупным значком над названием;
// - forWhom — для кого подходит товар (ей / ему / обоим партнёрам),
//   показывается отдельной строкой под описанием;
// - womenRating/menRating — оценки партнёров от 0 до 10, показываются
//   отдельной строкой значков ниже.
// level (здесь всегда 5 — отдельный модуль), image (путь к фото в
// photos_shop/), title (название товара) и text (только описание товара,
// без прочих полей).
//
// Фото синхронизированы из папки photos_shop/ — файлы 001.webp..150.webp
// по одному на каждую позицию рейтинга.

const SEXSHOP_CARDS = [
  { level: 5, rank: 1, image: 'photos_shop/001.webp', title: 'Лубрикант на водной основе', text: 'Базовая смазка для любых видов секса, самая ходовая позиция.', forWhom: 'обоим партнёрам', womenRating: 9, menRating: 9 },
  { level: 5, rank: 2, image: 'photos_shop/002.webp', title: 'Эротические игры для пар (настольная)', text: 'Игры с заданиями и вопросами, популярный подарочный формат.', forWhom: 'обоим партнёрам', womenRating: 8, menRating: 8 },
  { level: 5, rank: 3, image: 'photos_shop/003.webp', title: 'Вибратор-пуля', text: 'Компактная игрушка для клиторальной стимуляции.', forWhom: 'ей', womenRating: 9, menRating: 6 },
  { level: 5, rank: 4, image: 'photos_shop/004.webp', title: 'Клиторальный вакуумный стимулятор', text: 'Стимуляция воздушными импульсами, один из лидеров женского спроса.', forWhom: 'ей', womenRating: 9, menRating: 6 },
  { level: 5, rank: 5, image: 'photos_shop/005.webp', title: 'Мастурбатор (рукав/туннель)', text: 'Классический мужской мастурбатор, базовый вариант.', forWhom: 'ему', womenRating: 2, menRating: 9 },
  { level: 5, rank: 6, image: 'photos_shop/006.webp', title: 'Вибратор для пар (кольцо на пенис)', text: 'Стимулирует клитор во время проникновения.', forWhom: 'обоим партнёрам', womenRating: 8, menRating: 8 },
  { level: 5, rank: 7, image: 'photos_shop/007.webp', title: 'Силиконовый лубрикант', text: 'Более долговечная смазка, подходит для душа и ванны.', forWhom: 'обоим партнёрам', womenRating: 8, menRating: 8 },
  { level: 5, rank: 8, image: 'photos_shop/008.webp', title: 'Вибратор-кролик (двойная стимуляция)', text: 'Одновременная стимуляция клитора и влагалища.', forWhom: 'ей', womenRating: 9, menRating: 6 },
  { level: 5, rank: 9, image: 'photos_shop/009.webp', title: 'Анальная пробка (базовая)', text: 'Небольшая пробка для начального уровня.', forWhom: 'обоим партнёрам', womenRating: 6, menRating: 7 },
  { level: 5, rank: 10, image: 'photos_shop/010.webp', title: 'Презервативы классические', text: 'Базовая защита, массовый спрос.', forWhom: 'обоим партнёрам', womenRating: 8, menRating: 8 },
  { level: 5, rank: 11, image: 'photos_shop/011.webp', title: 'Эротическое бельё (комплект)', text: 'Бюстгальтер + трусики, популярный подарок.', forWhom: 'ей', womenRating: 7, menRating: 8 },
  { level: 5, rank: 12, image: 'photos_shop/012.webp', title: 'Вибропалочка (wand)', text: 'Мощная внешняя стимуляция, классика для клитора.', forWhom: 'ей', womenRating: 9, menRating: 6 },
  { level: 5, rank: 13, image: 'photos_shop/013.webp', title: 'Эротические костюмы (ролевые)', text: 'Медсестра, полицейская, горничная — популярные сюжеты.', forWhom: 'ей', womenRating: 7, menRating: 8 },
  { level: 5, rank: 14, image: 'photos_shop/014.webp', title: 'Массажное масло', text: 'Для эротического массажа как часть прелюдии.', forWhom: 'обоим партнёрам', womenRating: 8, menRating: 7 },
  { level: 5, rank: 15, image: 'photos_shop/015.webp', title: 'Автоматический мастурбатор', text: 'Устройство с вращением и сжатием.', forWhom: 'ему', womenRating: 3, menRating: 9 },
  { level: 5, rank: 16, image: 'photos_shop/016.webp', title: 'Вибратор с изгибом (G‑точка)', text: 'Специальная форма для стимуляции G‑точки.', forWhom: 'ей', womenRating: 8, menRating: 5 },
  { level: 5, rank: 17, image: 'photos_shop/017.webp', title: 'Эротические аксессуары (набор для бондажа)', text: 'Верёвки, повязки, мягкие фиксаторы.', forWhom: 'обоим партнёрам', womenRating: 6, menRating: 7 },
  { level: 5, rank: 18, image: 'photos_shop/018.webp', title: 'Презервативы с вкусами/ароматами', text: 'Для орального секса, популярный вариант.', forWhom: 'обоим партнёрам', womenRating: 7, menRating: 7 },
  { level: 5, rank: 19, image: 'photos_shop/019.webp', title: 'Вагинальные шарики', text: 'Тренировка интимных мышц и дополнительная стимуляция.', forWhom: 'ей', womenRating: 6, menRating: 4 },
  { level: 5, rank: 20, image: 'photos_shop/020.webp', title: 'Простатный массажёр', text: 'Стимуляция простаты, растущий сегмент.', forWhom: 'ему', womenRating: 3, menRating: 8 },
  { level: 5, rank: 21, image: 'photos_shop/021.webp', title: 'Анальная смазка (густая)', text: 'Специальный лубрикант для анального секса.', forWhom: 'обоим партнёрам', womenRating: 7, menRating: 7 },
  { level: 5, rank: 22, image: 'photos_shop/022.webp', title: 'Вибратор-яйцо', text: 'Компактная форма, подходит для новичков.', forWhom: 'ей', womenRating: 7, menRating: 5 },
  { level: 5, rank: 23, image: 'photos_shop/023.webp', title: 'Набор презервативов (микс)', text: 'Разные виды в одной упаковке.', forWhom: 'обоим партнёрам', womenRating: 7, menRating: 8 },
  { level: 5, rank: 24, image: 'photos_shop/024.webp', title: 'Чулки эротические', text: 'Классика эротического белья.', forWhom: 'ей', womenRating: 7, menRating: 8 },
  { level: 5, rank: 25, image: 'photos_shop/025.webp', title: 'Вибратор с пультом (для пар)', text: 'Управление партнёром, игра на расстоянии.', forWhom: 'обоим партнёрам', womenRating: 8, menRating: 7 },
  { level: 5, rank: 26, image: 'photos_shop/026.webp', title: 'Анальный набор (пробки разного размера)', text: 'Постепенное увеличение диаметра.', forWhom: 'обоим партнёрам', womenRating: 7, menRating: 7 },
  { level: 5, rank: 27, image: 'photos_shop/027.webp', title: 'Мастурбатор с вибрацией', text: 'Добавляет вибрацию к обычному рукаву.', forWhom: 'ему', womenRating: 3, menRating: 8 },
  { level: 5, rank: 28, image: 'photos_shop/028.webp', title: 'Эротические кубики', text: 'Генерация случайных заданий для пар.', forWhom: 'обоим партнёрам', womenRating: 7, menRating: 6 },
  { level: 5, rank: 29, image: 'photos_shop/029.webp', title: 'Вибратор-браслет', text: 'Носимая игрушка с пультом.', forWhom: 'ей', womenRating: 7, menRating: 4 },
  { level: 5, rank: 30, image: 'photos_shop/030.webp', title: 'Свечи эротические (массажные)', text: 'Создают атмосферу и используются для массажа.', forWhom: 'обоим партнёрам', womenRating: 7, menRating: 6 },
  { level: 5, rank: 31, image: 'photos_shop/031.webp', title: 'Вибратор-помада', text: 'Компактный формат, похожий на помаду.', forWhom: 'ей', womenRating: 7, menRating: 4 },
  { level: 5, rank: 32, image: 'photos_shop/032.webp', title: 'Презервативы с пролонгатором', text: 'Содержат лёгкий анестетик для продления.', forWhom: 'обоим партнёрам', womenRating: 7, menRating: 8 },
  { level: 5, rank: 33, image: 'photos_shop/033.webp', title: 'Эротическая повязка на глаза', text: 'Базовый элемент для сенсорных игр.', forWhom: 'обоим партнёрам', womenRating: 7, menRating: 7 },
  { level: 5, rank: 34, image: 'photos_shop/034.webp', title: 'Мини-вибратор для клитора', text: 'Точечная стимуляция, удобно носить с собой.', forWhom: 'ей', womenRating: 8, menRating: 5 },
  { level: 5, rank: 35, image: 'photos_shop/035.webp', title: 'Гель для интимной гигиены', text: 'Ежедневная гигиена, чувствительная зона.', forWhom: 'ей', womenRating: 7, menRating: 4 },
  { level: 5, rank: 36, image: 'photos_shop/036.webp', title: 'Вибратор-двойник (для пар)', text: 'Одновременно стимулирует обоих партнёров.', forWhom: 'обоим партнёрам', womenRating: 8, menRating: 7 },
  { level: 5, rank: 37, image: 'photos_shop/037.webp', title: 'Анальная груша/спринцовка', text: 'Для подготовки и гигиены перед анальным сексом.', forWhom: 'обоим партнёрам', womenRating: 6, menRating: 6 },
  { level: 5, rank: 38, image: 'photos_shop/038.webp', title: 'Мастурбатор с подогревом', text: 'Тепло усиливает реалистичность ощущений.', forWhom: 'ему', womenRating: 3, menRating: 8 },
  { level: 5, rank: 39, image: 'photos_shop/039.webp', title: 'Вибратор с аппликатором для пар', text: 'Одновременная стимуляция клитора и пениса.', forWhom: 'обоим партнёрам', womenRating: 8, menRating: 7 },
  { level: 5, rank: 40, image: 'photos_shop/040.webp', title: 'Эротический комплект «горничная»', text: 'Платье, фартук и аксессуары.', forWhom: 'ей', womenRating: 7, menRating: 7 },
  { level: 5, rank: 41, image: 'photos_shop/041.webp', title: 'Вибратор-кольцо на палец', text: 'Точечная стимуляция во время ласк.', forWhom: 'ей', womenRating: 7, menRating: 6 },
  { level: 5, rank: 42, image: 'photos_shop/042.webp', title: 'Шарик в презерватив для увеличения члена', text: 'Для ярких ощущений.', forWhom: 'ему', womenRating: 5, menRating: 8 },
  { level: 5, rank: 43, image: 'photos_shop/043.webp', title: 'Вибратор с изгибом и вибрацией', text: 'Комбинация формы и мощности.', forWhom: 'ей', womenRating: 8, menRating: 5 },
  { level: 5, rank: 44, image: 'photos_shop/044.webp', title: 'Эротический набор для массажа', text: 'Масло, перо, иногда кубики.', forWhom: 'обоим партнёрам', womenRating: 7, menRating: 7 },
  { level: 5, rank: 45, image: 'photos_shop/045.webp', title: 'Анальная пробка с камнем/декором', text: 'Эстетика и стимуляция.', forWhom: 'обоим партнёрам', womenRating: 6, menRating: 6 },
  { level: 5, rank: 46, image: 'photos_shop/046.webp', title: 'Вибратор-кролик премиум', text: 'Более мощные моторы и материалы.', forWhom: 'ей', womenRating: 8, menRating: 5 },
  { level: 5, rank: 47, image: 'photos_shop/047.webp', title: 'Мастурбатор-туннель (компактный)', text: 'Упрощённая версия для новичков.', forWhom: 'ему', womenRating: 3, menRating: 8 },
  { level: 5, rank: 48, image: 'photos_shop/048.webp', title: 'Эротическое боди', text: 'Цельный комплект, популярный в подарках.', forWhom: 'ей', womenRating: 7, menRating: 7 },
  { level: 5, rank: 49, image: 'photos_shop/049.webp', title: 'Вибратор с Bluetooth (управление из приложения)', text: 'Smart-игрушка, управление со смартфона.', forWhom: 'ей', womenRating: 8, menRating: 6 },
  { level: 5, rank: 50, image: 'photos_shop/050.webp', title: 'Презервативы тонкие (ultra thin)', text: 'Максимальная чувствительность.', forWhom: 'обоим партнёрам', womenRating: 8, menRating: 8 },
  { level: 5, rank: 51, image: 'photos_shop/051.webp', title: 'Вибропалочка с насадками', text: 'Разные текстуры в одном устройстве.', forWhom: 'ей', womenRating: 8, menRating: 5 },
  { level: 5, rank: 52, image: 'photos_shop/052.webp', title: 'Эротический корсет', text: 'Формирует силуэт, ролевой элемент.', forWhom: 'ей', womenRating: 6, menRating: 7 },
  { level: 5, rank: 53, image: 'photos_shop/053.webp', title: 'Анальный вибратор-пуля', text: 'Маленькая модель для анальной зоны.', forWhom: 'обоим партнёрам', womenRating: 7, menRating: 7 },
  { level: 5, rank: 54, image: 'photos_shop/054.webp', title: 'Мастурбатор с текстурой (рёбра/волны)', text: 'Внутренний рельеф для усиления стимуляции.', forWhom: 'ему', womenRating: 3, menRating: 8 },
  { level: 5, rank: 55, image: 'photos_shop/055.webp', title: 'Вибратор для G‑точки с пультом', text: 'Управление партнёром, игра в постели.', forWhom: 'ей', womenRating: 8, menRating: 5 },
  { level: 5, rank: 56, image: 'photos_shop/056.webp', title: 'Эротические перчатки', text: 'Часть образа и тактильного сценария.', forWhom: 'ей', womenRating: 6, menRating: 7 },
  { level: 5, rank: 57, image: 'photos_shop/057.webp', title: 'Лубрикант с ароматом/вкусом', text: 'Для оральных практик и разнообразия.', forWhom: 'обоим партнёрам', womenRating: 7, menRating: 7 },
  { level: 5, rank: 58, image: 'photos_shop/058.webp', title: 'Вибратор с программируемыми паттернами', text: 'Сложные сценарии вибрации.', forWhom: 'ей', womenRating: 7, menRating: 5 },
  { level: 5, rank: 59, image: 'photos_shop/059.webp', title: 'Автоматический мастурбатор с вращением', text: 'Вращение в сочетании с движением.', forWhom: 'ему', womenRating: 3, menRating: 8 },
  { level: 5, rank: 60, image: 'photos_shop/060.webp', title: 'Эротический халатик/пеньюар', text: 'Лёгкая домашняя эротика.', forWhom: 'ей', womenRating: 7, menRating: 7 },
  { level: 5, rank: 61, image: 'photos_shop/061.webp', title: 'Вибратор-браслет с пультом', text: 'Носимая игрушка, управление партнёром.', forWhom: 'ей', womenRating: 7, menRating: 6 },
  { level: 5, rank: 62, image: 'photos_shop/062.webp', title: 'Простатный массажёр с вибрацией', text: 'Стимуляция простаты + вибрация.', forWhom: 'ему', womenRating: 4, menRating: 8 },
  { level: 5, rank: 63, image: 'photos_shop/063.webp', title: 'Эротические чулки с узором', text: 'Эротический акцент в образе.', forWhom: 'ей', womenRating: 7, menRating: 7 },
  { level: 5, rank: 64, image: 'photos_shop/064.webp', title: 'Вибратор с подогревом', text: 'Тепло усиливает ощущения.', forWhom: 'ей', womenRating: 7, menRating: 5 },
  { level: 5, rank: 65, image: 'photos_shop/065.webp', title: 'Мастурбатор с сжатием (автомат)', text: 'Имитация сжатия, более продвинутая модель.', forWhom: 'ему', womenRating: 3, menRating: 8 },
  { level: 5, rank: 66, image: 'photos_shop/066.webp', title: 'Эротический набор «стюардесса»', text: 'Ролевой комплект.', forWhom: 'ей', womenRating: 6, menRating: 7 },
  { level: 5, rank: 67, image: 'photos_shop/067.webp', title: 'Вибратор-двойник премиум', text: 'Более мощные моторы и материалы.', forWhom: 'обоим партнёрам', womenRating: 8, menRating: 7 },
  { level: 5, rank: 68, image: 'photos_shop/068.webp', title: 'Анальная пробка металлическая', text: 'Тяжёлая, для продвинутых.', forWhom: 'обоим партнёрам', womenRating: 6, menRating: 7 },
  { level: 5, rank: 69, image: 'photos_shop/069.webp', title: 'Вибратор с дальним управлением (long distance)', text: 'Игра на расстоянии через приложение.', forWhom: 'ей', womenRating: 8, menRating: 6 },
  { level: 5, rank: 70, image: 'photos_shop/070.webp', title: 'Презервативы с рёбрами/точками', text: 'Дополнительная стимуляция для партнёрши.', forWhom: 'обоим партнёрам', womenRating: 7, menRating: 7 },
  { level: 5, rank: 71, image: 'photos_shop/071.webp', title: 'Вибратор-помада с пультом', text: 'Компактность + управление партнёром.', forWhom: 'ей', womenRating: 7, menRating: 6 },
  { level: 5, rank: 72, image: 'photos_shop/072.webp', title: 'Эротический комплект «полицейская»', text: 'Популярный ролевой сюжет.', forWhom: 'ей', womenRating: 6, menRating: 7 },
  { level: 5, rank: 73, image: 'photos_shop/073.webp', title: 'Анальный стимулятор с изгибом (для простаты)', text: 'Часто выбирают для простатной стимуляции.', forWhom: 'ему', womenRating: 4, menRating: 8 },
  { level: 5, rank: 74, image: 'photos_shop/074.webp', title: 'Вибратор-яйцо с Bluetooth', text: 'Удалённое управление на расстоянии.', forWhom: 'ей', womenRating: 8, menRating: 6 },
  { level: 5, rank: 75, image: 'photos_shop/075.webp', title: 'Мастурбатор с вибрацией и подогревом', text: 'Комбинация тепла и вибрации.', forWhom: 'ему', womenRating: 3, menRating: 8 },
  { level: 5, rank: 76, image: 'photos_shop/076.webp', title: 'Эротический пояс для подвязок', text: 'Классический элемент образа.', forWhom: 'ей', womenRating: 6, menRating: 7 },
  { level: 5, rank: 77, image: 'photos_shop/077.webp', title: 'Вибратор с голосовым управлением', text: 'Нишевая smart-функция.', forWhom: 'ей', womenRating: 6, menRating: 5 },
  { level: 5, rank: 78, image: 'photos_shop/078.webp', title: 'Анальная смазка с анестетиком', text: 'Частично снижает чувствительность.', forWhom: 'обоим партнёрам', womenRating: 6, menRating: 7 },
  { level: 5, rank: 79, image: 'photos_shop/079.webp', title: 'Вибратор-кролик с подогревом', text: 'Двойная стимуляция + тепло.', forWhom: 'ей', womenRating: 8, menRating: 5 },
  { level: 5, rank: 80, image: 'photos_shop/080.webp', title: 'Эротический комплект «медсестра»', text: 'Классика ролевых сценариев.', forWhom: 'ей', womenRating: 7, menRating: 7 },
  { level: 5, rank: 81, image: 'photos_shop/081.webp', title: 'Вибратор с подсветкой', text: 'Добавляет визуальный эффект.', forWhom: 'ей', womenRating: 6, menRating: 5 },
  { level: 5, rank: 82, image: 'photos_shop/082.webp', title: 'Автоматический мастурбатор премиум', text: 'Более сложные программы и материалы.', forWhom: 'ему', womenRating: 3, menRating: 8 },
  { level: 5, rank: 83, image: 'photos_shop/083.webp', title: 'Эротические гольфы/чулки до бедра', text: 'Элемент костюма.', forWhom: 'ей', womenRating: 6, menRating: 7 },
  { level: 5, rank: 84, image: 'photos_shop/084.webp', title: 'Вибратор с аппликатором для пар (премиум)', text: 'Одновременная стимуляция, улучшенная версия.', forWhom: 'обоим партнёрам', womenRating: 8, menRating: 7 },
  { level: 5, rank: 85, image: 'photos_shop/085.webp', title: 'Анальный набор (пробки + смазка + груша)', text: 'Комплект для комфортного старта.', forWhom: 'обоим партнёрам', womenRating: 7, menRating: 7 },
  { level: 5, rank: 86, image: 'photos_shop/086.webp', title: 'Вибратор-браслет с приложением', text: 'Smart-сценарии и тонкая настройка.', forWhom: 'ей', womenRating: 7, menRating: 6 },
  { level: 5, rank: 87, image: 'photos_shop/087.webp', title: 'Эротический комплект «студентка»', text: 'Один из массовых ролевых образов.', forWhom: 'ей', womenRating: 6, menRating: 7 },
  { level: 5, rank: 88, image: 'photos_shop/088.webp', title: 'Вибратор с изгибом и вибрацией (премиум)', text: 'Более мощные моторы и материалы.', forWhom: 'ей', womenRating: 8, menRating: 5 },
  { level: 5, rank: 89, image: 'photos_shop/089.webp', title: 'Мастурбатор с текстурой и вибрацией', text: 'Сочетание рельефа и вибрации.', forWhom: 'ему', womenRating: 3, menRating: 8 },
  { level: 5, rank: 90, image: 'photos_shop/090.webp', title: 'Эротический комплект «кошка/лисичка»', text: 'Ушки, хвост и костюм в одном наборе.', forWhom: 'ей', womenRating: 7, menRating: 7 },
  { level: 5, rank: 91, image: 'photos_shop/091.webp', title: 'Вибратор-двойник с подогревом', text: 'Тепло + двойная стимуляция.', forWhom: 'обоим партнёрам', womenRating: 8, menRating: 7 },
  { level: 5, rank: 92, image: 'photos_shop/092.webp', title: 'Анальная пробка с вибрацией', text: 'Добавляет вибрацию к анальной стимуляции.', forWhom: 'обоим партнёрам', womenRating: 7, menRating: 7 },
  { level: 5, rank: 93, image: 'photos_shop/093.webp', title: 'Вибратор-помада с подогревом', text: 'Компактность + тепло.', forWhom: 'ей', womenRating: 7, menRating: 5 },
  { level: 5, rank: 94, image: 'photos_shop/094.webp', title: 'Эротический набор для бондажа (премиум)', text: 'Более дорогие материалы и фурнитура.', forWhom: 'обоим партнёрам', womenRating: 6, menRating: 7 },
  { level: 5, rank: 95, image: 'photos_shop/095.webp', title: 'Вибратор с программируемыми паттернами (премиум)', text: 'Сложные сценарии и настройки.', forWhom: 'ей', womenRating: 7, menRating: 6 },
  { level: 5, rank: 96, image: 'photos_shop/096.webp', title: 'Мастурбатор с подогревом и вибрацией (премиум)', text: 'Тепло + вибрация + продвинутые режимы.', forWhom: 'ему', womenRating: 3, menRating: 8 },
  { level: 5, rank: 97, image: 'photos_shop/097.webp', title: 'Эротический комплект «горничная» (премиум)', text: 'Улучшенные материалы и детали.', forWhom: 'ей', womenRating: 7, menRating: 7 },
  { level: 5, rank: 98, image: 'photos_shop/098.webp', title: 'Вибратор-яйцо с подогревом', text: 'Тепло + компактность.', forWhom: 'ей', womenRating: 7, menRating: 6 },
  { level: 5, rank: 99, image: 'photos_shop/099.webp', title: 'Анальный стимулятор с вибрацией и подогревом', text: 'Вибрация + тепло для простатной стимуляции.', forWhom: 'ему', womenRating: 4, menRating: 8 },
  { level: 5, rank: 100, image: 'photos_shop/100.webp', title: 'Эротический комплект «стюардесса» (премиум)', text: 'Ролевой комплект улучшенного качества.', forWhom: 'ей', womenRating: 6, menRating: 7 },
  { level: 5, rank: 101, image: 'photos_shop/101.webp', title: 'Секс-кукла (TPE, средняя)', text: 'Высокий чек, но взрывной рост категории.', forWhom: 'ему', womenRating: 1, menRating: 6 },
  { level: 5, rank: 102, image: 'photos_shop/102.webp', title: 'Секс-машина (продвинутая)', text: 'Одна из самых дорогих позиций, штучные продажи.', forWhom: 'ей', womenRating: 6, menRating: 4 },
  { level: 5, rank: 103, image: 'photos_shop/103.webp', title: 'Набор насадок на вибратор', text: 'Расширяет функционал базового устройства.', forWhom: 'ей', womenRating: 6, menRating: 3 },
  { level: 5, rank: 104, image: 'photos_shop/104.webp', title: 'Эротический веер', text: 'Лёгкий BDSM- или ролевой аксессуар.', forWhom: 'обоим партнёрам', womenRating: 6, menRating: 5 },
  { level: 5, rank: 105, image: 'photos_shop/105.webp', title: 'Зажимы для сосков (металл)', text: 'Более выраженный эффект давления.', forWhom: 'обоим партнёрам', womenRating: 4, menRating: 5 },
  { level: 5, rank: 106, image: 'photos_shop/106.webp', title: 'Набор для ролевых (костюм + аксессуары)', text: 'Популярный подарочный формат.', forWhom: 'ей', womenRating: 6, menRating: 6 },
  { level: 5, rank: 107, image: 'photos_shop/107.webp', title: 'Эротическая маска', text: 'Дополняет образ в ролевых сценариях.', forWhom: 'обоим партнёрам', womenRating: 6, menRating: 5 },
  { level: 5, rank: 108, image: 'photos_shop/108.webp', title: 'Чокер эротический', text: 'Аксессуар для образа и BDSM-эстетики.', forWhom: 'ей', womenRating: 5, menRating: 5 },
  { level: 5, rank: 109, image: 'photos_shop/109.webp', title: 'Каблуки или туфли для ролевых', text: 'Элемент костюма, усиливает образ.', forWhom: 'ей', womenRating: 4, menRating: 5 },
  { level: 5, rank: 110, image: 'photos_shop/110.webp', title: 'Эротические чулки (сетка)', text: 'Классика эротического белья.', forWhom: 'ей', womenRating: 5, menRating: 6 },
  { level: 5, rank: 111, image: 'photos_shop/111.webp', title: 'Подтяжки для чулок', text: 'Дополнение к комплекту белья.', forWhom: 'ей', womenRating: 4, menRating: 5 },
  { level: 5, rank: 112, image: 'photos_shop/112.webp', title: 'Боди эротическое', text: 'Цельный комплект, популярный в подарках.', forWhom: 'ей', womenRating: 5, menRating: 6 },
  { level: 5, rank: 113, image: 'photos_shop/113.webp', title: 'Корсет эротический', text: 'Формирует силуэт и поддерживает ролевой образ.', forWhom: 'ей', womenRating: 5, menRating: 6 },
  { level: 5, rank: 114, image: 'photos_shop/114.webp', title: 'Халатик или пеньюар прозрачный', text: 'Лёгкая домашняя эротика.', forWhom: 'ей', womenRating: 5, menRating: 6 },
  { level: 5, rank: 115, image: 'photos_shop/115.webp', title: 'Трусики с вырезами', text: 'Открытый дизайн для доступа.', forWhom: 'ей', womenRating: 5, menRating: 6 },
  { level: 5, rank: 116, image: 'photos_shop/116.webp', title: 'Бюстгальтер push-up эротический', text: 'Усиливает декольте, часть комплекта.', forWhom: 'ей', womenRating: 5, menRating: 6 },
  { level: 5, rank: 117, image: 'photos_shop/117.webp', title: 'Пояс для подвязок', text: 'Классический элемент образа.', forWhom: 'ей', womenRating: 5, menRating: 5 },
  { level: 5, rank: 118, image: 'photos_shop/118.webp', title: 'Массажёр для шеи и плеч', text: 'Подходит для расслабляющей прелюдии.', forWhom: 'обоим партнёрам', womenRating: 6, menRating: 5 },
  { level: 5, rank: 119, image: 'photos_shop/119.webp', title: 'Игрушка-антистресс 18+', text: 'Шуточный или подарочный формат.', forWhom: 'обоим партнёрам', womenRating: 4, menRating: 4 },
  { level: 5, rank: 120, image: 'photos_shop/120.webp', title: 'Набор эротических кубиков', text: 'Генератор случайных заданий.', forWhom: 'обоим партнёрам', womenRating: 6, menRating: 5 },
  { level: 5, rank: 121, image: 'photos_shop/121.webp', title: 'Карты желаний (интимные)', text: 'Мягкая игра про желания и фантазии.', forWhom: 'обоим партнёрам', womenRating: 6, menRating: 5 },
  { level: 5, rank: 122, image: 'photos_shop/122.webp', title: 'Игра «Правда или действие» 18+', text: 'Адаптация популярной игры.', forWhom: 'обоим партнёрам', womenRating: 6, menRating: 6 },
  { level: 5, rank: 123, image: 'photos_shop/123.webp', title: 'Рулетка эротическая', text: 'Случайный выбор действия или зоны.', forWhom: 'обоим партнёрам', womenRating: 5, menRating: 5 },
  { level: 5, rank: 124, image: 'photos_shop/124.webp', title: 'Дартс эротический', text: 'Игра с призами и заданиями.', forWhom: 'обоим партнёрам', womenRating: 5, menRating: 5 },
  { level: 5, rank: 125, image: 'photos_shop/125.webp', title: 'Настольная игра для пар (продвинутая)', text: 'Более откровенные механики и сценарии.', forWhom: 'обоим партнёрам', womenRating: 7, menRating: 6 },
  { level: 5, rank: 126, image: 'photos_shop/126.webp', title: 'Игра-квиз про отношения 18+', text: 'Проверка совместимости и фантазий.', forWhom: 'обоим партнёрам', womenRating: 6, menRating: 5 },
  { level: 5, rank: 127, image: 'photos_shop/127.webp', title: 'Лубрикант с разогревающим эффектом', text: 'Нишевый сегмент интим-косметики.', forWhom: 'обоим партнёрам', womenRating: 6, menRating: 6 },
  { level: 5, rank: 128, image: 'photos_shop/128.webp', title: 'Интимный дезодорант', text: 'Гигиена и свежесть перед близостью.', forWhom: 'обоим партнёрам', womenRating: 5, menRating: 5 },
  { level: 5, rank: 129, image: 'photos_shop/129.webp', title: 'Спрей для свежести дыхания', text: 'Используют перед оральными практиками.', forWhom: 'обоим партнёрам', womenRating: 5, menRating: 5 },
  { level: 5, rank: 130, image: 'photos_shop/130.webp', title: 'Салфетки с ароматом для интима', text: 'Быстрая гигиена на ходу.', forWhom: 'обоим партнёрам', womenRating: 6, menRating: 6 },
  { level: 5, rank: 131, image: 'photos_shop/131.webp', title: 'Гель для интимной гигиены (мужской)', text: 'Часть мужского sexual wellness.', forWhom: 'ему', womenRating: 3, menRating: 6 },
  { level: 5, rank: 132, image: 'photos_shop/132.webp', title: 'Гель для интимной гигиены (женский)', text: 'Ежедневная гигиена для чувствительной зоны.', forWhom: 'ей', womenRating: 6, menRating: 3 },
  { level: 5, rank: 133, image: 'photos_shop/133.webp', title: 'Пенка для интимной гигиены', text: 'Мягкая альтернатива гелю.', forWhom: 'ей', womenRating: 6, menRating: 3 },
  { level: 5, rank: 134, image: 'photos_shop/134.webp', title: 'Презервативы с пролонгатором', text: 'Содержат лёгкий анестетик.', forWhom: 'обоим партнёрам', womenRating: 6, menRating: 7 },
  { level: 5, rank: 135, image: 'photos_shop/135.webp', title: 'Презервативы увеличенного размера', text: 'Для большего комфорта.', forWhom: 'ему', womenRating: 4, menRating: 7 },
  { level: 5, rank: 136, image: 'photos_shop/136.webp', title: 'Презервативы тонкие со смазкой', text: 'Баланс чувствительности и скольжения.', forWhom: 'обоим партнёрам', womenRating: 7, menRating: 7 },
  { level: 5, rank: 137, image: 'photos_shop/137.webp', title: 'Женский презерватив', text: 'Альтернатива мужскому, нишевый спрос.', forWhom: 'ей', womenRating: 4, menRating: 4 },
  { level: 5, rank: 138, image: 'photos_shop/138.webp', title: 'Диафрагма или колпачок', text: 'Многоразовая контрацепция, редкий спрос.', forWhom: 'ей', womenRating: 3, menRating: 2 },
  { level: 5, rank: 139, image: 'photos_shop/139.webp', title: 'Тест на овуляцию', text: 'Смежная категория, иногда в одном чеке.', forWhom: 'ей', womenRating: 3, menRating: 1 },
  { level: 5, rank: 140, image: 'photos_shop/140.webp', title: 'Тест на беременность', text: 'Часто размещается рядом с интим-товарами.', forWhom: 'ей', womenRating: 3, menRating: 1 },
  { level: 5, rank: 141, image: 'photos_shop/141.webp', title: 'Секс-качели', text: 'Для продвинутых позиций, высокий чек.', forWhom: 'обоим партнёрам', womenRating: 5, menRating: 5 },
  { level: 5, rank: 142, image: 'photos_shop/142.webp', title: 'Секс-кресло или надувная подушка', text: 'Облегчает сложные позы.', forWhom: 'обоим партнёрам', womenRating: 6, menRating: 6 },
  { level: 5, rank: 143, image: 'photos_shop/143.webp', title: 'Набор для бондажа', text: 'Комплект для фиксаций.', forWhom: 'обоим партнёрам', womenRating: 5, menRating: 6 },
  { level: 5, rank: 144, image: 'photos_shop/144.webp', title: 'BDSM-набор премиум', text: 'Более дорогие материалы и фурнитура.', forWhom: 'обоим партнёрам', womenRating: 5, menRating: 6 },
  { level: 5, rank: 145, image: 'photos_shop/145.webp', title: 'Зажимы для сосков с цепочкой', text: 'Визуальный и физический эффект.', forWhom: 'обоим партнёрам', womenRating: 4, menRating: 5 },
  { level: 5, rank: 146, image: 'photos_shop/146.webp', title: 'Стеклянный анальный стимулятор', text: 'Непористый, подходит для температурной игры.', forWhom: 'обоим партнёрам', womenRating: 5, menRating: 6 },
  { level: 5, rank: 147, image: 'photos_shop/147.webp', title: 'Металлическая анальная пробка', text: 'Тяжёлая модель для продвинутых.', forWhom: 'обоим партнёрам', womenRating: 5, menRating: 6 },
  { level: 5, rank: 148, image: 'photos_shop/148.webp', title: 'Виброяйцо с Bluetooth', text: 'Удалённое управление на расстоянии.', forWhom: 'ей', womenRating: 7, menRating: 5 },
  { level: 5, rank: 149, image: 'photos_shop/149.webp', title: 'Эрекционное кольцо на член с вибрацией и усиками', text: 'Кольцо с вибромотором и стимулирующими «усиками» для дополнительной ласки партнёрши во время секса.', forWhom: 'обоим партнёрам', womenRating: 7, menRating: 8 },
  { level: 5, rank: 150, image: 'photos_shop/150.webp', title: 'Форма секс полицейской', text: 'Ролевой костюм: фуражка, жезл и провокационный крой формы.', forWhom: 'ей', womenRating: 6, menRating: 8 },
];
