// cards_kids_krokodil.js — данные для детской версии игры «Крокодил».
// Уровень (1-4) берётся не из отдельного экрана настройки, а из общего
// переключателя возраста #kidsAgeGroup на экране "Игры с детьми"
// (state.kidsAge) — тот же id, что и level карточек здесь (как в
// cards_kids_td.js).
// KIDS_KROKODIL_LEVELS — 4 возрастные группы (id, name, desc, icon).
// KIDS_KROKODIL_CARDS — { level, text, icon, mode? }: mode:'word' — простые
// одиночные слова (классический Крокодил), без mode — сценки/действия
// (что показывающий изображает движением).

const KIDS_KROKODIL_LEVELS = [
  {id:1, icon:'🧸', name:'5 лет', desc:'Простые знакомые слова и движения'},
  {id:2, icon:'🎈', name:'7 лет', desc:'Школа, игры во дворе, мультфильмы'},
  {id:3, icon:'🚀', name:'10 лет', desc:'Увлечения, приключения, фантазия'},
  {id:4, icon:'🏆', name:'14 лет', desc:'Подростковые темы и тренды'},
];

const KIDS_KROKODIL_CARDS = [
  // ---------- Уровень 1 (5 лет): Слово ----------
  {level:1, text:'Кот', icon:'🐱', mode:'word'},
  {level:1, text:'Собака', icon:'🐶', mode:'word'},
  {level:1, text:'Мяч', icon:'⚽', mode:'word'},
  {level:1, text:'Яблоко', icon:'🍎', mode:'word'},
  {level:1, text:'Стол', icon:'🪑', mode:'word'},
  {level:1, text:'Солнце', icon:'☀️', mode:'word'},
  {level:1, text:'Луна', icon:'🌙', mode:'word'},
  {level:1, text:'Рыба', icon:'🐟', mode:'word'},
  {level:1, text:'Птица', icon:'🐦', mode:'word'},
  {level:1, text:'Дом', icon:'🏠', mode:'word'},
  {level:1, text:'Машина', icon:'🚗', mode:'word'},
  {level:1, text:'Цветок', icon:'🌸', mode:'word'},
  {level:1, text:'Дерево', icon:'🌳', mode:'word'},
  {level:1, text:'Зонт', icon:'☂️', mode:'word'},
  {level:1, text:'Шарик', icon:'🎈', mode:'word'},
  // ---------- Уровень 1 (5 лет): Действие ----------
  {level:1, text:'Спит', icon:'😴'},
  {level:1, text:'Плачет', icon:'😢'},
  {level:1, text:'Смеётся', icon:'😂'},
  {level:1, text:'Прыгает', icon:'🤸'},
  {level:1, text:'Бежит', icon:'🏃'},
  {level:1, text:'Ест', icon:'🍽️'},
  {level:1, text:'Пьёт', icon:'🥤'},
  {level:1, text:'Танцует', icon:'💃'},
  {level:1, text:'Поёт', icon:'🎤'},
  {level:1, text:'Летает как птица', icon:'🕊️'},
  {level:1, text:'Плавает', icon:'🏊'},
  {level:1, text:'Рисует', icon:'🎨'},
  {level:1, text:'Читает книжку', icon:'📖'},
  {level:1, text:'Моет руки', icon:'🧼'},
  {level:1, text:'Чистит зубы', icon:'🪥'},

  // ---------- Уровень 2 (7 лет): Слово ----------
  {level:2, text:'Школа', icon:'🏫', mode:'word'},
  {level:2, text:'Портфель', icon:'🎒', mode:'word'},
  {level:2, text:'Карандаш', icon:'✏️', mode:'word'},
  {level:2, text:'Учитель', icon:'🧑‍🏫', mode:'word'},
  {level:2, text:'Друг', icon:'🧑‍🤝‍🧑', mode:'word'},
  {level:2, text:'Велосипед', icon:'🚲', mode:'word'},
  {level:2, text:'Качели', icon:'🛝', mode:'word'},
  {level:2, text:'Мороженое', icon:'🍦', mode:'word'},
  {level:2, text:'Пицца', icon:'🍕', mode:'word'},
  {level:2, text:'Робот', icon:'🤖', mode:'word'},
  {level:2, text:'Динозавр', icon:'🦕', mode:'word'},
  {level:2, text:'Ракета', icon:'🚀', mode:'word'},
  {level:2, text:'Клоун', icon:'🤡', mode:'word'},
  {level:2, text:'Скакалка', icon:'🪢', mode:'word'},
  {level:2, text:'Самокат', icon:'🛴', mode:'word'},
  // ---------- Уровень 2 (7 лет): Действие ----------
  {level:2, text:'Чистит зубы перед сном', icon:'🪥'},
  {level:2, text:'Делает домашнее задание', icon:'📝'},
  {level:2, text:'Катается на велосипеде', icon:'🚲'},
  {level:2, text:'Играет в футбол', icon:'⚽'},
  {level:2, text:'Прыгает через скакалку', icon:'🪢'},
  {level:2, text:'Строит замок из песка', icon:'🏰'},
  {level:2, text:'Ловит бабочку сачком', icon:'🦋'},
  {level:2, text:'Печёт пирог с мамой', icon:'🥧'},
  {level:2, text:'Собирает пазл', icon:'🧩'},
  {level:2, text:'Смотрит мультфильм', icon:'📺'},
  {level:2, text:'Едет на самокате', icon:'🛴'},
  {level:2, text:'Кормит рыбок в аквариуме', icon:'🐠'},
  {level:2, text:'Поливает цветы из лейки', icon:'🪴'},
  {level:2, text:'Играет в прятки', icon:'🙈'},
  {level:2, text:'Задувает свечи на торте', icon:'🎂'},

  // ---------- Уровень 3 (10 лет): Слово ----------
  {level:3, text:'Компьютер', icon:'💻', mode:'word'},
  {level:3, text:'Наушники', icon:'🎧', mode:'word'},
  {level:3, text:'Скейтборд', icon:'🛹', mode:'word'},
  {level:3, text:'Гитара', icon:'🎸', mode:'word'},
  {level:3, text:'Телескоп', icon:'🔭', mode:'word'},
  {level:3, text:'Комикс', icon:'📚', mode:'word'},
  {level:3, text:'Ниндзя', icon:'🥷', mode:'word'},
  {level:3, text:'Супергерой', icon:'🦸', mode:'word'},
  {level:3, text:'Астронавт', icon:'🧑‍🚀', mode:'word'},
  {level:3, text:'Пират', icon:'🏴‍☠️', mode:'word'},
  {level:3, text:'Волшебник', icon:'🧙', mode:'word'},
  {level:3, text:'Единорог', icon:'🦄', mode:'word'},
  {level:3, text:'Дракон', icon:'🐉', mode:'word'},
  {level:3, text:'Батут', icon:'🤾', mode:'word'},
  {level:3, text:'Конструктор', icon:'🧱', mode:'word'},
  // ---------- Уровень 3 (10 лет): Действие ----------
  {level:3, text:'Играет в видеоигру с джойстиком', icon:'🎮'},
  {level:3, text:'Катается на скейтборде', icon:'🛹'},
  {level:3, text:'Играет на гитаре', icon:'🎸'},
  {level:3, text:'Делает селфи', icon:'🤳'},
  {level:3, text:'Собирает конструктор', icon:'🧱'},
  {level:3, text:'Занимается карате', icon:'🥋'},
  {level:3, text:'Плавает в бассейне', icon:'🏊'},
  {level:3, text:'Прыгает на батуте', icon:'🤾'},
  {level:3, text:'Разгадывает кроссворд', icon:'📰'},
  {level:3, text:'Изучает звёзды в телескоп', icon:'🔭'},
  {level:3, text:'Играет в шахматы', icon:'♟️'},
  {level:3, text:'Танцует брейк-данс', icon:'🕺'},
  {level:3, text:'Ищет клад по карте', icon:'🗺️'},
  {level:3, text:'Печёт печенье', icon:'🍪'},
  {level:3, text:'Запускает воздушного змея', icon:'🪁'},

  // ---------- Уровень 4 (14 лет): Слово ----------
  {level:4, text:'Смартфон', icon:'📱', mode:'word'},
  {level:4, text:'Скейтпарк', icon:'🛹', mode:'word'},
  {level:4, text:'Плейлист', icon:'🎵', mode:'word'},
  {level:4, text:'Стример', icon:'🎥', mode:'word'},
  {level:4, text:'Хайп', icon:'🔥', mode:'word'},
  {level:4, text:'Челлендж', icon:'🏆', mode:'word'},
  {level:4, text:'Мем', icon:'😂', mode:'word'},
  {level:4, text:'Подкаст', icon:'🎙️', mode:'word'},
  {level:4, text:'Дедлайн', icon:'⏰', mode:'word'},
  {level:4, text:'Кроссовки', icon:'👟', mode:'word'},
  {level:4, text:'Худи', icon:'🧥', mode:'word'},
  {level:4, text:'Пауэрбанк', icon:'🔋', mode:'word'},
  {level:4, text:'Наушники беспроводные', icon:'🎧', mode:'word'},
  {level:4, text:'Селфи-палка', icon:'🤳', mode:'word'},
  {level:4, text:'Киберспорт', icon:'🎮', mode:'word'},
  // ---------- Уровень 4 (14 лет): Действие ----------
  {level:4, text:'Снимает видео для соцсети', icon:'🎥'},
  {level:4, text:'Играет в киберспорт', icon:'🎮'},
  {level:4, text:'Делает домашку в последний момент', icon:'📚'},
  {level:4, text:'Спорит с родителями из-за телефона', icon:'📱'},
  {level:4, text:'Готовится к экзамену', icon:'✏️'},
  {level:4, text:'Красится перед зеркалом', icon:'💄'},
  {level:4, text:'Слушает музыку в наушниках', icon:'🎧'},
  {level:4, text:'Листает ленту в телефоне', icon:'📱'},
  {level:4, text:'Заказывает еду онлайн', icon:'🍔'},
  {level:4, text:'Играет в настольный теннис', icon:'🏓'},
  {level:4, text:'Едет на самокате в школу', icon:'🛴'},
  {level:4, text:'Спорит с другом по видеозвонку', icon:'📹'},
  {level:4, text:'Собирается на дискотеку', icon:'🕺'},
  {level:4, text:'Фотографирует закат', icon:'📸'},
  {level:4, text:'Танцует под любимый трек', icon:'🎶'},
];
