// cards_kids_krokodil.js — данные для детской версии игры «Крокодил».
// Уровень (1-4) берётся не из отдельного экрана настройки, а из общего
// переключателя возраста #kidsAgeGroup на экране "Игры с детьми"
// (state.kidsAge) — тот же id, что и level карточек здесь (как в
// cards_kids_td.js).
// KIDS_KROKODIL_LEVELS — 4 возрастные группы (id, name, desc, icon).
// KIDS_KROKODIL_CARDS — { level, text, icon, mode? }: mode:'word' — простые
// одиночные слова (классический Крокодил), без mode — сценки/действия
// (что показывающий изображает движением).

const KIDS_KROKODIL_LEVELS = [
  {id:1, icon:'🧸', name:'5 лет', desc:'Простые знакомые слова и движения'},
  {id:2, icon:'🎈', name:'7 лет', desc:'Школа, игры во дворе, мультфильмы'},
  {id:3, icon:'🚀', name:'10 лет', desc:'Увлечения, приключения, фантазия'},
  {id:4, icon:'🏆', name:'14 лет', desc:'Подростковые темы и тренды'},
];

const KIDS_KROKODIL_CARDS = [
  // ---------- Уровень 1 (5 лет): Слово ----------
  {level:1, text:'Кот', icon:'🐱', mode:'word'},
  {level:1, text:'Собака', icon:'🐶', mode:'word'},
  {level:1, text:'Мяч', icon:'⚽', mode:'word'},
  {level:1, text:'Яблоко', icon:'🍎', mode:'word'},
  {level:1, text:'Стол', icon:'🪑', mode:'word'},
  {level:1, text:'Солнце', icon:'☀️', mode:'word'},
  {level:1, text:'Луна', icon:'🌙', mode:'word'},
  {level:1, text:'Рыба', icon:'🐟', mode:'word'},
  {level:1, text:'Птица', icon:'🐦', mode:'word'},
  {level:1, text:'Дом', icon:'🏠', mode:'word'},
  {level:1, text:'Машина', icon:'🚗', mode:'word'},
  {level:1, text:'Цветок', icon:'🌸', mode:'word'},
  {level:1, text:'Дерево', icon:'🌳', mode:'word'},
  {level:1, text:'Зонт', icon:'☂️', mode:'word'},
  {level:1, text:'Шарик', icon:'🎈', mode:'word'},
  // ---------- Уровень 1 (5 лет): Действие ----------
  {level:1, text:'Спит', icon:'😴'},
  {level:1, text:'Плачет', icon:'😢'},
  {level:1, text:'Смеётся', icon:'😂'},
  {level:1, text:'Прыгает', icon:'🤸'},
  {level:1, text:'Бежит', icon:'🏃'},
  {level:1, text:'Ест', icon:'🍽️'},
  {level:1, text:'Пьёт', icon:'🥤'},
  {level:1, text:'Танцует', icon:'💃'},
  {level:1, text:'Поёт', icon:'🎤'},
  {level:1, text:'Летает как птица', icon:'🕊️'},
  {level:1, text:'Плавает', icon:'🏊'},
  {level:1, text:'Рисует', icon:'🎨'},
  {level:1, text:'Читает книжку', icon:'📖'},
  {level:1, text:'Моет руки', icon:'🧼'},
  {level:1, text:'Чистит зубы', icon:'🪥'},
  // ---------- Уровень 1 (5 лет): Слово (дополнение) ----------
  {level:1, text:'Заяц', icon:'🐰', mode:'word'},
  {level:1, text:'Мишка', icon:'🐻', mode:'word'},
  {level:1, text:'Лиса', icon:'🦊', mode:'word'},
  {level:1, text:'Волк', icon:'🐺', mode:'word'},
  {level:1, text:'Ёжик', icon:'🦔', mode:'word'},
  {level:1, text:'Белка', icon:'🐿️', mode:'word'},
  {level:1, text:'Бабочка', icon:'🦋', mode:'word'},
  {level:1, text:'Пчела', icon:'🐝', mode:'word'},
  {level:1, text:'Корова', icon:'🐮', mode:'word'},
  {level:1, text:'Лошадь', icon:'🐴', mode:'word'},
  {level:1, text:'Утка', icon:'🦆', mode:'word'},
  {level:1, text:'Курица', icon:'🐔', mode:'word'},
  {level:1, text:'Свинья', icon:'🐷', mode:'word'},
  {level:1, text:'Коза', icon:'🐐', mode:'word'},
  {level:1, text:'Обезьяна', icon:'🐵', mode:'word'},
  {level:1, text:'Слон', icon:'🐘', mode:'word'},
  {level:1, text:'Жираф', icon:'🦒', mode:'word'},
  {level:1, text:'Телефон', icon:'📞', mode:'word'},
  {level:1, text:'Книга', icon:'📖', mode:'word'},
  {level:1, text:'Ложка', icon:'🥄', mode:'word'},
  {level:1, text:'Чашка', icon:'☕', mode:'word'},
  {level:1, text:'Кровать', icon:'🛏️', mode:'word'},
  {level:1, text:'Стул', icon:'🪑', mode:'word'},
  {level:1, text:'Окно', icon:'🪟', mode:'word'},
  {level:1, text:'Дверь', icon:'🚪', mode:'word'},
  {level:1, text:'Лестница', icon:'🪜', mode:'word'},
  {level:1, text:'Гора', icon:'⛰️', mode:'word'},
  {level:1, text:'Море', icon:'🌊', mode:'word'},
  {level:1, text:'Река', icon:'🏞️', mode:'word'},
  {level:1, text:'Гриб', icon:'🍄', mode:'word'},
  {level:1, text:'Морковка', icon:'🥕', mode:'word'},
  {level:1, text:'Огурец', icon:'🥒', mode:'word'},
  {level:1, text:'Банан', icon:'🍌', mode:'word'},
  {level:1, text:'Арбуз', icon:'🍉', mode:'word'},
  {level:1, text:'Печенье', icon:'🍪', mode:'word'},
  // ---------- Уровень 1 (5 лет): Действие (дополнение) ----------
  {level:1, text:'Хлопает в ладоши', icon:'👏'},
  {level:1, text:'Топает ногами', icon:'🦶'},
  {level:1, text:'Машет рукой', icon:'👋'},
  {level:1, text:'Качает головой', icon:'🙂'},
  {level:1, text:'Кивает', icon:'✅'},
  {level:1, text:'Смотрит в бинокль', icon:'🔭'},
  {level:1, text:'Зевает', icon:'🥱'},
  {level:1, text:'Чихает', icon:'🤧'},
  {level:1, text:'Кашляет', icon:'😷'},
  {level:1, text:'Улыбается', icon:'😊'},
  {level:1, text:'Хмурится', icon:'😠'},
  {level:1, text:'Прячется', icon:'🙈'},
  {level:1, text:'Ищет что-то по комнате', icon:'🔍'},
  {level:1, text:'Дарит цветочек', icon:'💐'},
  {level:1, text:'Дует на свечку', icon:'🕯️'},
  {level:1, text:'Крутит обруч', icon:'⭕'},
  {level:1, text:'Играет в ладушки', icon:'🖐️'},
  {level:1, text:'Кувыркается', icon:'🤸'},
  {level:1, text:'Ползает', icon:'🐾'},
  {level:1, text:'Лазает по лесенке', icon:'🪜'},
  {level:1, text:'Толкает мяч', icon:'⚽'},
  {level:1, text:'Ловит мяч', icon:'🤲'},
  {level:1, text:'Бросает мяч', icon:'🎯'},
  {level:1, text:'Катает машинку', icon:'🚗'},
  {level:1, text:'Строит башню из кубиков', icon:'🧱'},
  {level:1, text:'Убирает игрушки', icon:'🧸'},
  {level:1, text:'Поливает цветы', icon:'🌷'},
  {level:1, text:'Подметает пол', icon:'🧹'},
  {level:1, text:'Моет посуду', icon:'🍽️'},
  {level:1, text:'Вытирает пыль', icon:'🧽'},
  {level:1, text:'Смотрит телевизор', icon:'📺'},
  {level:1, text:'Слушает сказку', icon:'📚'},
  {level:1, text:'Обнимает маму', icon:'🤗'},
  {level:1, text:'Целует маму', icon:'😘'},
  {level:1, text:'Машет на прощание', icon:'👋'},

  // ---------- Уровень 2 (7 лет): Слово ----------
  {level:2, text:'Школа', icon:'🏫', mode:'word'},
  {level:2, text:'Портфель', icon:'🎒', mode:'word'},
  {level:2, text:'Карандаш', icon:'✏️', mode:'word'},
  {level:2, text:'Учитель', icon:'🧑‍🏫', mode:'word'},
  {level:2, text:'Друг', icon:'🧑‍🤝‍🧑', mode:'word'},
  {level:2, text:'Велосипед', icon:'🚲', mode:'word'},
  {level:2, text:'Качели', icon:'🛝', mode:'word'},
  {level:2, text:'Мороженое', icon:'🍦', mode:'word'},
  {level:2, text:'Пицца', icon:'🍕', mode:'word'},
  {level:2, text:'Робот', icon:'🤖', mode:'word'},
  {level:2, text:'Динозавр', icon:'🦕', mode:'word'},
  {level:2, text:'Ракета', icon:'🚀', mode:'word'},
  {level:2, text:'Клоун', icon:'🤡', mode:'word'},
  {level:2, text:'Скакалка', icon:'🪢', mode:'word'},
  {level:2, text:'Самокат', icon:'🛴', mode:'word'},
  // ---------- Уровень 2 (7 лет): Действие ----------
  {level:2, text:'Чистит зубы перед сном', icon:'🪥'},
  {level:2, text:'Делает домашнее задание', icon:'📝'},
  {level:2, text:'Катается на велосипеде', icon:'🚲'},
  {level:2, text:'Играет в футбол', icon:'⚽'},
  {level:2, text:'Прыгает через скакалку', icon:'🪢'},
  {level:2, text:'Строит замок из песка', icon:'🏰'},
  {level:2, text:'Ловит бабочку сачком', icon:'🦋'},
  {level:2, text:'Печёт пирог с мамой', icon:'🥧'},
  {level:2, text:'Собирает пазл', icon:'🧩'},
  {level:2, text:'Смотрит мультфильм', icon:'📺'},
  {level:2, text:'Едет на самокате', icon:'🛴'},
  {level:2, text:'Кормит рыбок в аквариуме', icon:'🐠'},
  {level:2, text:'Поливает цветы из лейки', icon:'🪴'},
  {level:2, text:'Играет в прятки', icon:'🙈'},
  {level:2, text:'Задувает свечи на торте', icon:'🎂'},
  // ---------- Уровень 2 (7 лет): Слово (дополнение) ----------
  {level:2, text:'Тетрадь', icon:'📓', mode:'word'},
  {level:2, text:'Ручка', icon:'🖊️', mode:'word'},
  {level:2, text:'Линейка', icon:'📏', mode:'word'},
  {level:2, text:'Ластик', icon:'🧽', mode:'word'},
  {level:2, text:'Дневник', icon:'📔', mode:'word'},
  {level:2, text:'Звонок', icon:'🔔', mode:'word'},
  {level:2, text:'Перемена', icon:'🛝', mode:'word'},
  {level:2, text:'Доска', icon:'🖥️', mode:'word'},
  {level:2, text:'Парта', icon:'🪑', mode:'word'},
  {level:2, text:'Читальня', icon:'📚', mode:'word'},
  {level:2, text:'Библиотека', icon:'🏛️', mode:'word'},
  {level:2, text:'Баскетбол', icon:'🏀', mode:'word'},
  {level:2, text:'Хоккей', icon:'🏒', mode:'word'},
  {level:2, text:'Шайба', icon:'🏒', mode:'word'},
  {level:2, text:'Вратарь', icon:'🧤', mode:'word'},
  {level:2, text:'Свисток', icon:'🎺', mode:'word'},
  {level:2, text:'Медаль', icon:'🥇', mode:'word'},
  {level:2, text:'Кубок', icon:'🏆', mode:'word'},
  {level:2, text:'Сок', icon:'🧃', mode:'word'},
  {level:2, text:'Компот', icon:'🍹', mode:'word'},
  {level:2, text:'Блины', icon:'🥞', mode:'word'},
  {level:2, text:'Сыр', icon:'🧀', mode:'word'},
  {level:2, text:'Колбаса', icon:'🌭', mode:'word'},
  {level:2, text:'Суп', icon:'🍲', mode:'word'},
  {level:2, text:'Салат', icon:'🥗', mode:'word'},
  {level:2, text:'Йогурт', icon:'🥛', mode:'word'},
  {level:2, text:'Булка', icon:'🥐', mode:'word'},
  {level:2, text:'Конфета', icon:'🍬', mode:'word'},
  {level:2, text:'Шоколад', icon:'🍫', mode:'word'},
  {level:2, text:'Зефир', icon:'🍥', mode:'word'},
  {level:2, text:'Торт', icon:'🎂', mode:'word'},
  {level:2, text:'Пирог', icon:'🥧', mode:'word'},
  {level:2, text:'Матрёшка', icon:'🪆', mode:'word'},
  {level:2, text:'Игрушка', icon:'🧸', mode:'word'},
  {level:2, text:'Пазл', icon:'🧩', mode:'word'},
  // ---------- Уровень 2 (7 лет): Действие (дополнение) ----------
  {level:2, text:'Пишет в тетради', icon:'✍️'},
  {level:2, text:'Читает книгу', icon:'📖'},
  {level:2, text:'Решает примеры', icon:'🧮'},
  {level:2, text:'Рисует мелками на асфальте', icon:'🖍️'},
  {level:2, text:'Играет в настольную игру', icon:'🎲'},
  {level:2, text:'Играет в догонялки', icon:'🏃'},
  {level:2, text:'Кидает снежки', icon:'⛄'},
  {level:2, text:'Лепит снеговика', icon:'☃️'},
  {level:2, text:'Катается на санках', icon:'🛷'},
  {level:2, text:'Катается на коньках', icon:'⛸️'},
  {level:2, text:'Идёт в школу с ранцем', icon:'🎒'},
  {level:2, text:'Отвечает у доски', icon:'🖥️'},
  {level:2, text:'Поднимает руку', icon:'🙋'},
  {level:2, text:'Дежурит в столовой', icon:'🍽️'},
  {level:2, text:'Раздаёт тетради', icon:'📓'},
  {level:2, text:'Готовит бутерброд', icon:'🥪'},
  {level:2, text:'Заваривает чай', icon:'🫖'},
  {level:2, text:'Наливает компот', icon:'🍹'},
  {level:2, text:'Чистит картошку', icon:'🥔'},
  {level:2, text:'Месит тесто', icon:'🥖'},
  {level:2, text:'Печёт печенье', icon:'🍪'},
  {level:2, text:'Украшает пряник', icon:'🍪'},
  {level:2, text:'Жонглирует мячиками', icon:'🤹'},
  {level:2, text:'Спускается с горки', icon:'🛝'},
  {level:2, text:'Качается на качелях', icon:'🛝'},
  {level:2, text:'Играет в бадминтон', icon:'🏸'},
  {level:2, text:'Играет в теннис', icon:'🎾'},
  {level:2, text:'Собирает листья', icon:'🍂'},
  {level:2, text:'Гуляет с собакой', icon:'🐕'},
  {level:2, text:'Кормит кота', icon:'🐈'},
  {level:2, text:'Поит цыплят', icon:'🐤'},
  {level:2, text:'Чистит аквариум', icon:'🐠'},
  {level:2, text:'Ухаживает за хомяком', icon:'🐹'},
  {level:2, text:'Моет овощи', icon:'🥕'},
  {level:2, text:'Сервирует стол', icon:'🍽️'},

  // ---------- Уровень 3 (10 лет): Слово ----------
  {level:3, text:'Компьютер', icon:'💻', mode:'word'},
  {level:3, text:'Наушники', icon:'🎧', mode:'word'},
  {level:3, text:'Скейтборд', icon:'🛹', mode:'word'},
  {level:3, text:'Гитара', icon:'🎸', mode:'word'},
  {level:3, text:'Телескоп', icon:'🔭', mode:'word'},
  {level:3, text:'Комикс', icon:'📚', mode:'word'},
  {level:3, text:'Ниндзя', icon:'🥷', mode:'word'},
  {level:3, text:'Супергерой', icon:'🦸', mode:'word'},
  {level:3, text:'Астронавт', icon:'🧑‍🚀', mode:'word'},
  {level:3, text:'Пират', icon:'🏴‍☠️', mode:'word'},
  {level:3, text:'Волшебник', icon:'🧙', mode:'word'},
  {level:3, text:'Единорог', icon:'🦄', mode:'word'},
  {level:3, text:'Дракон', icon:'🐉', mode:'word'},
  {level:3, text:'Батут', icon:'🤾', mode:'word'},
  {level:3, text:'Конструктор', icon:'🧱', mode:'word'},
  // ---------- Уровень 3 (10 лет): Действие ----------
  {level:3, text:'Играет в видеоигру с джойстиком', icon:'🎮'},
  {level:3, text:'Катается на скейтборде', icon:'🛹'},
  {level:3, text:'Играет на гитаре', icon:'🎸'},
  {level:3, text:'Делает селфи', icon:'🤳'},
  {level:3, text:'Собирает конструктор', icon:'🧱'},
  {level:3, text:'Занимается карате', icon:'🥋'},
  {level:3, text:'Плавает в бассейне', icon:'🏊'},
  {level:3, text:'Прыгает на батуте', icon:'🤾'},
  {level:3, text:'Разгадывает кроссворд', icon:'📰'},
  {level:3, text:'Изучает звёзды в телескоп', icon:'🔭'},
  {level:3, text:'Играет в шахматы', icon:'♟️'},
  {level:3, text:'Танцует брейк-данс', icon:'🕺'},
  {level:3, text:'Ищет клад по карте', icon:'🗺️'},
  {level:3, text:'Печёт печенье', icon:'🍪'},
  {level:3, text:'Запускает воздушного змея', icon:'🪁'},
  // ---------- Уровень 3 (10 лет): Слово (дополнение) ----------
  {level:3, text:'Планшет', icon:'📱', mode:'word'},
  {level:3, text:'Смартфон', icon:'📲', mode:'word'},
  {level:3, text:'Клавиатура', icon:'⌨️', mode:'word'},
  {level:3, text:'Джойстик', icon:'🕹️', mode:'word'},
  {level:3, text:'Квест', icon:'🗺️', mode:'word'},
  {level:3, text:'Кроссворд', icon:'📰', mode:'word'},
  {level:3, text:'Загадка', icon:'🤔', mode:'word'},
  {level:3, text:'Ребус', icon:'🧩', mode:'word'},
  {level:3, text:'Шахматы', icon:'♟️', mode:'word'},
  {level:3, text:'Шашки', icon:'🔴', mode:'word'},
  {level:3, text:'Домино', icon:'🎲', mode:'word'},
  {level:3, text:'Трек', icon:'🏔️', mode:'word'},
  {level:3, text:'Вершина', icon:'⛰️', mode:'word'},
  {level:3, text:'Компас', icon:'🧭', mode:'word'},
  {level:3, text:'Карта', icon:'🗺️', mode:'word'},
  {level:3, text:'Палатка', icon:'⛺', mode:'word'},
  {level:3, text:'Костёр', icon:'🔥', mode:'word'},
  {level:3, text:'Поход', icon:'🥾', mode:'word'},
  {level:3, text:'Рюкзак', icon:'🎒', mode:'word'},
  {level:3, text:'Трюк', icon:'🤸', mode:'word'},
  {level:3, text:'Танцор', icon:'💃', mode:'word'},
  {level:3, text:'Иллюзионист', icon:'🎩', mode:'word'},
  {level:3, text:'Фокусник', icon:'🪄', mode:'word'},
  {level:3, text:'Маска', icon:'🎭', mode:'word'},
  {level:3, text:'Костюм', icon:'👗', mode:'word'},
  {level:3, text:'Принцесса', icon:'👸', mode:'word'},
  {level:3, text:'Рыцарь', icon:'🛡️', mode:'word'},
  {level:3, text:'Феникс', icon:'🦅', mode:'word'},
  {level:3, text:'Русалка', icon:'🧜', mode:'word'},
  {level:3, text:'Джинн', icon:'🧞', mode:'word'},
  {level:3, text:'Лабиринт', icon:'🌀', mode:'word'},
  {level:3, text:'Капсула времени', icon:'⏳', mode:'word'},
  {level:3, text:'Эксперимент', icon:'⚗️', mode:'word'},
  {level:3, text:'Микроскоп', icon:'🔬', mode:'word'},
  {level:3, text:'Спутник', icon:'🛰️', mode:'word'},
  // ---------- Уровень 3 (10 лет): Действие (дополнение) ----------
  {level:3, text:'Пишет код на компьютере', icon:'💻'},
  {level:3, text:'Собирает робота', icon:'🤖'},
  {level:3, text:'Делает презентацию', icon:'📊'},
  {level:3, text:'Побеждает в гоночной игре', icon:'🏎️'},
  {level:3, text:'Проходит сложный уровень', icon:'🎮'},
  {level:3, text:'Чинит велосипед', icon:'🛠️'},
  {level:3, text:'Собирает палатку', icon:'⛺'},
  {level:3, text:'Разводит костёр', icon:'🔥'},
  {level:3, text:'Ориентируется по компасу', icon:'🧭'},
  {level:3, text:'Рисует карту сокровищ', icon:'🗺️'},
  {level:3, text:'Решение головоломки', icon:'🧩'},
  {level:3, text:'Распутывает узел', icon:'🪢'},
  {level:3, text:'Показывает фокус', icon:'🪄'},
  {level:3, text:'Выступает на сцене', icon:'🎤'},
  {level:3, text:'Поёт под гитару', icon:'🎸'},
  {level:3, text:'Пишет песню', icon:'🎼'},
  {level:3, text:'Создаёт комикс', icon:'📚'},
  {level:3, text:'Придумывает рассказ', icon:'📝'},
  {level:3, text:'Снимает короткое видео', icon:'🎥'},
  {level:3, text:'Монтирует видео', icon:'🎬'},
  {level:3, text:'Участвует в квесте', icon:'🗝️'},
  {level:3, text:'Выбирается из лабиринта', icon:'🌀'},
  {level:3, text:'Собирает кубик Рубика', icon:'🎲'},
  {level:3, text:'Жонглирует', icon:'🤹'},
  {level:3, text:'Ходит на ходулях', icon:'🦵'},
  {level:3, text:'Ездит на роликах', icon:'🛼'},
  {level:3, text:'Работает с микроскопом', icon:'🔬'},
  {level:3, text:'Проводит опыт', icon:'⚗️'},
  {level:3, text:'Сажает растение', icon:'🪴'},
  {level:3, text:'Ухаживает за питомцем', icon:'🐶'},
  {level:3, text:'Запускает ракету', icon:'🚀'},
  {level:3, text:'Наблюдает за звёздами', icon:'🔭'},
  {level:3, text:'Делает уроки по видео', icon:'📹'},
  {level:3, text:'Читает комикс', icon:'📚'},
  {level:3, text:'Играет на барабанах', icon:'🥁'},

  // ---------- Уровень 4 (14 лет): Слово ----------
  {level:4, text:'Смартфон', icon:'📱', mode:'word'},
  {level:4, text:'Скейтпарк', icon:'🛹', mode:'word'},
  {level:4, text:'Плейлист', icon:'🎵', mode:'word'},
  {level:4, text:'Стример', icon:'🎥', mode:'word'},
  {level:4, text:'Хайп', icon:'🔥', mode:'word'},
  {level:4, text:'Челлендж', icon:'🏆', mode:'word'},
  {level:4, text:'Мем', icon:'😂', mode:'word'},
  {level:4, text:'Подкаст', icon:'🎙️', mode:'word'},
  {level:4, text:'Дедлайн', icon:'⏰', mode:'word'},
  {level:4, text:'Кроссовки', icon:'👟', mode:'word'},
  {level:4, text:'Худи', icon:'🧥', mode:'word'},
  {level:4, text:'Пауэрбанк', icon:'🔋', mode:'word'},
  {level:4, text:'Наушники беспроводные', icon:'🎧', mode:'word'},
  {level:4, text:'Селфи-палка', icon:'🤳', mode:'word'},
  {level:4, text:'Киберспорт', icon:'🎮', mode:'word'},
  // ---------- Уровень 4 (14 лет): Действие ----------
  {level:4, text:'Снимает видео для соцсети', icon:'🎥'},
  {level:4, text:'Играет в киберспорт', icon:'🎮'},
  {level:4, text:'Делает домашку в последний момент', icon:'📚'},
  {level:4, text:'Спорит с родителями из-за телефона', icon:'📱'},
  {level:4, text:'Готовится к экзамену', icon:'✏️'},
  {level:4, text:'Красится перед зеркалом', icon:'💄'},
  {level:4, text:'Слушает музыку в наушниках', icon:'🎧'},
  {level:4, text:'Листает ленту в телефоне', icon:'📱'},
  {level:4, text:'Заказывает еду онлайн', icon:'🍔'},
  {level:4, text:'Играет в настольный теннис', icon:'🏓'},
  {level:4, text:'Едет на самокате в школу', icon:'🛴'},
  {level:4, text:'Спорит с другом по видеозвонку', icon:'📹'},
  {level:4, text:'Собирается на дискотеку', icon:'🕺'},
  {level:4, text:'Фотографирует закат', icon:'📸'},
  {level:4, text:'Танцует под любимый трек', icon:'🎶'},
  // ---------- Уровень 4 (14 лет): Слово (дополнение) ----------
  {level:4, text:'Тикток', icon:'📱', mode:'word'},
  {level:4, text:'Рилс', icon:'🎬', mode:'word'},
  {level:4, text:'Блогер', icon:'📸', mode:'word'},
  {level:4, text:'Инфлюенсер', icon:'🌟', mode:'word'},
  {level:4, text:'Вайб', icon:'✨', mode:'word'},
  {level:4, text:'Флекс', icon:'💪', mode:'word'},
  {level:4, text:'Лайк', icon:'👍', mode:'word'},
  {level:4, text:'Рофл', icon:'😂', mode:'word'},
  {level:4, text:'Кринж', icon:'😬', mode:'word'},
  {level:4, text:'Пранк', icon:'🃏', mode:'word'},
  {level:4, text:'Контент', icon:'📝', mode:'word'},
  {level:4, text:'Донат', icon:'💰', mode:'word'},
  {level:4, text:'Стрим', icon:'📺', mode:'word'},
  {level:4, text:'Чатик', icon:'💬', mode:'word'},
  {level:4, text:'Подписчик', icon:'👥', mode:'word'},
  {level:4, text:'Алгоритм', icon:'🤖', mode:'word'},
  {level:4, text:'Сторис', icon:'📖', mode:'word'},
  {level:4, text:'Директ', icon:'✉️', mode:'word'},
  {level:4, text:'Тренд', icon:'📈', mode:'word'},
  {level:4, text:'Хэштег', icon:'#️⃣', mode:'word'},
  {level:4, text:'Аватар', icon:'🖼️', mode:'word'},
  {level:4, text:'Никнейм', icon:'🏷️', mode:'word'},
  {level:4, text:'Геймер', icon:'🎮', mode:'word'},
  {level:4, text:'Нуб', icon:'🍼', mode:'word'},
  {level:4, text:'Квиз', icon:'❓', mode:'word'},
  {level:4, text:'Таймкод', icon:'⏱️', mode:'word'},
  {level:4, text:'Дубль', icon:'🎬', mode:'word'},
  {level:4, text:'Премодерация', icon:'🛡️', mode:'word'},
  {level:4, text:'Спойлер', icon:'🤫', mode:'word'},
  {level:4, text:'Трейлер', icon:'🎥', mode:'word'},
  {level:4, text:'Квир', icon:'🦄', mode:'word'},
  {level:4, text:'Рандом', icon:'🎲', mode:'word'},
  {level:4, text:'Сарказм', icon:'🙃', mode:'word'},
  {level:4, text:'Перфоманс', icon:'🎭', mode:'word'},
  {level:4, text:'Баттл', icon:'⚔️', mode:'word'},
  // ---------- Уровень 4 (14 лет): Действие (дополнение) ----------
  {level:4, text:'Записывает тренд-танец', icon:'🕺'},
  {level:4, text:'Монтирует рилс', icon:'🎬'},
  {level:4, text:'Делает коллаб', icon:'🤝'},
  {level:4, text:'Чатит в стриме', icon:'💬'},
  {level:4, text:'Просматривает сторис', icon:'📖'},
  {level:4, text:'Ставит лайк', icon:'👍'},
  {level:4, text:'Делает репост', icon:'🔁'},
  {level:4, text:'Следит за трендами', icon:'📈'},
  {level:4, text:'Ищет новый плейлист', icon:'🎵'},
  {level:4, text:'Скачивает приложение', icon:'📲'},
  {level:4, text:'Обновляет профиль', icon:'🔄'},
  {level:4, text:'Стримит игру', icon:'🎮'},
  {level:4, text:'Участвует в челлендже', icon:'🏆'},
  {level:4, text:'Делает пранк над другом', icon:'🃏'},
  {level:4, text:'Обсуждает мемы', icon:'😂'},
  {level:4, text:'Отвечает в директ', icon:'✉️'},
  {level:4, text:'Планирует посты', icon:'🗓️'},
  {level:4, text:'Оформляет сторис', icon:'🎨'},
  {level:4, text:'Делает серию фото', icon:'📷'},
  {level:4, text:'Готовит контент-план', icon:'📝'},
  {level:4, text:'Выступает с презентацией', icon:'🎤'},
  {level:4, text:'Защищает проект', icon:'🛡️'},
  {level:4, text:'Пишет эссе', icon:'✍️'},
  {level:4, text:'Собирает портфолио', icon:'📂'},
  {level:4, text:'Волнуется перед собеседованием', icon:'😰'},
  {level:4, text:'Помогает с презентацией', icon:'🖥️'},
  {level:4, text:'Записывает подкаст', icon:'🎙️'},
  {level:4, text:'Репетирует выступление', icon:'🎭'},
  {level:4, text:'Зубрит билеты', icon:'📚'},
  {level:4, text:'Готовит шпаргалки', icon:'📋'},
  {level:4, text:'Решает пробник', icon:'✏️'},
  {level:4, text:'Разбирает ошибки', icon:'🔍'},
  {level:4, text:'Снимает влог', icon:'📹'},
  {level:4, text:'Делает пирсинг', icon:'💉'},
  {level:4, text:'Красит волосы', icon:'🎨'},
];
